BEGIN IMMEDIATE;

-- v0.8.0: Eleusis evidence layers. Historical archaeology, textual myth,
-- public ritual description and modern museum catalogues remain separately scoped.

INSERT OR IGNORE INTO languages(id,canonical_name,name_zh,iso_639_3,script_name,historical_stage,notes) VALUES
('lang.el','Modern Greek','现代希腊语','ell','Greek','Modern','Added for current Greek Ministry and archaeological-project pages; distinct from Ancient Greek lang.grc.');

INSERT OR IGNORE INTO relationship_types(
  code,inverse_code,label_en,label_zh,category,is_symmetric,description
) VALUES
('DEDICATED_TO','HAS_DEDICATION','dedicated to','奉献给','CULT',0,'A text, object or monument records a dedication; this does not imply ownership.'),
('HAS_DEDICATION','DEDICATED_TO','has dedication','接受奉献','CULT',0,'Inverse of DEDICATED_TO.'),
('LATER_COPY_OF','HAS_LATER_COPY','later copy of','后世摹本／复制品','OBJECT',0,'A later object copies or closely reproduces an earlier work; the records remain distinct.'),
('HAS_LATER_COPY','LATER_COPY_OF','has later copy','具有后世摹本／复制品','OBJECT',0,'Inverse of LATER_COPY_OF.'),
('REVEALED_RITES_TO','RECEIVED_RITES_FROM','revealed rites to','向……揭示仪式','MYTH',0,'A source-bounded mythic statement that one figure disclosed rites to another.'),
('RECEIVED_RITES_FROM','REVEALED_RITES_TO','received rites from','从……获授仪式','MYTH',0,'Inverse of REVEALED_RITES_TO.');

INSERT OR IGNORE INTO sources(
  id,title,original_title,source_type,evidence_tier,institution,author_or_editor,
  language_id,publication_date,accessed_date,url,stable_url,doi,isbn,
  catalogue_number,manuscript_number,rights_status,source_perspective,
  community_or_lineage,collector_context,living_tradition,
  access_or_reuse_restrictions,community_permission_required,
  same_witness_as_source_id,translation_status,verification_status,notes
) VALUES
('source.greek.eleusis.efada','Archaeological Site of Eleusis',NULL,'OFFICIAL_ARCHAEOLOGICAL_SITE',3,'Ephorate of Antiquities of West Attica, Hellenic Ministry of Culture',NULL,'lang.en',NULL,'2026-08-21','https://www.efada.gr/en-us/Archaeological-Sites-Monuments/Eleusis/Archaeological-Site-of-Eleusis',NULL,NULL,NULL,'Eleusis archaeological site',NULL,'Copyright Hellenic Ministry of Culture; metadata, locator and independent summary only','Official archaeological-site description',NULL,NULL,0,'Do not package page images or copy extended text',0,NULL,'English official site page','URL_SYNTAX_VALID','Identifies the sanctuary of Demeter and Kore at Eleusis and gives a public archaeological and cult-history overview.'),
('source.greek.eleusis.conservation2023','Eleusis conservation project 2018-2023 workshop','Διημερίδα', 'ARCHAEOLOGICAL_PROJECT',3,'Hellenic Ministry of Culture',NULL,'lang.el','2023-12','2026-08-21','https://eleusis-project-2018-2023.culture.gov.gr/%CE%B4%CE%B9%CE%B7%CE%BC%CE%B5%CF%81%CE%AF%CE%B4%CE%B1/',NULL,NULL,NULL,'Eleusis 2018-2023 conservation project',NULL,'Copyright Hellenic Ministry of Culture; metadata and link only','Official conservation-project record',NULL,NULL,0,'Do not package project images; retain monument names and independent summaries',0,NULL,'Greek official project page','URL_SYNTAX_VALID','Documents conservation and research work concerning the Telesterion, walls, propylaea and Ploutonion.'),
('source.greek.eleusis.hh','Eleusis',NULL,'OFFICIAL_HERITAGE_RECORD',3,'Hellenic Organization of Cultural Resources Development',NULL,'lang.en',NULL,'2026-08-21','https://www.hh.gr/en/destinations/eleusis/',NULL,NULL,NULL,'Eleusis destination record',NULL,'Official destination-page rights apply; metadata, locator and independent summary only','Official public heritage interpretation',NULL,NULL,0,'Do not package page images or extended text',0,NULL,'English official heritage page','URL_SYNTAX_VALID','Describes the Processional Road, continuation of the Sacred Way, propylaea and surviving foundations of the Telesterion.'),
('source.greek.ieleusis97.phi','I.Eleusis 97: dedication to Demeter and Kore',NULL,'INSCRIPTION',1,'Packard Humanities Institute Greek Inscriptions','I.Eleusis / PHI editorial record','lang.grc','321/0 BCE','2026-08-21','https://epigraphy.packhum.org/text/346557',NULL,NULL,NULL,'I.Eleusis 97; IG II² 2841; IG II³,4 213',NULL,'PHI presentation rights apply; locator, catalogue concordance and a very short phrase only','Scholarly epigraphic database record',NULL,NULL,0,'Do not bulk reproduce the inscription corpus',0,NULL,'Ancient Greek inscription with scholarly apparatus','URL_SYNTAX_VALID','Eleusinian dedication naming Demeter and Kore, the official Xenokles and sculptor Aristopeithes.'),
('source.greek.eleusinian_relief.nam126','Classical Period: Great Eleusinian Relief no. 126',NULL,'MUSEUM_OBJECT',3,'National Archaeological Museum, Athens',NULL,'lang.en',NULL,'2026-08-21','https://www.namuseum.gr/en/collection/klasiki-periodos-2/',NULL,NULL,NULL,'NAM 126',NULL,'National Archaeological Museum page rights apply; metadata and link only','Official museum collection description',NULL,'Found at Eleusis; present collection context retained',0,'Do not package museum images',0,NULL,'English museum catalogue page','URL_SYNTAX_VALID','The museum identifies Demeter, Persephone and the young hero Triptolemos on the Great Eleusinian Relief.'),
('source.greek.eleusinian_relief.met141309','Ten marble fragments of the Great Eleusinian Relief, Roman copy',NULL,'MUSEUM_OBJECT',3,'The Metropolitan Museum of Art',NULL,'lang.en','ca. 27 BCE-14 CE','2026-08-21','https://www.metmuseum.org/art/collection/search/248899',NULL,NULL,NULL,'14.130.9',NULL,'Object data and public-domain media follow The Met Open Access terms','Official museum catalogue',NULL,'Roman copy fragments set in a cast; acquisition context retained',0,'No image is packaged in this release',0,NULL,'English museum catalogue','URL_SYNTAX_VALID','The catalogue describes Roman fragments copying the Greek Eleusinian relief and identifies Demeter, Persephone and probably Triptolemos.'),
('source.greek.mystery_cults.met2013','Mystery Cults in the Greek and Roman World',NULL,'MUSEUM_CURATORIAL_ESSAY',4,'The Metropolitan Museum of Art','Kiki Karoglou','lang.en','2013-10','2026-08-21','https://www.metmuseum.org/essays/mystery-cults-in-the-greek-and-roman-world',NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'Copyright The Metropolitan Museum of Art; metadata, locator and independent summary only','Museum scholarly synthesis',NULL,NULL,0,'Do not reproduce extended essay text or images',0,NULL,'English curatorial essay','URL_SYNTAX_VALID','Provides a cautious public synthesis of Eleusinian procession, Telesterion and the fragmentary, localized evidence for mystery cults.');

INSERT OR IGNORE INTO entities(
  id,canonical_name,name_zh,original_name,transliteration,primary_type,
  primary_civilization_id,primary_region_id,historical_period,description,
  research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('concept.greek.eleusinian_secrecy','Eleusinian ritual secrecy','厄琉息斯仪式保密原则',NULL,NULL,'CONCEPT','civ.greek','region.mediterranean','Archaic textual witness and later reception','用于标记古代文本所述的不可泄露性及现代证据边界；不重构未公开的秘仪内容。 / Records ancient claims of restricted disclosure and the modern evidentiary limit without reconstructing secret rites.','PARTIAL','UNVERIFIED',1,'{"methodological_guardrail":"absence of public detail is not permission to invent"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('hero.greek.triptolemos','Triptolemos','特里普托勒摩斯','Τριπτόλεμος','Triptolemos','HERO','civ.greek','region.mediterranean','Archaic and Classical Greek witnesses','《得墨忒耳颂歌》与厄琉息斯图像中的英雄人物；不同传统版本继续分层。 / Hero attested in the Hymn to Demeter and Eleusinian imagery; variant traditions remain open.','PARTIAL','UNVERIFIED',1,'{}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('ritual.greek.eleusinian_mysteries','Eleusinian Mysteries','厄琉息斯秘仪','Ἐλευσίνια Μυστήρια','Eleusinia Mysteria','RITUAL','civ.greek','region.mediterranean','Archaic through Roman-period evidence layers','与得墨忒耳、珀耳塞福涅和厄琉息斯圣所有关的历史仪式传统；公开证据与秘密内容严格区分。 / Historical ritual tradition linked to Demeter, Persephone and Eleusis; public evidence is separated from unrecoverable secret content.','PARTIAL','UNVERIFIED',1,'{"reality_status":"HISTORICAL_RITUAL","secret_content":"NOT_RECONSTRUCTED"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('festival.greek.great_eleusinia','Great Eleusinia','大厄琉息斯节','Μεγάλα Ἐλευσίνια','Megala Eleusinia','FESTIVAL','civ.greek','region.mediterranean','Classical and later public festival layers','从雅典沿圣道前往厄琉息斯的公共节庆／行列层；不等同于秘仪内部全部活动。 / Public festival and procession layer from Athens along the Sacred Way, distinct from all inner initiatory acts.','PARTIAL','UNVERIFIED',1,'{"scope":"public procession layer"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('site.greece.eleusis_telesterion','Telesterion at Eleusis','厄琉息斯特勒斯特里翁仪式厅','Τελεστήριον','Telesterion','ARCHAEOLOGICAL_SITE','civ.greek','region.mediterranean','Multiple building phases; surviving foundations','厄琉息斯圣所内用于仪式集会的建筑子实体；仅保存可公开验证的考古结构。 / Monument-level subrecord for the assembly hall within the sanctuary, limited to public archaeological evidence.','PARTIAL','UNVERIFIED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","part_of":"site.greece.eleusis"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('site.greece.sacred_way','Sacred Way from Athens to Eleusis','雅典至厄琉息斯圣道','Ἱερὰ Ὁδός','Hiera Hodos','ARCHAEOLOGICAL_SITE','civ.greek','region.mediterranean','Ancient route with surviving monuments','连接雅典与厄琉息斯的现实古代道路及仪式行列路线。 / Real ancient road and processional route connecting Athens and Eleusis.','PARTIAL','UNVERIFIED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","route_model":"period-sensitive"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('text.greek.ieleusis97','I.Eleusis 97','《厄琉息斯铭文集》97号',NULL,NULL,'INSCRIPTION','civ.greek','region.mediterranean','321/0 BCE','奉献给得墨忒耳与科瑞的厄琉息斯铭文，保存官员与雕刻者信息。 / Eleusinian dedication to Demeter and Kore naming an official and sculptor.','PARTIAL','UNVERIFIED',1,'{"catalogue_concordance":["I.Eleusis 97","IG II² 2841","IG II³,4 213"]}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('institution.nam_athens','National Archaeological Museum, Athens','雅典国家考古博物馆',NULL,NULL,'INSTITUTION','civ.greek','region.mediterranean','Modern museum institution','收藏大厄琉息斯浮雕126号的现代博物馆机构。 / Modern holding institution for the Great Eleusinian Relief no. 126.','PARTIAL','UNVERIFIED',1,'{}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('museum.nam.great_eleusinian_relief_126','Great Eleusinian Relief no. 126','大厄琉息斯浮雕126号',NULL,NULL,'MUSEUM_OBJECT','civ.greek','region.mediterranean','Classical period, ca. 440-430 BCE','厄琉息斯出土的大型浮雕，博物馆目录识别得墨忒耳、珀耳塞福涅与特里普托勒摩斯。 / Monumental relief from Eleusis catalogued with Demeter, Persephone and Triptolemos.','PARTIAL','UNVERIFIED',1,'{"catalogue_number":"126"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('museum.met.eleusinian_relief_14_130_9','Roman fragments of the Great Eleusinian Relief 14.130.9','大厄琉息斯浮雕罗马摹本残片14.130.9',NULL,NULL,'MUSEUM_OBJECT','civ.greek','region.mediterranean','Roman, ca. 27 BCE-14 CE','大都会艺术博物馆藏十块罗马大理石摹本残片，现嵌于原作石膏模型。 / Ten Roman marble copy fragments at The Met, set into a cast of the Greek relief.','PARTIAL','UNVERIFIED',1,'{"catalogue_number":"14.130.9","copy_status":"ROMAN_COPY_FRAGMENTS"}','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.8.0 Eleusis evidence-layer checkpoint'
FROM entities WHERE created_at='2026-08-21T00:00:00Z';

INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes)
SELECT id,'civ.greek','ORIGIN','SUPPORTED','v0.8.0 source-located Greek baseline'
FROM entities WHERE created_at='2026-08-21T00:00:00Z';

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v080.triptolemos.en','hero.greek.triptolemos','Triptolemos','triptolemos','lang.en','Latin','PREFERRED',1,'source.greek.homeric_hymn_demeter.scaife','Transliteration retained; Triptolemus remains an alias candidate.'),
('name.v080.triptolemos.grc','hero.greek.triptolemos','Τριπτόλεμος','τριπτολεμος','lang.grc','Greek','ORIGINAL',1,'source.greek.homeric_hymn_demeter.scaife',NULL),
('name.v080.triptolemos.zh','hero.greek.triptolemos','特里普托勒摩斯','特里普托勒摩斯','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.mysteries.en','ritual.greek.eleusinian_mysteries','Eleusinian Mysteries','eleusinian mysteries','lang.en','Latin','PREFERRED',1,'source.greek.mystery_cults.met2013',NULL),
('name.v080.mysteries.grc','ritual.greek.eleusinian_mysteries','Ἐλευσίνια Μυστήρια','ελευσινια μυστηρια','lang.grc','Greek','ORIGINAL',1,NULL,'Normalized without diacritics for discovery only.'),
('name.v080.mysteries.zh','ritual.greek.eleusinian_mysteries','厄琉息斯秘仪','厄琉息斯秘仪','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.eleusinia.en','festival.greek.great_eleusinia','Great Eleusinia','great eleusinia','lang.en','Latin','PREFERRED',1,'source.greek.mystery_cults.met2013',NULL),
('name.v080.eleusinia.zh','festival.greek.great_eleusinia','大厄琉息斯节','大厄琉息斯节','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.telesterion.en','site.greece.eleusis_telesterion','Telesterion','telesterion','lang.en','Latin','PREFERRED',1,'source.greek.eleusis.hh',NULL),
('name.v080.telesterion.grc','site.greece.eleusis_telesterion','Τελεστήριον','τελεστηριον','lang.grc','Greek','ORIGINAL',1,NULL,NULL),
('name.v080.telesterion.zh','site.greece.eleusis_telesterion','厄琉息斯特勒斯特里翁仪式厅','厄琉息斯特勒斯特里翁仪式厅','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.sacredway.en','site.greece.sacred_way','Sacred Way','sacred way','lang.en','Latin','PREFERRED',1,'source.greek.eleusis.hh',NULL),
('name.v080.sacredway.grc','site.greece.sacred_way','Ἱερὰ Ὁδός','ιερα οδος','lang.grc','Greek','ORIGINAL',1,NULL,NULL),
('name.v080.sacredway.zh','site.greece.sacred_way','雅典至厄琉息斯圣道','雅典至厄琉息斯圣道','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.ieleusis97.en','text.greek.ieleusis97','I.Eleusis 97','i eleusis 97','lang.en','Latin','PREFERRED',1,'source.greek.ieleusis97.phi',NULL),
('name.v080.nam.en','institution.nam_athens','National Archaeological Museum, Athens','national archaeological museum athens','lang.en','Latin','PREFERRED',1,'source.greek.eleusinian_relief.nam126',NULL),
('name.v080.nam.zh','institution.nam_athens','雅典国家考古博物馆','雅典国家考古博物馆','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.relief126.en','museum.nam.great_eleusinian_relief_126','Great Eleusinian Relief no. 126','great eleusinian relief 126','lang.en','Latin','PREFERRED',1,'source.greek.eleusinian_relief.nam126',NULL),
('name.v080.relief126.zh','museum.nam.great_eleusinian_relief_126','大厄琉息斯浮雕126号','大厄琉息斯浮雕126号','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.metrelief.en','museum.met.eleusinian_relief_14_130_9','Roman fragments of the Great Eleusinian Relief','roman fragments great eleusinian relief','lang.en','Latin','PREFERRED',1,'source.greek.eleusinian_relief.met141309',NULL),
('name.v080.metrelief.zh','museum.met.eleusinian_relief_14_130_9','大厄琉息斯浮雕罗马摹本残片','大厄琉息斯浮雕罗马摹本残片','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v080.secrecy.en','concept.greek.eleusinian_secrecy','Eleusinian ritual secrecy','eleusinian ritual secrecy','lang.en','Latin','PREFERRED',1,'source.greek.homeric_hymn_demeter.scaife',NULL),
('name.v080.secrecy.zh','concept.greek.eleusinian_secrecy','厄琉息斯仪式保密原则','厄琉息斯仪式保密原则','lang.zh','Han','TRANSLATION',1,NULL,NULL);

INSERT OR IGNORE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,date_range,architecture_summary,excavation_summary,major_finds_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.greece.eleusis_telesterion','RITUAL_HALL','Τελεστήριον','Telesterion at Eleusis','GR','Multiple ancient building phases','Large square columned hall with six entrances in the official public description; only foundations survive.','Modern conservation and study are documented by the Hellenic Ministry project.','Architectural foundations and sanctuary context.','NOT_LISTED_AS_INDEPENDENT_PROPERTY','REAL_ARCHAEOLOGICAL','HIGH'),
('site.greece.sacred_way','PROCESSIONAL_ROUTE','Ἱερὰ Ὁδός','Sacred Way, Athens-Eleusis','GR','Ancient route; monuments span multiple periods','Processional route approaching Eleusis and continuing through the sanctuary entrance sequence.','Route and associated monuments require segment-level expansion.','Road segments, funerary monuments and sanctuary approach.','NOT_LISTED_AS_INDEPENDENT_PROPERTY','REAL_ARCHAEOLOGICAL','HIGH');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,composition_period,repository,shelfmark,copyright_status,summary) VALUES
('text.greek.ieleusis97','INSCRIPTION','lang.grc','321/0 BCE','Epigraphic find from Eleusis','I.Eleusis 97; IG II² 2841; IG II³,4 213','Ancient text is public domain; PHI database presentation terms apply','Dedication to Demeter and Kore naming Xenokles and sculptor Aristopeithes.');

INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.nam.great_eleusinian_relief_126','National Archaeological Museum, Athens','126','MARBLE_RELIEF','Found at Eleusis','ca. 440-430 BCE','Official museum collection record; images not packaged.'),
('museum.met.eleusinian_relief_14_130_9','The Metropolitan Museum of Art','14.130.9','MARBLE_RELIEF_FRAGMENTS','Roman copy fragments, set in a cast of the Greek original','ca. 27 BCE-14 CE','Official museum catalogue; public-domain object media is not packaged.');

INSERT OR IGNORE INTO claims(
  id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,
  claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,
  tradition_scope,temporal_scope,research_notes,created_at
) VALUES
('claim.v080.demeter_worshipped_eleusis','deity.greek.demeter','WORSHIPPED_AT','site.greece.eleusis',NULL,NULL,'The official archaeological record identifies Eleusis as the sanctuary of Demeter and Kore.','greek.eleusis.cult','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusinian cult','Ancient sanctuary history','Historical cult-site claim, not a mythic event location.','2026-08-21T00:00:00Z'),
('claim.v080.persephone_worshipped_eleusis','deity.greek.persephone','WORSHIPPED_AT','site.greece.eleusis',NULL,NULL,'The official archaeological record identifies Eleusis as the sanctuary of Demeter and Kore.','greek.eleusis.cult','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusinian cult','Ancient sanctuary history','Kore is mapped to the existing Persephone entity without deleting the Kore name layer.','2026-08-21T00:00:00Z'),
('claim.v080.mysteries_demeter','ritual.greek.eleusinian_mysteries','ASSOCIATED_WITH','deity.greek.demeter',NULL,NULL,'Public archaeological and museum scholarship associate the Eleusinian Mysteries with Demeter.','greek.eleusis.ritual','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Eleusinian ritual','Ancient practice','Association only; secret acts are not reconstructed.','2026-08-21T00:00:00Z'),
('claim.v080.mysteries_persephone','ritual.greek.eleusinian_mysteries','ASSOCIATED_WITH','deity.greek.persephone',NULL,NULL,'Public archaeological and museum scholarship associate the Eleusinian Mysteries with Persephone/Kore.','greek.eleusis.ritual','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Eleusinian ritual','Ancient practice','Kore and Persephone naming is retained at the source layer.','2026-08-21T00:00:00Z'),
('claim.v080.telesterion_part_eleusis','site.greece.eleusis_telesterion','PART_OF','site.greece.eleusis',NULL,NULL,'The Telesterion is modeled as a monument within the wider archaeological site and sanctuary of Eleusis.','greek.eleusis.structure','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','Multiple building phases','Subsite containment, not identity.','2026-08-21T00:00:00Z'),
('claim.v080.telesterion_mysteries','site.greece.eleusis_telesterion','ASSOCIATED_WITH','ritual.greek.eleusinian_mysteries',NULL,NULL,'Official heritage interpretation and museum scholarship identify the Telesterion as the central assembly hall for the mysteries.','greek.eleusis.telesterion','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Eleusinian ritual','Ancient practice','Only the public building-function layer is asserted.','2026-08-21T00:00:00Z'),
('claim.v080.sacredway_eleusis','site.greece.sacred_way','ASSOCIATED_WITH','site.greece.eleusis',NULL,NULL,'The official heritage record describes the Processional Road at Eleusis as continuing the Sacred Way from Athens.','greek.eleusis.route','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Attica','Ancient route','Route geometry and monuments remain queued for expansion.','2026-08-21T00:00:00Z'),
('claim.v080.eleusinia_sacredway','festival.greek.great_eleusinia','ASSOCIATED_WITH','site.greece.sacred_way',NULL,NULL,'Modern museum scholarship describes the public Great Eleusinia procession from Athens to Eleusis along the Sacred Way.','greek.eleusis.procession','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','RITUAL_PRACTICE','Eleusinian festival','Public procession layer','This does not define all period-specific route details.','2026-08-21T00:00:00Z'),
('claim.v080.eleusinia_mysteries','festival.greek.great_eleusinia','ASSOCIATED_WITH','ritual.greek.eleusinian_mysteries',NULL,NULL,'The Great Eleusinia is registered as the public festival/procession layer associated with the mysteries.','greek.eleusis.procession','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','RITUAL_PRACTICE','Eleusinian festival','Ancient practice','Public and inner ritual layers remain distinct.','2026-08-21T00:00:00Z'),
('claim.v080.demeter_revealed_triptolemos','deity.greek.demeter','REVEALED_RITES_TO','hero.greek.triptolemos',NULL,NULL,'Homeric Hymn 2 says Demeter revealed the conduct of her rites to Triptolemos and other Eleusinian leaders.','greek.hymn2.rites','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Homeric Hymn to Demeter','lines 470-479','Textual mythic statement, not independent historical biography.','2026-08-21T00:00:00Z'),
('claim.v080.triptolemos_hymn','hero.greek.triptolemos','MENTIONED_IN','text.greek.homeric_hymn_demeter',NULL,NULL,'Triptolemos is named among those to whom Demeter revealed her rites in Homeric Hymn 2.','greek.hymn2.rites','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Homeric Hymn to Demeter','lines 470-479','Name-level textual attestation.','2026-08-21T00:00:00Z'),
('claim.v080.mysteries_secrecy','ritual.greek.eleusinian_mysteries','ASSOCIATED_WITH','concept.greek.eleusinian_secrecy',NULL,NULL,'Homeric Hymn 2 presents the rites as not lawfully transgressed, investigated or uttered; modern reconstruction must therefore remain evidence-limited.','greek.eleusis.secrecy','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Homeric Hymn to Demeter','lines 478-482','A methodological guardrail, not a claim to know the secret content.','2026-08-21T00:00:00Z'),
('claim.v080.ieleusis97_ded_demeter','text.greek.ieleusis97','DEDICATED_TO','deity.greek.demeter',NULL,NULL,'I.Eleusis 97 records a dedication to Demeter and Kore.','greek.ieleusis97.dedication','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Eleusinian inscription','321/0 BCE','Inscription-level dedication.','2026-08-21T00:00:00Z'),
('claim.v080.ieleusis97_ded_persephone','text.greek.ieleusis97','DEDICATED_TO','deity.greek.persephone',NULL,NULL,'I.Eleusis 97 records a dedication to Demeter and Kore; Kore is linked to the Persephone dossier.','greek.ieleusis97.dedication','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Eleusinian inscription','321/0 BCE','The source name Kore is retained in the claim statement.','2026-08-21T00:00:00Z'),
('claim.v080.ieleusis97_eleusis','text.greek.ieleusis97','EXCAVATED_AT','site.greece.eleusis',NULL,NULL,'The scholarly epigraphic record locates I.Eleusis 97 at Eleusis.','greek.ieleusis97.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','321/0 BCE','Findspot/provenance relationship.','2026-08-21T00:00:00Z'),
('claim.v080.relief126_demeter','museum.nam.great_eleusinian_relief_126','DEPICTS','deity.greek.demeter',NULL,NULL,'The National Archaeological Museum identifies Demeter on the Great Eleusinian Relief no. 126.','greek.relief126.iconography','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Classical Greek relief','ca. 440-430 BCE','Official catalogue identification.','2026-08-21T00:00:00Z'),
('claim.v080.relief126_persephone','museum.nam.great_eleusinian_relief_126','DEPICTS','deity.greek.persephone',NULL,NULL,'The National Archaeological Museum identifies Persephone on the Great Eleusinian Relief no. 126.','greek.relief126.iconography','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Classical Greek relief','ca. 440-430 BCE','Official catalogue identification.','2026-08-21T00:00:00Z'),
('claim.v080.relief126_triptolemos','museum.nam.great_eleusinian_relief_126','DEPICTS','hero.greek.triptolemos',NULL,NULL,'The National Archaeological Museum identifies the young hero Triptolemos on the Great Eleusinian Relief no. 126.','greek.relief126.iconography','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Classical Greek relief','ca. 440-430 BCE','Official catalogue identification.','2026-08-21T00:00:00Z'),
('claim.v080.relief126_held_nam','museum.nam.great_eleusinian_relief_126','HELD_BY_MUSEUM','institution.nam_athens',NULL,NULL,'The National Archaeological Museum, Athens holds the Great Eleusinian Relief no. 126.','greek.relief126.custody','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern custody','Current catalogue','Modern custody only.','2026-08-21T00:00:00Z'),
('claim.v080.relief126_excavated_eleusis','museum.nam.great_eleusinian_relief_126','EXCAVATED_AT','site.greece.eleusis',NULL,NULL,'The National Archaeological Museum states that the Great Eleusinian Relief was found at Eleusis.','greek.relief126.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','Classical object, modern find','Findspot relationship.','2026-08-21T00:00:00Z'),
('claim.v080.metrelief_demeter','museum.met.eleusinian_relief_14_130_9','DEPICTS','deity.greek.demeter',NULL,NULL,'The Met catalogue identifies Demeter in the copied composition represented by object 14.130.9.','greek.met141309.iconography','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Roman copy fragments','ca. 27 BCE-14 CE','Catalogue identification of the copied composition.','2026-08-21T00:00:00Z'),
('claim.v080.metrelief_persephone','museum.met.eleusinian_relief_14_130_9','DEPICTS','deity.greek.persephone',NULL,NULL,'The Met catalogue identifies Persephone in the copied composition represented by object 14.130.9.','greek.met141309.iconography','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Roman copy fragments','ca. 27 BCE-14 CE','Catalogue identification of the copied composition.','2026-08-21T00:00:00Z'),
('claim.v080.metrelief_triptolemos','museum.met.eleusinian_relief_14_130_9','DEPICTS','hero.greek.triptolemos',NULL,NULL,'The Met catalogue identifies the youth in the copied composition as probably Triptolemos.','greek.met141309.iconography','INTERPRETIVE',0.86,'MEDIUM','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Roman copy fragments','ca. 27 BCE-14 CE','The catalogue uncertainty is preserved.','2026-08-21T00:00:00Z'),
('claim.v080.metrelief_held_met','museum.met.eleusinian_relief_14_130_9','HELD_BY_MUSEUM','institution.met',NULL,NULL,'The Metropolitan Museum of Art holds object 14.130.9.','greek.met141309.custody','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern custody','Current catalogue','Modern custody only.','2026-08-21T00:00:00Z'),
('claim.v080.metrelief_copy_relief126','museum.met.eleusinian_relief_14_130_9','LATER_COPY_OF','museum.nam.great_eleusinian_relief_126',NULL,NULL,'The Met catalogues its Roman fragments as a copy of the Greek Great Eleusinian Relief whose original survives in Athens.','greek.eleusinian_relief.copy_network','SUPPORTED',0.97,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Greek original and Roman copy','Greek ca. 440-430 BCE; Roman ca. 27 BCE-14 CE','Copy relation does not merge the objects.','2026-08-21T00:00:00Z');

INSERT OR IGNORE INTO evidence(
  id,claim_id,source_id,source_location,chapter,verse,line,page,catalogue_number,
  short_quote,evidence_type,direction,strength,research_notes
) VALUES
('evidence.v080.demeter_eleusis','claim.v080.demeter_worshipped_eleusis','source.greek.eleusis.efada','Official site overview',NULL,NULL,NULL,NULL,'Eleusis archaeological site',NULL,'OFFICIAL_SITE','SUPPORTS',0.99,'Official public archaeological description checked 2026-08-21.'),
('evidence.v080.persephone_eleusis','claim.v080.persephone_worshipped_eleusis','source.greek.eleusis.efada','Official site overview',NULL,NULL,NULL,NULL,'Eleusis archaeological site',NULL,'OFFICIAL_SITE','SUPPORTS',0.99,'Kore naming retained; mapping to Persephone is explicit.'),
('evidence.v080.mysteries_demeter','claim.v080.mysteries_demeter','source.greek.mystery_cults.met2013','Eleusis section',NULL,NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.99,'Independent summary only.'),
('evidence.v080.mysteries_persephone','claim.v080.mysteries_persephone','source.greek.mystery_cults.met2013','Eleusis section',NULL,NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.99,'Independent summary only.'),
('evidence.v080.telesterion_part','claim.v080.telesterion_part_eleusis','source.greek.eleusis.hh','Monument route and Telesterion description',NULL,NULL,NULL,NULL,'Eleusis destination record',NULL,'OFFICIAL_SITE','SUPPORTS',0.99,'Official public description.'),
('evidence.v080.telesterion_mysteries','claim.v080.telesterion_mysteries','source.greek.mystery_cults.met2013','Eleusis section',NULL,NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.98,'Secret content not reproduced or inferred.'),
('evidence.v080.sacredway_eleusis','claim.v080.sacredway_eleusis','source.greek.eleusis.hh','Processional Road description',NULL,NULL,NULL,NULL,'Eleusis destination record',NULL,'OFFICIAL_SITE','SUPPORTS',0.99,'Official public route description.'),
('evidence.v080.eleusinia_sacredway','claim.v080.eleusinia_sacredway','source.greek.mystery_cults.met2013','Great Eleusinia procession',NULL,NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.96,'Public procession layer only.'),
('evidence.v080.eleusinia_mysteries','claim.v080.eleusinia_mysteries','source.greek.mystery_cults.met2013','Great Eleusinia and mysteries',NULL,NULL,NULL,NULL,'Heilbrunn Timeline essay',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.96,'Public and restricted layers separated.'),
('evidence.v080.demeter_triptolemos','claim.v080.demeter_revealed_triptolemos','source.greek.homeric_hymn_demeter.scaife','Homeric Hymn 2',NULL,NULL,'470-479',NULL,NULL,NULL,'ANCIENT_TEXT','SUPPORTS',0.99,'Line locator only; no extended translation reproduced.'),
('evidence.v080.triptolemos_hymn','claim.v080.triptolemos_hymn','source.greek.homeric_hymn_demeter.scaife','Homeric Hymn 2',NULL,NULL,'470-479',NULL,NULL,NULL,'ANCIENT_TEXT','SUPPORTS',0.99,'Name attestation.'),
('evidence.v080.mysteries_secrecy','claim.v080.mysteries_secrecy','source.greek.homeric_hymn_demeter.scaife','Homeric Hymn 2',NULL,NULL,'478-482',NULL,NULL,NULL,'ANCIENT_TEXT','SUPPORTS',0.98,'Evidence boundary registered; secret content not reconstructed.'),
('evidence.v080.ieleusis97_demeter','claim.v080.ieleusis97_ded_demeter','source.greek.ieleusis97.phi','I.Eleusis 97',NULL,NULL,'1-6',NULL,'I.Eleusis 97',NULL,'INSCRIPTION','SUPPORTS',0.99,'Catalogue and line locator retained.'),
('evidence.v080.ieleusis97_persephone','claim.v080.ieleusis97_ded_persephone','source.greek.ieleusis97.phi','I.Eleusis 97',NULL,NULL,'1-6',NULL,'I.Eleusis 97',NULL,'INSCRIPTION','SUPPORTS',0.98,'Kore source name retained.'),
('evidence.v080.ieleusis97_eleusis','claim.v080.ieleusis97_eleusis','source.greek.ieleusis97.phi','Record provenance',NULL,NULL,NULL,NULL,'I.Eleusis 97',NULL,'INSCRIPTION','SUPPORTS',0.99,'Epigraphic database location.'),
('evidence.v080.relief126_demeter','claim.v080.relief126_demeter','source.greek.eleusinian_relief.nam126','Classical Period collection page',NULL,NULL,NULL,NULL,'NAM 126',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Official museum identification.'),
('evidence.v080.relief126_persephone','claim.v080.relief126_persephone','source.greek.eleusinian_relief.nam126','Classical Period collection page',NULL,NULL,NULL,NULL,'NAM 126',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Official museum identification.'),
('evidence.v080.relief126_triptolemos','claim.v080.relief126_triptolemos','source.greek.eleusinian_relief.nam126','Classical Period collection page',NULL,NULL,NULL,NULL,'NAM 126',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Official museum identification.'),
('evidence.v080.relief126_held','claim.v080.relief126_held_nam','source.greek.eleusinian_relief.nam126','Collection record',NULL,NULL,NULL,NULL,'NAM 126',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Modern custody.'),
('evidence.v080.relief126_findspot','claim.v080.relief126_excavated_eleusis','source.greek.eleusinian_relief.nam126','Object findspot',NULL,NULL,NULL,NULL,'NAM 126',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Museum-stated findspot.'),
('evidence.v080.metrelief_demeter','claim.v080.metrelief_demeter','source.greek.eleusinian_relief.met141309','Object description',NULL,NULL,NULL,NULL,'14.130.9',NULL,'MUSEUM_OBJECT','SUPPORTS',0.98,'Official catalogue identification.'),
('evidence.v080.metrelief_persephone','claim.v080.metrelief_persephone','source.greek.eleusinian_relief.met141309','Object description',NULL,NULL,NULL,NULL,'14.130.9',NULL,'MUSEUM_OBJECT','SUPPORTS',0.98,'Official catalogue identification.'),
('evidence.v080.metrelief_triptolemos','claim.v080.metrelief_triptolemos','source.greek.eleusinian_relief.met141309','Object description',NULL,NULL,NULL,NULL,'14.130.9',NULL,'MUSEUM_OBJECT','SUPPORTS',0.86,'Catalogue probability preserved.'),
('evidence.v080.metrelief_held','claim.v080.metrelief_held_met','source.greek.eleusinian_relief.met141309','Collection record',NULL,NULL,NULL,NULL,'14.130.9',NULL,'MUSEUM_OBJECT','SUPPORTS',0.99,'Modern custody.'),
('evidence.v080.metrelief_copy','claim.v080.metrelief_copy_relief126','source.greek.eleusinian_relief.met141309','Copy/original description',NULL,NULL,NULL,NULL,'14.130.9',NULL,'MUSEUM_OBJECT','SUPPORTS',0.97,'Objects remain separate; no identity merge.');

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v080.eleusinian_secret_content','ritual.greek.eleusinian_mysteries','greek.eleusis.secret_content','claim.v080.mysteries_secrecy','claim.v080.telesterion_mysteries','EVIDENCE_LIMIT','OPEN','Ancient secrecy and fragmentary evidence prevent confident reconstruction of the complete inner ritual from the current public source set.','Preserve public procession, building function, textual prohibitions and later interpretations as separate layers; never fill the gap by invention.');

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,
  next_action='Expand the inscription corpus, Telesterion phases, Sacred Way monuments, Ninnion Tablet and relief copy network while preserving the secrecy evidence limit',
  updated_at='2026-08-21T00:00:00Z'
WHERE id='queue.greek.v050.eleusis_layers';

INSERT OR IGNORE INTO queue_status_history(id,queue_id,old_status,new_status,changed_at,reason) VALUES
('qhist.v080.eleusis_layers','queue.greek.v050.eleusis_layers','SOURCE_FOUND','PARTIAL','2026-08-21T00:00:00Z','Added ritual, hero, monument, inscription and museum-object layers with evidence locators.');

INSERT OR IGNORE INTO collection_queue(
  id,target_label,normalized_label,proposed_entity_type,civilization_id,
  discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,
  discovery_context,priority,status,attempts,last_error,next_action,created_at,updated_at
) VALUES
('queue.v080.greek.eleusis_inscription_corpus','Eleusis inscription corpus beyond I.Eleusis 97','eleusis inscription corpus beyond i eleusis 97','INSCRIPTION','civ.greek','text.greek.ieleusis97','claim.v080.ieleusis97_ded_demeter','source.greek.ieleusis97.phi','The first dated dedication exposes administrators, sculptors and a much larger epigraphic corpus.',99,'SOURCE_FOUND',1,NULL,'Add inscriptions as distinct witnesses with findspot, date, edition concordance and claim-level locators','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('queue.v080.greek.telesterion_phases','Telesterion building phases and conservation history','telesterion building phases and conservation history','ARCHAEOLOGICAL_SITE','civ.greek','site.greece.eleusis_telesterion','claim.v080.telesterion_part_eleusis','source.greek.eleusis.conservation2023','Official conservation records expose multiple monument phases requiring dated structure records.',98,'SOURCE_FOUND',1,NULL,'Add phase-specific architecture, excavations and conservation interventions from project publications','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('queue.v080.greek.sacred_way_monuments','Sacred Way route segments and monuments','sacred way route segments and monuments','ARCHAEOLOGICAL_SITE','civ.greek','site.greece.sacred_way','claim.v080.sacredway_eleusis','source.greek.eleusis.hh','The route record exposes segment-level archaeology and monuments between Athens and Eleusis.',97,'SOURCE_FOUND',1,NULL,'Add geospatial segments, dated monuments and official archaeological records without forcing one timeless route','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('queue.v080.greek.ninnion_tablet','Ninnion Tablet A11036','ninnion tablet a11036','MUSEUM_OBJECT','civ.greek','ritual.greek.eleusinian_mysteries',NULL,'source.greek.eleusinian_relief.nam126','The National Archaeological Museum collection overview identifies another major Eleusinian object.',96,'DISCOVERED',0,NULL,'Register the official object catalogue, iconographic claims and uncertainty before creating the entity','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('queue.v080.greek.eleusinian_relief_copy_network','Great Eleusinian Relief copy and cast network','great eleusinian relief copy and cast network','MUSEUM_OBJECT','civ.greek','museum.met.eleusinian_relief_14_130_9','claim.v080.metrelief_copy_relief126','source.greek.eleusinian_relief.met141309','The Roman fragments and modern cast expose an object-transmission network.',95,'SOURCE_FOUND',1,NULL,'Add provenance, cast history and additional ancient copies without merging objects','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z'),
('queue.v080.greek.mystery_terminology','Eleusinian ritual terminology and translation variants','eleusinian ritual terminology and translation variants','CONCEPT','civ.greek','concept.greek.eleusinian_secrecy','claim.v080.mysteries_secrecy','source.greek.homeric_hymn_demeter.scaife','The hymn and modern scholarship expose source-specific terms whose meanings should not be flattened.',94,'SOURCE_FOUND',1,NULL,'Add Greek terms, translations and witness-specific meanings with philological sources','2026-08-21T00:00:00Z','2026-08-21T00:00:00Z');

INSERT OR IGNORE INTO queue_discoveries(id,queue_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,discovered_at)
SELECT 'discovery.' || substr(id,7),id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,'2026-08-21T00:00:00Z'
FROM collection_queue WHERE id LIKE 'queue.v080.greek.%';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260821.v080_eleusis_layers','2026-08-21T00:00:00Z','2026-08-21T06:00:00Z','Eleusis archaeology, public ritual layer, Homeric Hymn evidence, I.Eleusis 97 and Great Eleusinian Relief object network','Select the highest-value source-found queue target; prioritize primary text, epigraphy, Greek official archaeology and museum catalogues; preserve uncertainty and secrecy boundaries','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Inscription corpus, architecture phases, Sacred Way segments, Ninnion Tablet, copy network and terminology remain queued.');

INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260821.v080_eleusis_layers','SOURCE',id,'REGISTER','URL_SYNTAX_VALID_WITH_LOCATOR_AND_RIGHTS_NOTE' FROM sources WHERE accessed_date='2026-08-21';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260821.v080_eleusis_layers','CLAIM',id,'REGISTER','SOURCE_LOCATED' FROM claims WHERE id LIKE 'claim.v080.%';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260821.v080_eleusis_layers','ENTITY',id,'CREATE','DISCOVERY_PATH_AND_SOURCE_LAYER_REGISTERED' FROM entities WHERE created_at='2026-08-21T00:00:00Z';

UPDATE entities SET evidence_status='PARTIAL',updated_at='2026-08-21T06:00:00Z'
WHERE id IN (SELECT subject_id FROM claims WHERE id LIKE 'claim.v080.%')
   OR id IN (SELECT object_entity_id FROM claims WHERE id LIKE 'claim.v080.%' AND object_entity_id IS NOT NULL);
UPDATE entities SET evidence_status='SOURCE_BACKED',updated_at='2026-08-21T06:00:00Z'
WHERE id IN (SELECT subject_id FROM claims WHERE id LIKE 'claim.v080.%')
  AND NOT EXISTS (SELECT 1 FROM claims c WHERE c.subject_id=entities.id AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.claim_id=c.id));
UPDATE entities SET evidence_status='CONFLICTING',research_status='CONFLICT',updated_at='2026-08-21T06:00:00Z'
WHERE id='ritual.greek.eleusinian_mysteries';

UPDATE civilizations SET research_status='COLLECTING',evidence_status='PARTIAL' WHERE id='civ.greek';
UPDATE project_metadata SET value='0.8.0-eleusis-evidence-layers-20260821',updated_at='2026-08-21T06:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='13',updated_at='2026-08-21T06:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-21T06:00:00Z',updated_at='2026-08-21T06:00:00Z' WHERE key='generated_at';

INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.8.0',13,'0.8.0-eleusis-evidence-layers-20260821',NULL,'2026-08-21T06:00:00Z',NULL,'Eleusis evidence-layer checkpoint: Triptolemos, Eleusinian Mysteries and Great Eleusinia; Telesterion and Sacred Way; I.Eleusis 97; Great Eleusinian Relief original and Roman-copy fragments; explicit secrecy and reconstruction boundary; six permanent follow-up discovery branches.');

INSERT INTO schema_migrations(version,name,applied_at) VALUES
(13,'20260821_v080_eleusis_evidence_layers','2026-08-21T06:00:00Z');

COMMIT;
