BEGIN IMMEDIATE;

-- v0.10.0 separates a named Kamo shrine deity, a fragmentary genealogy,
-- living festival practice and Edo-period visual reception from the Raijin umbrella.

INSERT OR IGNORE INTO sources(
  id,title,original_title,source_type,evidence_tier,institution,author_or_editor,
  language_id,publication_date,accessed_date,url,stable_url,doi,isbn,catalogue_number,
  manuscript_number,rights_status,source_perspective,community_or_lineage,
  collector_context,living_tradition,access_or_reuse_restrictions,
  community_permission_required,same_witness_as_source_id,translation_status,
  verification_status,notes
) VALUES
('source.japanese.kamo_genealogy.kokugakuin','Boshijin','母子神','ACADEMIC_REFERENCE',4,'Kokugakuin University Encyclopedia of Shinto',NULL,'lang.en',NULL,'2026-08-23','https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9452',NULL,NULL,NULL,'Encyclopedia of Shinto ID 9452',NULL,'All rights reserved; metadata, locator and independent summary only','Academic discussion of a fragmentary Yamashiro no kuni fudoki genealogy',NULL,NULL,0,'Do not reproduce extended entry text; preserve its fragmentary-witness scope',0,NULL,'English academic reference','URL_SYNTAX_VALID','Names Tamayorihime and Kamo Taketsunumi as mother and maternal grandfather of Kamo Wakeikazuchi; reports the red-arrow/Honoikazuchi account from a fragmentary provincial gazetteer.'),
('source.japanese.tamayorihime.kokugakuin','Tamayorihime','玉依毘売命','ACADEMIC_REFERENCE',4,'Kokugakuin University Encyclopedia of Shinto',NULL,'lang.en',NULL,'2026-08-23','https://d-museum.kokugakuin.ac.jp/eos/detail/?id=9143',NULL,NULL,NULL,'Encyclopedia of Shinto ID 9143',NULL,'All rights reserved; metadata, locator and independent summary only','Academic deity-name entry preserving multiple Tamayorihime usages',NULL,NULL,0,'Do not flatten the common title and specific Kamo figure; no extended reproduction',0,NULL,'English academic reference','URL_SYNTAX_VALID','The Kamo-context Tamayorihime is daughter of Kamo Taketsunumi and mother of Kamo Wakeikazuchi; other figures bearing the title remain outside this identity.'),
('source.japanese.kamigamo.about','About Kamo Wakeikazuchi Jinja Shrine',NULL,'LIVING_TRADITION_OFFICIAL_SITE',3,'Kamo Wakeikazuchi Jinja Shrine',NULL,'lang.en',NULL,'2026-08-23','https://www.kamigamojinja.jp/en/about/',NULL,NULL,NULL,'Kamigamo Jinja official history and grounds',NULL,'Shrine website rights apply; metadata and independent summary only','Official public self-description of a living shrine tradition','Kamo Wakeikazuchi Jinja Shrine',NULL,1,'Public layer only; do not infer restricted rites or reproduce images',0,NULL,'English official shrine page','URL_SYNTAX_VALID','Public shrine account connects the deity, thunderous ascent/descent legend, Mt. Koyama, shrine origin and Kamo Festival; historical statements remain attributed to shrine records.'),
('source.japanese.kamo_festival.official','Kamo Festival','賀茂祭','LIVING_TRADITION_OFFICIAL_SITE',3,'Kamo Wakeikazuchi Jinja Shrine',NULL,'lang.en',NULL,'2026-08-23','https://www.kamigamojinja.jp/en/rituals/kamo-festival/',NULL,NULL,NULL,'Kamo Festival / Aoi Matsuri official page',NULL,'Shrine website rights apply; metadata and independent summary only','Official public account of a continuing festival','Kamo Wakeikazuchi Jinja Shrine',NULL,1,'Public procession and published ritual outline only; do not infer restricted practice',0,NULL,'English official shrine page','URL_SYNTAX_VALID','Describes the May 15 procession, imperial messenger, public rites and shrine-attributed origin narrative.'),
('source.japanese.kamo_kurabeuma.official','Kamo Kurabeuma Horse Racing Ritual','賀茂競馬','LIVING_TRADITION_OFFICIAL_SITE',3,'Kamo Wakeikazuchi Jinja Shrine',NULL,'lang.en','1093 tradition; current annual practice','2026-08-23','https://www.kamigamojinja.jp/en/rituals/kamo-kurabeuma-horse-racing-ritual/',NULL,NULL,NULL,'Kamo Kurabeuma official page',NULL,'Shrine website rights apply; metadata and independent summary only','Official public account of a continuing horse-racing offering','Kamo Wakeikazuchi Jinja Shrine',NULL,1,'Publicly described practice only; do not package images or infer restricted ritual detail',0,NULL,'English official shrine page','URL_SYNTAX_VALID','Records a May 5 horse-racing offering to Kamo Wakeikazuchi associated with peace, harvest and preparation for the Kamo Festival.'),
('source.japanese.kamigamo.unesco688','Historic Monuments of Ancient Kyoto: Kamowakeikazuchi-jinja component','古都京都の文化財・賀茂別雷神社','OFFICIAL_HERITAGE_RECORD',3,'UNESCO World Heritage Centre',NULL,'lang.en','1994 inscription','2026-08-23','https://whc.unesco.org/en/list/688/maps/',NULL,NULL,NULL,'World Heritage 688-001',NULL,'UNESCO site terms apply; map metadata under stated terms','Official World Heritage component record',NULL,NULL,0,'Store coordinates, component identifier and independent summary only',0,NULL,'English official heritage record','URL_SYNTAX_VALID','Identifies Kamowakeikazuchi-jinja as component 688-001 with coordinates and mapped property/buffer-zone data.');

INSERT OR IGNORE INTO entities(
 id,canonical_name,name_zh,original_name,transliteration,primary_type,
 primary_civilization_id,primary_region_id,historical_period,description,
 research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('deity.japanese.kamo_wakeikazuchi','Kamo Wakeikazuchi no Okami','贺茂别雷大神','賀茂別雷大神','Kamo Wakeikazuchi no Okami','DEITY','civ.japanese_shinto','region.east_asia','Fragmentary Yamashiro Fudoki and living Kamigamo tradition','贺茂别雷神社主祭神；地方谱系、神社传承与雷神总称层分别保存。 / Enshrined deity of Kamigamo Jinja; local genealogy, shrine tradition and the broader Raijin umbrella remain separate.','PARTIAL','UNVERIFIED',1,'{"local_dossier":"Kamigamo/Kamo tradition","dedup_rule":"not identical to umbrella Raijin by name or domain"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('deity.japanese.tamayorihime_kamo','Tamayorihime (Kamo tradition)','玉依姬（贺茂传统）','玉依毘売命','Tamayorihime','DEITY','civ.japanese_shinto','region.east_asia','Fragmentary Yamashiro Fudoki genealogy','贺茂谱系中的玉依姬；“玉依姬”也可指其他人物，因此使用限定实体。 / Kamo-genealogy Tamayorihime; the title/name can denote other figures, so this record is scoped.','PARTIAL','UNVERIFIED',1,'{"homonym_scope":"Kamo tradition; daughter of Kamo Taketsunumi"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('deity.japanese.kamo_taketsunumi','Kamo Taketsunumi no Mikoto','贺茂建角身命','賀茂建角身命','Kamo Taketsunumi no Mikoto','DEITY','civ.japanese_shinto','region.east_asia','Fragmentary Yamashiro Fudoki genealogy','贺茂谱系中玉依姬之父、贺茂别雷之母系祖父。 / Father of Tamayorihime and maternal grandfather of Kamo Wakeikazuchi in the fragmentary genealogy.','PARTIAL','UNVERIFIED',1,'{}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('deity.japanese.honoikazuchi_otokuni','Honoikazuchi (Otokuni tradition)','火雷神（乙训传统）','火雷神','Honoikazuchi no Kami','DEITY','civ.japanese_shinto','region.east_asia','Fragmentary Yamashiro Fudoki, Otokuni context','学术条目所述乙训郡火雷神／红箭谱系人物；不与《古事记》黄泉八雷中的火雷自动合并。 / Honoikazuchi of the Otokuni red-arrow genealogy; not automatically merged with the Kojiki Yomi thunder kami.','PARTIAL','UNVERIFIED',1,'{"identity_caution":"relationship to Kojiki Honoikazuchi unresolved"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('deity.japanese.fujin','Fujin','风神','風神','Fujin','DEITY','civ.japanese_shinto','region.east_asia','Diachronic visual and religious traditions','日本风神入口；本批仅登记宗达屏风中的后世图像见证。 / Japanese wind-deity entry currently limited to the later Sotatsu screen witness.','PARTIAL','UNVERIFIED',1,'{"current_scope":"Edo-period visual witness"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('site.japan.kamigamo_jinja','Kamo Wakeikazuchi Jinja (Kamigamo Jinja)','贺茂别雷神社（上贺茂神社）','賀茂別雷神社','Kamigamo Jinja','ARCHAEOLOGICAL_SITE','civ.japanese_shinto','region.east_asia','Late seventh-century establishment; continuing shrine','京都现实神社与活态宗教遗产，UNESCO古都京都文化财组成部分688-001。 / Real continuing shrine in Kyoto and UNESCO component 688-001.','PARTIAL','UNVERIFIED',1,'{"reality_status":"REAL_LIVING_HERITAGE","unesco_component":"688-001"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('festival.japan.kamo_aoi','Kamo Festival (Aoi Matsuri)','贺茂祭（葵祭）','賀茂祭','Kamo-sai / Aoi Matsuri','FESTIVAL','civ.japanese_shinto','region.east_asia','Living annual festival with layered historical tradition','京都持续举行的公开节庆与仪式传统；神社所述起源、历史制度和现代行列分层保存。 / Continuing Kyoto festival whose shrine-origin narrative, historical institutions and modern procession remain layered.','PARTIAL','UNVERIFIED',1,'{"living_tradition":true,"public_scope_only":true}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('ritual.japan.kamo_kurabeuma','Kamo Kurabeuma Horse Racing Ritual','贺茂竞马仪式','賀茂競馬','Kamo Kurabeuma','RITUAL','civ.japanese_shinto','region.east_asia','Living annual ritual; shrine tradition dates transfer to 1093','上贺茂神社五月五日举行的赛马奉献仪式；仅登记官方公开层。 / May 5 horse-racing offering at Kamigamo Jinja, limited to the official public layer.','PARTIAL','UNVERIFIED',1,'{"living_tradition":true,"public_scope_only":true}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('museum.japan.sotatsu_wind_thunder_screens','Wind God and Thunder God Screens by Tawaraya Sotatsu','俵屋宗达《风神雷神图屏风》','風神雷神図屏風','Fujin Raijin-zu Byobu','MUSEUM_OBJECT','civ.japanese_shinto','region.east_asia','Edo period, seventeenth century','建仁寺所有、京都国立博物馆官方目录记录的宗达屏风；属于后世图像层，不是古代谱系证据。 / Kennin-ji screens catalogued by Kyoto National Museum; a later visual witness, not ancient genealogy evidence.','PARTIAL','UNVERIFIED',1,'{"object_layer":"EDO_VISUAL_RECEPTION","ownership":"Kennin-ji Temple"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('institution.japan.kyoto_national_museum','Kyoto National Museum','京都国立博物馆','京都国立博物館','Kyoto Kokuritsu Hakubutsukan','INSTITUTION','civ.japanese_shinto','region.east_asia','Modern museum institution','为宗达《风神雷神图屏风》提供官方目录与展示记录的现代机构。 / Modern institution providing the official catalogue and exhibition record for the Sotatsu screens.','PARTIAL','UNVERIFIED',1,'{}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('historical.japan.tawaraya_sotatsu','Tawaraya Sotatsu','俵屋宗达','俵屋宗達','Tawaraya Sotatsu','HISTORICAL_FIGURE','civ.japanese_shinto','region.east_asia','Edo period, active early seventeenth century','京都国立博物馆归属《风神雷神图屏风》的画家；历史人物与神话实体分开。 / Historical painter to whom Kyoto National Museum attributes the screens.','PARTIAL','UNVERIFIED',1,'{"reality_status":"HISTORICAL_PERSON"}','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.10.0 Japanese thunder local-dossier checkpoint' FROM entities WHERE created_at='2026-08-23T00:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes)
SELECT id,'civ.japanese_shinto','ORIGIN','SUPPORTED','v0.10.0 source-scoped Japanese dossier' FROM entities WHERE created_at='2026-08-23T00:00:00Z';

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0100.kamo.en','deity.japanese.kamo_wakeikazuchi','Kamo Wakeikazuchi no Okami','kamo wakeikazuchi no okami','lang.en','Latin','PREFERRED',1,'source.japanese.kamigamo.about',NULL),
('name.v0100.kamo.jpn','deity.japanese.kamo_wakeikazuchi','賀茂別雷大神','賀茂別雷大神','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamigamo.about',NULL),
('name.v0100.tamayori.en','deity.japanese.tamayorihime_kamo','Tamayorihime (Kamo tradition)','tamayorihime kamo','lang.en','Latin','PREFERRED',1,'source.japanese.tamayorihime.kokugakuin','Scoped to the Kamo genealogy.'),
('name.v0100.tamayori.jpn','deity.japanese.tamayorihime_kamo','玉依毘売命','玉依毘売命','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.tamayorihime.kokugakuin',NULL),
('name.v0100.taketsunumi.en','deity.japanese.kamo_taketsunumi','Kamo Taketsunumi no Mikoto','kamo taketsunumi no mikoto','lang.en','Latin','PREFERRED',1,'source.japanese.kamo_genealogy.kokugakuin',NULL),
('name.v0100.taketsunumi.jpn','deity.japanese.kamo_taketsunumi','賀茂建角身命','賀茂建角身命','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamo_genealogy.kokugakuin',NULL),
('name.v0100.hono_otokuni.en','deity.japanese.honoikazuchi_otokuni','Honoikazuchi (Otokuni tradition)','honoikazuchi otokuni','lang.en','Latin','PREFERRED',1,'source.japanese.kamo_genealogy.kokugakuin','Scoped to the red-arrow/Otokuni genealogy.'),
('name.v0100.hono_otokuni.jpn','deity.japanese.honoikazuchi_otokuni','火雷神','火雷神','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamo_genealogy.kokugakuin',NULL),
('name.v0100.fujin.en','deity.japanese.fujin','Fujin','fujin','lang.en','Latin','PREFERRED',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.fujin.jpn','deity.japanese.fujin','風神','風神','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.kamigamo.en','site.japan.kamigamo_jinja','Kamo Wakeikazuchi Jinja (Kamigamo Jinja)','kamo wakeikazuchi jinja kamigamo','lang.en','Latin','PREFERRED',1,'source.japanese.kamigamo.unesco688',NULL),
('name.v0100.kamigamo.jpn','site.japan.kamigamo_jinja','賀茂別雷神社','賀茂別雷神社','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamigamo.about',NULL),
('name.v0100.aoi.en','festival.japan.kamo_aoi','Kamo Festival (Aoi Matsuri)','kamo festival aoi matsuri','lang.en','Latin','PREFERRED',1,'source.japanese.kamo_festival.official',NULL),
('name.v0100.aoi.jpn','festival.japan.kamo_aoi','賀茂祭','賀茂祭','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamo_festival.official',NULL),
('name.v0100.kurabeuma.en','ritual.japan.kamo_kurabeuma','Kamo Kurabeuma Horse Racing Ritual','kamo kurabeuma','lang.en','Latin','PREFERRED',1,'source.japanese.kamo_kurabeuma.official',NULL),
('name.v0100.kurabeuma.jpn','ritual.japan.kamo_kurabeuma','賀茂競馬','賀茂競馬','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.kamo_kurabeuma.official',NULL),
('name.v0100.screen.en','museum.japan.sotatsu_wind_thunder_screens','Wind God and Thunder God Screens','wind god thunder god screens','lang.en','Latin','PREFERRED',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.screen.jpn','museum.japan.sotatsu_wind_thunder_screens','風神雷神図屏風','風神雷神図屏風','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.knm.en','institution.japan.kyoto_national_museum','Kyoto National Museum','kyoto national museum','lang.en','Latin','PREFERRED',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.knm.jpn','institution.japan.kyoto_national_museum','京都国立博物館','京都国立博物館','lang.jpn','Kanji','ORIGINAL',1,NULL,NULL),
('name.v0100.sotatsu.en','historical.japan.tawaraya_sotatsu','Tawaraya Sotatsu','tawaraya sotatsu','lang.en','Latin','PREFERRED',1,'source.japanese.raijin_screen.kyohaku',NULL),
('name.v0100.sotatsu.jpn','historical.japan.tawaraya_sotatsu','俵屋宗達','俵屋宗達','lang.jpn','Kanji','ORIGINAL',1,'source.japanese.raijin_screen.kyohaku',NULL);

INSERT OR IGNORE INTO deity_profiles(entity_id,deity_class,pantheon_or_family,rank_or_status,domains_json,powers_json,limitations_json,appearance_json,symbols_json,cult_summary,final_fate_summary) VALUES
('deity.japanese.kamo_wakeikazuchi','REGIONAL_KAMI','Kamo shrine tradition','Enshrined deity of Kamigamo Jinja','["雷的地方传统","降雨与农业的神社公共层"]','[]','["不与雷神总称自动合并","谱系仅限片段文献与神社传承"]','{}','["葵叶与桂枝（祭礼层）"]','Kamigamo Jinja and publicly described Kamo Festival traditions.',NULL),
('deity.japanese.tamayorihime_kamo','GENEALOGICAL_KAMI','Kamo genealogy','Mother figure','[]','[]','["Tamayorihime is also a title/name for other figures"]','{}','[]','Kamo Mioya/Shimogamo context remains queued.',NULL),
('deity.japanese.kamo_taketsunumi','GENEALOGICAL_KAMI','Kamo genealogy','Maternal grandfather figure','[]','[]','["Current dossier is limited to the fragmentary genealogy"]','{}','[]',NULL,NULL),
('deity.japanese.honoikazuchi_otokuni','THUNDER_KAMI','Otokuni red-arrow genealogy','Paternal figure in fragmentary account','["雷"]','[]','["Identity with Kojiki Honoikazuchi unresolved"]','{}','["红箭（片段谱系）"]',NULL,NULL),
('deity.japanese.fujin','WIND_KAMI','Diachronic Japanese traditions','Visual-reception baseline','["风"]','[]','["Current evidence is limited to an Edo-period visual witness"]','{"screen_witness":"Sotatsu composition"}','[]',NULL,NULL);

INSERT OR IGNORE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,latitude,longitude,date_range,architecture_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.japan.kamigamo_jinja','LIVING_SHRINE','賀茂別雷神社','Kamigamo Jinja','JP',35.060528,135.753222,'Late seventh century establishment; later reconstructions; continuing use','Official heritage records distinguish the historical buildings from continuing shrine practice.','WORLD_HERITAGE_COMPONENT_688_001','REAL_SACRED','HIGH');

INSERT OR IGNORE INTO myth_event_profiles(entity_id,event_type,time_layer,cause_summary,process_summary,result_summary,symbolism_summary) VALUES
('festival.japan.kamo_aoi','LIVING_FESTIVAL','Shrine origin tradition, court history and current annual practice','Shrine tradition attributes the origin to rites addressing storms and floods.','The public modern procession travels from the Imperial Palace via Shimogamo to Kamigamo, followed by published rites.','Continuing festival; historical interruptions and revivals remain period-specific.','Aoi and katsura decorations belong to the public festival layer.'),
('ritual.japan.kamo_kurabeuma','LIVING_RITUAL','Shrine tradition dates transfer of the court race to 1093; current annual practice','Presented as an offering ahead of the Kamo Festival.','Purification, prayers and paired horse races are publicly described by the shrine.','Offering for peace, harvest and safe completion.','Not modeled as a modern competitive sport.');

INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.japan.sotatsu_wind_thunder_screens','Kyoto National Museum catalogue; owned by Kennin-ji Temple','National Treasure; Kennin-ji pair','PAIR_OF_TWO_FOLD_SCREENS','Kennin-ji Temple, Kyoto','Edo period, 17th century','Official catalogue states ink and color on gold-foiled paper; no image is packaged.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0100.tamayori_parent_kamo','deity.japanese.tamayorihime_kamo','PARENT_OF','deity.japanese.kamo_wakeikazuchi',NULL,NULL,'Kokugakuin reports the fragmentary Yamashiro genealogy in which Tamayorihime is mother of Kamo Wakeikazuchi.','japan.kamo.fragmentary_genealogy','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Fragmentary Yamashiro no kuni fudoki genealogy','Fragmentary provincial-gazetteer tradition','The surviving fragment is accessed through modern academic reference, not presented as a complete manuscript.','2026-08-23T00:00:00Z'),
('claim.v0100.taketsunumi_parent_tamayori','deity.japanese.kamo_taketsunumi','PARENT_OF','deity.japanese.tamayorihime_kamo',NULL,NULL,'The academic entry identifies Kamo Taketsunumi as father of Tamayorihime in the Kamo genealogy.','japan.kamo.fragmentary_genealogy','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Fragmentary Yamashiro no kuni fudoki genealogy','Fragmentary provincial-gazetteer tradition',NULL,'2026-08-23T00:00:00Z'),
('claim.v0100.hono_parent_kamo','deity.japanese.honoikazuchi_otokuni','PARENT_OF','deity.japanese.kamo_wakeikazuchi',NULL,NULL,'Kokugakuin reports that the red arrow in the fragmentary genealogy is a transformation of Honoikazuchi of Otokuni and fathers Kamo Wakeikazuchi.','japan.kamo.fragmentary_genealogy','SUPPORTED',0.92,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Fragmentary Yamashiro no kuni fudoki genealogy','Fragmentary provincial-gazetteer tradition','The scoped Otokuni entity prevents an unsupported merger with the Kojiki Yomi Honoikazuchi.','2026-08-23T00:00:00Z'),
('claim.v0100.kamo_worshipped_kamigamo','deity.japanese.kamo_wakeikazuchi','WORSHIPPED_AT','site.japan.kamigamo_jinja',NULL,NULL,'The official shrine and heritage records identify Kamo Wakeikazuchi as the enshrined deity of Kamigamo Jinja.','japan.kamigamo.cult','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo public tradition','Current public shrine record','Public self-description, not access to restricted practice.','2026-08-23T00:00:00Z'),
('claim.v0100.kamo_associated_raijin','deity.japanese.kamo_wakeikazuchi','ASSOCIATED_WITH','deity.japanese.raijin',NULL,NULL,'Kamo Wakeikazuchi is connected to the broader Japanese thunder-kami research umbrella while remaining a distinct regional dossier.','japan.thunder.umbrella','SUPPORTED',0.93,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Japanese thunder-kami comparison','Diachronic','Association is a discovery bridge, not an identity merge.','2026-08-23T00:00:00Z'),
('claim.v0100.kamo_associated_thunder','deity.japanese.kamo_wakeikazuchi','ASSOCIATED_WITH','concept.comparative.thunder',NULL,NULL,'The shrine-name, genealogy and official descent account support a source-scoped thunder association for Kamo Wakeikazuchi.','japan.kamo.domain','SUPPORTED',0.95,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','RITUAL_PRACTICE','Kamigamo public tradition','Published shrine and academic layers','No universal fixed thunder-god taxonomy is asserted.','2026-08-23T00:00:00Z'),
('claim.v0100.festival_deity','festival.japan.kamo_aoi','ASSOCIATED_WITH','deity.japanese.kamo_wakeikazuchi',NULL,NULL,'The official festival page presents Kamo Wakeikazuchi as the receiving shrine deity in the Kamo Festival.','japan.kamo.festival','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamo Festival public layer','Current and attributed historical layers','Public official account only.','2026-08-23T00:00:00Z'),
('claim.v0100.festival_site','festival.japan.kamo_aoi','ASSOCIATED_WITH','site.japan.kamigamo_jinja',NULL,NULL,'The public Kamo Festival procession and rites culminate at Kamigamo Jinja.','japan.kamo.festival','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamo Festival public layer','Current annual practice',NULL,'2026-08-23T00:00:00Z'),
('claim.v0100.kurabeuma_deity','ritual.japan.kamo_kurabeuma','ASSOCIATED_WITH','deity.japanese.kamo_wakeikazuchi',NULL,NULL,'The official page describes Kamo Kurabeuma as an offering to Kamo Wakeikazuchi.','japan.kamo.kurabeuma','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo public ritual','Current annual practice','No restricted ritual detail is collected.','2026-08-23T00:00:00Z'),
('claim.v0100.kurabeuma_site','ritual.japan.kamo_kurabeuma','ASSOCIATED_WITH','site.japan.kamigamo_jinja',NULL,NULL,'Kamo Kurabeuma is held within the public grounds of Kamigamo Jinja.','japan.kamo.kurabeuma','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo public ritual','Current annual practice',NULL,'2026-08-23T00:00:00Z'),
('claim.v0100.kurabeuma_festival','ritual.japan.kamo_kurabeuma','ASSOCIATED_WITH','festival.japan.kamo_aoi',NULL,NULL,'The shrine presents Kamo Kurabeuma as a May 5 rite held ahead of the May 15 Kamo Festival.','japan.kamo.kurabeuma','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo public ritual','Current annual cycle',NULL,'2026-08-23T00:00:00Z'),
('claim.v0100.kamigamo_unesco','site.japan.kamigamo_jinja','ASSOCIATED_WITH',NULL,'UNESCO World Heritage component 688-001','text','UNESCO maps identify Kamowakeikazuchi-jinja as component 688-001 of the Historic Monuments of Ancient Kyoto.','japan.kamigamo.heritage','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','World Heritage record','Current official designation','Literal status retained because the World Heritage property is a multi-component record.','2026-08-23T00:00:00Z'),
('claim.v0100.screen_depicts_raijin','museum.japan.sotatsu_wind_thunder_screens','DEPICTS','deity.japanese.raijin',NULL,NULL,'Kyoto National Museum identifies the paired composition as Wind God and Thunder God, providing a seventeenth-century Raijin visual witness.','japan.sotatsu.iconography','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Edo-period visual reception','17th century','This is later iconography, not ancient genealogy.','2026-08-23T00:00:00Z'),
('claim.v0100.screen_depicts_fujin','museum.japan.sotatsu_wind_thunder_screens','DEPICTS','deity.japanese.fujin',NULL,NULL,'Kyoto National Museum identifies the paired composition as Wind God and Thunder God, providing a seventeenth-century Fujin visual witness.','japan.sotatsu.iconography','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Edo-period visual reception','17th century','This is later iconography, not a universal deity profile.','2026-08-23T00:00:00Z'),
('claim.v0100.screen_created_sotatsu','museum.japan.sotatsu_wind_thunder_screens','CREATED_BY','historical.japan.tawaraya_sotatsu',NULL,NULL,'Kyoto National Museum attributes the pair of screens to Tawaraya Sotatsu.','japan.sotatsu.object','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Museum attribution','Edo period, 17th century','The official catalogue notes the work bears no inscription or seal while maintaining the attribution.','2026-08-23T00:00:00Z'),
('claim.v0100.screen_catalogued_knm','museum.japan.sotatsu_wind_thunder_screens','HELD_BY_MUSEUM','institution.japan.kyoto_national_museum',NULL,NULL,'Kyoto National Museum catalogues and exhibits the Kennin-ji screens; the temple ownership statement is retained in the object profile.','japan.sotatsu.custody','SUPPORTED',0.95,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern catalogue and custody layer','Current catalogue','HELD_BY_MUSEUM records catalogue/exhibition custody and does not erase Kennin-ji ownership.','2026-08-23T00:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,short_quote,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(id,7),id,
 CASE
  WHEN id IN ('claim.v0100.tamayori_parent_kamo','claim.v0100.taketsunumi_parent_tamayori','claim.v0100.hono_parent_kamo','claim.v0100.kamo_associated_raijin','claim.v0100.kamo_associated_thunder') THEN 'source.japanese.kamo_genealogy.kokugakuin'
  WHEN id='claim.v0100.kamo_worshipped_kamigamo' THEN 'source.japanese.kamigamo.about'
  WHEN id IN ('claim.v0100.festival_deity','claim.v0100.festival_site') THEN 'source.japanese.kamo_festival.official'
  WHEN id IN ('claim.v0100.kurabeuma_deity','claim.v0100.kurabeuma_site','claim.v0100.kurabeuma_festival') THEN 'source.japanese.kamo_kurabeuma.official'
  WHEN id='claim.v0100.kamigamo_unesco' THEN 'source.japanese.kamigamo.unesco688'
  ELSE 'source.japanese.raijin_screen.kyohaku' END,
 CASE
  WHEN id LIKE 'claim.v0100.%parent%' OR id='claim.v0100.hono_parent_kamo' THEN 'Fragmentary Yamashiro no kuni fudoki genealogy discussion'
  WHEN id LIKE 'claim.v0100.festival_%' THEN 'Kamo Festival public description'
  WHEN id LIKE 'claim.v0100.kurabeuma_%' THEN 'Kamo Kurabeuma public description'
  WHEN id='claim.v0100.kamigamo_unesco' THEN 'World Heritage component map'
  ELSE 'Official catalogue or public institutional description' END,
 CASE WHEN id='claim.v0100.kamigamo_unesco' THEN 'World Heritage 688-001' WHEN id LIKE 'claim.v0100.screen_%' OR id='claim.v0100.raijin_screen' THEN 'National Treasure; Kennin-ji pair' ELSE NULL END,
 NULL,
 CASE WHEN id LIKE 'claim.v0100.screen_%' OR id='claim.v0100.raijin_screen' THEN 'MUSEUM_OBJECT' WHEN id='claim.v0100.kamigamo_unesco' THEN 'OFFICIAL_SITE' WHEN id LIKE 'claim.v0100.%parent%' OR id='claim.v0100.hono_parent_kamo' THEN 'MODERN_SCHOLARSHIP' ELSE 'OFFICIAL_SITE' END,
 'SUPPORTS',confidence,
 'Independent summary only; locator and evidence scope retained.'
FROM claims WHERE id LIKE 'claim.v0100.%';

INSERT OR IGNORE INTO identity_candidates(id,entity_a_id,entity_b_id,assessment,confidence,source_id,notes) VALUES
('identity.v0100.hono_otokuni_vs_kojiki','deity.japanese.honoikazuchi_otokuni','deity.japanese.honoikazuchi','DISPUTED_IDENTITY',0.98,'source.japanese.kamo_genealogy.kokugakuin','Same written thunder name appears in different textual and regional contexts; no redirect until a source establishes identity.'),
('identity.v0100.kamo_vs_raijin','deity.japanese.kamo_wakeikazuchi','deity.japanese.raijin','EXPLICITLY_DISTINCT',0.98,'source.japanese.raijin.kokugakuin','Raijin remains an umbrella entry; the named Kamo shrine deity retains a separate local dossier and may be compared without merger.');

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0100.honoikazuchi_identity','deity.japanese.honoikazuchi_otokuni','japan.honoikazuchi.homonym',NULL,NULL,'IDENTITY','OPEN','The Otokuni red-arrow Honoikazuchi and the Kojiki Yomi Honoikazuchi share a written name but occur in different witness contexts.','Preserve separate entities; future research needs source-specific philology, shrine history and transmission evidence.');

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,updated_at='2026-08-23T00:00:00Z',next_action='Expand Karaijin and additional regional thunder-kami dossiers; add Kamo manuscript/fragment editions and Sotatsu-Korin-Hoitsu copy network without merging local deities' WHERE id='queue.v060.japanese.raijin_regional';
INSERT OR IGNORE INTO queue_status_history(id,queue_id,old_status,new_status,changed_at,reason) VALUES
('queuehist.v0100.raijin_regional','queue.v060.japanese.raijin_regional','SOURCE_FOUND','PARTIAL','2026-08-23T00:00:00Z','Added Kamo local genealogy, shrine, living festival, ritual and Sotatsu visual-reception layers; wider regional expansion remains open.');

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0100.japanese.kamo_fragment_witnesses','Yamashiro Fudoki Kamo genealogy fragment witnesses','yamashiro fudoki kamo genealogy fragment witnesses','MANUSCRIPT','civ.japanese_shinto','deity.japanese.kamo_wakeikazuchi','claim.v0100.tamayori_parent_kamo','source.japanese.kamo_genealogy.kokugakuin','Academic entry exposes a fragmentary witness chain requiring edition-level registration.',98,'DISCOVERED',0,'Register editions, fragment numbers and quotation chains without inventing a complete manuscript','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('queue.v0100.japanese.honoikazuchi_identity','Otokuni and Kojiki Honoikazuchi identity audit','otokuni kojiki honoikazuchi identity audit','DEITY','civ.japanese_shinto','deity.japanese.honoikazuchi_otokuni','claim.v0100.hono_parent_kamo','source.japanese.kamo_genealogy.kokugakuin','Shared written name across regional and Yomi contexts creates a high-risk merge candidate.',99,'CONFLICT',0,'Compare primary-text witnesses, shrine records and academic philology; retain separate entities meanwhile','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('queue.v0100.japanese.kamo_mioya','Kamo Mioya Shrine and mother-child deity complex','kamo mioya shrine mother child deity complex','ARCHAEOLOGICAL_SITE','civ.japanese_shinto','deity.japanese.tamayorihime_kamo','claim.v0100.tamayori_parent_kamo','source.japanese.tamayorihime.kokugakuin','The Kamo genealogy connects Kamigamo and Shimogamo dossiers.',97,'DISCOVERED',0,'Add Shimogamo real-site, UNESCO component, deities and festival relations from official records','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('queue.v0100.japanese.kamo_festival_history','Kamo Festival historical phases and public ritual records','kamo festival historical phases public ritual records','FESTIVAL','civ.japanese_shinto','festival.japan.kamo_aoi','claim.v0100.festival_deity','source.japanese.kamo_festival.official','Official page distinguishes origin legend, court制度, interruption and modern revival.',97,'DISCOVERED',0,'Register dated court records and phase-specific procession claims; respect living-practice boundaries','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('queue.v0100.japanese.sotatsu_copy_network','Sotatsu-Korin-Hoitsu Wind and Thunder screen copy network','sotatsu korin hoitsu wind thunder screen copy network','MUSEUM_OBJECT','civ.japanese_shinto','museum.japan.sotatsu_wind_thunder_screens','claim.v0100.screen_created_sotatsu','source.japanese.raijin_screen.kyohaku','Kyoto National Museum explicitly identifies later replications by Korin and Hoitsu.',98,'DISCOVERED',0,'Add each object, owner, catalogue, date and LATER_COPY_OF relation separately','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z'),
('queue.v0100.japanese.karaijin_local','Karaijin and other regional thunder-kami local dossiers','karaijin regional thunder kami local dossiers','DEITY','civ.japanese_shinto','deity.japanese.raijin','claim.v0100.kamo_associated_raijin','source.japanese.raijin.kokugakuin','The umbrella overview still exposes regional thunder-kami not covered by the Kamo dossier.',98,'DISCOVERED',0,'Use shrine, local-history and academic sources; never promote name similarity to identity','2026-08-23T00:00:00Z','2026-08-23T00:00:00Z');

INSERT OR IGNORE INTO queue_discoveries(id,queue_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,discovered_at)
SELECT 'discovery.'||substr(id,7),id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,'2026-08-23T00:00:00Z' FROM collection_queue WHERE id LIKE 'queue.v0100.%';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260823.v0100_japanese_thunder_local_dossiers','2026-08-23T00:00:00Z','2026-08-23T07:00:00Z','Japanese regional thunder-kami, Kamo genealogy, Kamigamo living heritage and Sotatsu visual reception','Official shrine and museum records, UNESCO heritage metadata and university academic references; separate witness, ritual and visual layers','COMPLETED','Codex autonomous research pipeline','Local failures would be audited without blocking unrelated work; no restricted ritual material was collected.');
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260823.v0100_japanese_thunder_local_dossiers','SOURCE',id,'REGISTER','URL_SYNTAX_VALID_WITH_SCOPE_NOTE' FROM sources WHERE accessed_date='2026-08-23';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260823.v0100_japanese_thunder_local_dossiers','CLAIM',id,'REGISTER','SOURCE_LOCATED' FROM claims WHERE id LIKE 'claim.v0100.%';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260823.v0100_japanese_thunder_local_dossiers','ENTITY',id,'CREATE','LOCAL_DOSSIER_REGISTERED' FROM entities WHERE created_at='2026-08-23T00:00:00Z';

UPDATE entities SET evidence_status='SOURCE_BACKED',updated_at='2026-08-23T07:00:00Z'
WHERE id IN (SELECT subject_id FROM claims WHERE id LIKE 'claim.v0100.%')
AND NOT EXISTS (SELECT 1 FROM claims c WHERE c.subject_id=entities.id AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.claim_id=c.id));
UPDATE entities SET evidence_status='PARTIAL',updated_at='2026-08-23T07:00:00Z'
WHERE evidence_status<>'SOURCE_BACKED' AND id IN (SELECT object_entity_id FROM claims WHERE id LIKE 'claim.v0100.%' AND object_entity_id IS NOT NULL);
UPDATE civilizations SET research_status='COLLECTING',evidence_status='PARTIAL' WHERE id='civ.japanese_shinto';
UPDATE project_metadata SET value='0.10.0-japanese-thunder-local-dossiers-20260823',updated_at='2026-08-23T07:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='17',updated_at='2026-08-23T07:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-23T07:00:00Z',updated_at='2026-08-23T07:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.10.0',17,'0.10.0-japanese-thunder-local-dossiers-20260823',NULL,'2026-08-23T07:00:00Z',NULL,'Japanese thunder local dossiers: Kamo Wakeikazuchi genealogy, Kamigamo site, Kamo/Aoi festival, Kurabeuma ritual, Sotatsu screens, Fujin and explicit identity guardrails.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES
(17,'20260823_v0100_japanese_thunder_local_dossiers','2026-08-23T07:00:00Z');

COMMIT;
