BEGIN IMMEDIATE;

-- v0.12.0 expands the priority-99 Ra/Atum queue while keeping Atum-Ra,
-- Atum-Horakhty, their components, textual witness and Persian-period object
-- context distinct. Name order or shared solar function never triggers a merge.

INSERT OR IGNORE INTO sources(
 id,title,source_type,evidence_tier,institution,author_or_editor,language_id,
 publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,
 access_or_reuse_restrictions,community_permission_required,translation_status,
 verification_status,notes
) VALUES
('source.egypt.late_period_temples.uee2026','Late Period Temples, version 2','PEER_REVIEWED_REFERENCE',2,'UCLA Encyclopedia of Egyptology','Christiane Zivie-Coche','lang.en','2026-06-30','2026-08-25','https://escholarship.org/content/qt70p7j5x9/qt70p7j5x9.pdf','UEE Late Period Temples v2','Copyright author; metadata, page locators and independent summary only','Peer-reviewed Egyptological synthesis','Do not reproduce the article or figures; preserve page locators',0,'English scholarly article','URL_SYNTAX_VALID','Page 16 describes the Susa statue as Egyptian workmanship made for Darius and places him under the protection of Atum-Ra, great one of Heliopolis.'),
('source.egypt.book_dead15.ucl','Book of the Dead Chapter 15: sun hymns','SCHOLARLY_DIGITAL_TEXT',2,'UCL Digital Egypt','Digital Egypt for Universities','lang.en',NULL,'2026-08-25','https://www.ucl.ac.uk/museums-static/digitalegypt/literature/religious/bd15.html','Book of the Dead chapter 15','University page and translation rights apply','Academic digital presentation of transliteration, translation and genre context','Store locators and independent summaries; do not bulk reproduce translation',0,'Egyptian transliteration with English translation','URL_SYNTAX_VALID','Explains that Chapter 15 is a modern grouping of varied sun hymns and presents Assmann Standard Hymn C-prime addressing Ra in rising as Atum Horakhty.'),
('source.iran.susa_darius.achemenet','Susa: the Statue of Darius','SCHOLARLY_PROJECT',3,'Achemenet / Musée du Louvre research network',NULL,'lang.en',NULL,'2026-08-25','https://www.achemenet.com/en/visit/?/susa/the-statue-of-darius/6=','Susa statue of Darius','Project website rights apply; metadata and independent summary only','Scholarly Achaemenid object and inscription presentation','No images packaged; retain object and inscription locators',0,'English scholarly project presentation','URL_SYNTAX_VALID','Scholarly object presentation records the Egyptian-style statue, Susa context and inscriptions in hieroglyphs and the three cuneiform languages of the empire.'),
('source.egypt.pakeshi_stela.met.90_6_30','Stela of the God''s-Father of Amun Pakeshi','MUSEUM_OBJECT',3,'The Metropolitan Museum of Art',NULL,'lang.en','ca. 721-525 BCE','2026-08-25','https://www.metmuseum.org/art/collection/search/550789','90.6.30','Object data and public-domain media follow The Met Open Access terms','Official museum object catalogue','Metadata, locator and independent summary; no image packaged',0,'English museum catalogue','URL_SYNTAX_VALID','Curatorial context distinguishes Ra-Horakhty and Atum as rising and setting solar focal gods connected with continued life; the object itself depicts Osiris and the Four Sons of Horus.' );

INSERT OR IGNORE INTO entities(
 id,canonical_name,name_zh,original_name,transliteration,primary_type,
 primary_civilization_id,primary_region_id,historical_period,description,
 research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('deity.egyptian.atum_ra','Atum-Ra','阿图姆-拉','jtmw-rꜥ','Atum-Ra','DEITY','civ.egyptian','region.northeast_africa','Persian-period witness in the current dossier; wider chronology remains open','阿图姆与拉的复合神名档案；当前明确证据来自大流士苏萨雕像的埃及语境学术研究。 / Composite Atum-Ra dossier currently anchored to the Egyptian context of the Darius statue at Susa.','PARTIAL','UNVERIFIED',1,'{"entity_model":"composite expression; components remain independent","name_order":"Atum-Ra in current witness"}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('deity.egyptian.atum_horakhty','Atum-Horakhty','阿图姆-哈拉赫提','jtmw-ḥr-ꜣḫty','Atum-Horakhty','DEITY','civ.egyptian','region.northeast_africa','New Kingdom sun-hymn tradition represented by a scholarly digital edition','《亡灵书》第15章所收太阳赞歌见证中的复合称呼；与阿图姆-拉分开保存。 / Composite address in a Chapter 15 sun-hymn witness, stored separately from Atum-Ra.','PARTIAL','UNVERIFIED',1,'{"entity_model":"text-witness composite address","dedup_rule":"not merged with Atum-Ra"}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('text.egypt.book_dead_chapter15','Book of the Dead Chapter 15','《亡灵书》第15章太阳赞歌组',NULL,NULL,'TEXT','civ.egyptian','region.northeast_africa','New Kingdom and later witnesses; modern chapter numbering','现代编目下的一组太阳赞歌，而非单一固定文本；不同纸草和墓室见证可保存不同版本。 / Modern chapter grouping for varied sun hymns rather than one fixed composition.','PARTIAL','UNVERIFIED',1,'{"witness_model":"modern chapter grouping with multiple ancient variants"}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('text.egypt.sun_hymn_standard_c_prime','Sun Hymn: Assmann Standard Hymn C-prime','太阳赞歌：Assmann 标准赞歌 C′',NULL,'i.nD Hr.k ra m wbn.k itm Hr-Axty','TEXT','civ.egyptian','region.northeast_africa','New Kingdom sun-hymn tradition','UCL 数字版所列太阳赞歌定位实体，用于保存对拉与阿图姆-哈拉赫提的同一段见证。 / Section-level witness entity for the hymn addressing Ra in rising as Atum-Horakhty.','PARTIAL','UNVERIFIED',1,'{"locator":"UCL Book of the Dead 15 lines 15-40","not_a_whole_book":true}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('historical.achaemenid.darius_i','Darius I','大流士一世','Dārayavauš','Darius I','HISTORICAL_FIGURE','civ.persian','region.west_asia','Achaemenid king, 522-486 BCE','阿契美尼德国王；本批只建立苏萨雕像与埃及神学语境的有来源连接。 / Achaemenid king, here limited to the sourced Susa-statue and Egyptian-theological context.','PARTIAL','UNVERIFIED',1,'{"reality_status":"HISTORICAL_PERSON"}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('museum.iran.darius_susa_statue','Egyptian Statue of Darius I from Susa','苏萨出土大流士一世埃及式雕像',NULL,NULL,'MUSEUM_OBJECT','civ.persian','region.west_asia','Achaemenid / Egyptian Dynasty 27, reign of Darius I','在埃及制作、后于苏萨发现的多语铭文雕像；埃及神学与阿契美尼德王权层分别记录。 / Egyptian-made multilingual statue found at Susa; Egyptian theological and Achaemenid royal layers remain distinct.','PARTIAL','UNVERIFIED',1,'{"reality_status":"ARCHAEOLOGICAL_OBJECT","cross_civilization_context":["Egyptian","Achaemenid"]}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('concept.egyptian.rising_setting_solar_forms','Rising and setting solar forms','太阳升起与落下形态',NULL,NULL,'CONCEPT','civ.egyptian','region.northeast_africa','Diachronic funerary and hymn contexts','用于比较太阳升起与落下的神祇表达，不把不同神名强制等同。 / Comparison concept for rising and setting solar expressions without forcing deity identities.','PARTIAL','UNVERIFIED',1,'{"comparison_only":true,"no_identity_inference":true}','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.12.0 Ra-Atum witness-layer checkpoint' FROM entities WHERE created_at='2026-08-25T00:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) VALUES
('deity.egyptian.atum_ra','civ.egyptian','ORIGIN','SUPPORTED','Egyptian composite divine expression'),
('deity.egyptian.atum_horakhty','civ.egyptian','ORIGIN','SUPPORTED','Egyptian textual divine expression'),
('text.egypt.book_dead_chapter15','civ.egyptian','ORIGIN','SUPPORTED','Egyptian funerary-text tradition'),
('text.egypt.sun_hymn_standard_c_prime','civ.egyptian','ORIGIN','SUPPORTED','Egyptian sun-hymn tradition'),
('historical.achaemenid.darius_i','civ.persian','ORIGIN','SUPPORTED','Achaemenid historical ruler'),
('museum.iran.darius_susa_statue','civ.persian','FIND_CONTEXT','SUPPORTED','Found at Susa in an Achaemenid palace context'),
('museum.iran.darius_susa_statue','civ.egyptian','CREATION_CONTEXT','SUPPORTED','Egyptian workmanship and hieroglyphic theological program'),
('concept.egyptian.rising_setting_solar_forms','civ.egyptian','ORIGIN','SUPPORTED','Egyptian comparison concept');

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0120.atum_ra.en','deity.egyptian.atum_ra','Atum-Ra','atum ra','lang.en','Latin','PREFERRED',1,'source.egypt.late_period_temples.uee2026','Name order used by UEE v2'),
('name.v0120.atum_ra.egy','deity.egyptian.atum_ra','jtmw-rꜥ','jtmw rꜥ','lang.egy','Hieroglyphic transliteration','ORIGINAL',1,'source.egypt.late_period_temples.uee2026','Conventional transliteration; inscription-level edition remains queued'),
('name.v0120.atum_horakhty.en','deity.egyptian.atum_horakhty','Atum-Horakhty','atum horakhty','lang.en','Latin','PREFERRED',1,'source.egypt.book_dead15.ucl','Digital-edition form'),
('name.v0120.atum_horakhty.egy','deity.egyptian.atum_horakhty','jtmw ḥr-ꜣḫty','jtmw ḥr ꜣḫty','lang.egy','Hieroglyphic transliteration','ORIGINAL',1,'source.egypt.book_dead15.ucl','Normalized from registered transliteration'),
('name.v0120.bd15.en','text.egypt.book_dead_chapter15','Book of the Dead Chapter 15','book dead chapter 15','lang.en','Latin','PREFERRED',1,'source.egypt.book_dead15.ucl','Modern chapter label'),
('name.v0120.hymnc.en','text.egypt.sun_hymn_standard_c_prime','Assmann Standard Hymn C-prime','assmann standard hymn c prime','lang.en','Latin','PREFERRED',1,'source.egypt.book_dead15.ucl','Scholarly hymn designation'),
('name.v0120.darius.en','historical.achaemenid.darius_i','Darius I','darius i','lang.en','Latin','PREFERRED',1,'source.egypt.late_period_temples.uee2026',NULL),
('name.v0120.statue.en','museum.iran.darius_susa_statue','Egyptian Statue of Darius I from Susa','egyptian statue darius i susa','lang.en','Latin','PREFERRED',1,'source.iran.susa_darius.achemenet','Descriptive scholarly title'),
('name.v0120.solarforms.en','concept.egyptian.rising_setting_solar_forms','Rising and setting solar forms','rising setting solar forms','lang.en','Latin','PREFERRED',1,'source.egypt.pakeshi_stela.met.90_6_30','Comparison label, not ancient taxonomy');

INSERT OR IGNORE INTO deity_profiles(entity_id,deity_class,pantheon_or_family,rank_or_status,domains_json,powers_json,limitations_json,appearance_json,symbols_json,cult_summary,final_fate_summary) VALUES
('deity.egyptian.atum_ra','Composite solar deity','Egyptian','Witness-scoped composite','["solar divinity","Heliopolitan protection"]','[]','["Current dossier has one securely located Persian-period scholarly witness","Name order is source-specific"]','{}','[]','Current baseline is anchored to the Darius statue interpretation; earlier textual history remains queued.',NULL),
('deity.egyptian.atum_horakhty','Composite solar address','Egyptian','Text-witness expression','["rising sun","horizon"]','[]','["Current claim is limited to a registered sun-hymn passage","Not automatically identical to Atum-Ra"]','{}','[]','Registered from a UCL digital presentation of a Chapter 15 sun hymn.',NULL);

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.egypt.book_dead_chapter15','Sun-hymn chapter grouping','lang.egy',NULL,'Modern numbering initiated by Lepsius','New Kingdom and later transmitted variants','Multiple papyri and tomb-chapel witnesses','Modern Chapter 15 grouping; variant hymns and vignettes','Multiple repositories',NULL,'Ancient text public domain; modern edition and translation rights apply','A modern chapter grouping for diverse hymns to the sun god.'),
('text.egypt.sun_hymn_standard_c_prime','Sun hymn','lang.egy',NULL,'Assmann scholarly classification','New Kingdom hymn tradition','UCL page presents a transliterated and translated witness','Section-level hymn within the Chapter 15 research entry','UCL Digital Egypt',NULL,'Ancient text public domain; UCL edition and translation rights apply','The registered passage addresses Ra in rising with the composite form Atum-Horakhty.');

INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.iran.darius_susa_statue','National Museum of Iran','Susa Darius statue','Egyptian-style inscribed stone statue','Found at Susa; made in Egypt according to the registered scholarly synthesis','Reign of Darius I, 522-486 BCE','Current holding statement retained as catalogue metadata; inventory-number verification remains queued');

INSERT OR IGNORE INTO claims(
 id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,
 variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,
 knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at
) VALUES
('claim.v0120.atum_ra_component_atum','deity.egyptian.atum_ra','COMPOSITE_EXPRESSION_OF','deity.egyptian.atum',NULL,NULL,'Atum-Ra is registered as a composite expression involving Atum.','egypt.atum_ra.components','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','UEE Persian-period object discussion','Darius I','No redirect or universal identity is created.','2026-08-25T00:00:00Z'),
('claim.v0120.atum_ra_component_ra','deity.egyptian.atum_ra','COMPOSITE_EXPRESSION_OF','deity.egyptian.ra',NULL,NULL,'Atum-Ra is registered as a composite expression involving Ra.','egypt.atum_ra.components','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','UEE Persian-period object discussion','Darius I','No redirect or universal identity is created.','2026-08-25T00:00:00Z'),
('claim.v0120.atum_ra_heliopolis','deity.egyptian.atum_ra','ASSOCIATED_WITH',NULL,'Heliopolis','text','The UEE discussion calls Atum-Ra the great one of Heliopolis in the Darius-statue context.','egypt.atum_ra.cult_context','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Egyptian royal-theological context','Dynasty 27','Literal retained pending a dedicated Heliopolis site/cult dossier.','2026-08-25T00:00:00Z'),
('claim.v0120.darius_protected_atum_ra','historical.achaemenid.darius_i','ASSOCIATED_WITH','deity.egyptian.atum_ra',NULL,NULL,'The UEE synthesis describes Pharaoh Darius as protected by Atum-Ra in the statue''s Egyptian program.','achaemenid.darius.egyptian_theology','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Egyptian statue program','522-486 BCE','This does not replace the separate cuneiform Ahuramazda claim.','2026-08-25T00:00:00Z'),
('claim.v0120.statue_represents_darius','museum.iran.darius_susa_statue','REPRESENTS','historical.achaemenid.darius_i',NULL,NULL,'The scholarly sources identify the statue as representing Darius I.','susa.darius.object_identity','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Susa statue','522-486 BCE',NULL,'2026-08-25T00:00:00Z'),
('claim.v0120.statue_made_egypt','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'made in Egypt by Egyptian workmanship','text','The UEE synthesis states that the Susa statue was made in Egypt for Darius.','susa.darius.creation','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Object manufacture','522-486 BCE',NULL,'2026-08-25T00:00:00Z'),
('claim.v0120.statue_found_susa','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'found in the palace at Susa','text','The registered scholarly sources locate the statue''s find context at Susa.','susa.darius.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Archaeological find context','Modern excavation','Literal retained until a dedicated palace-gate subsite is registered.','2026-08-25T00:00:00Z'),
('claim.v0120.statue_multilingual','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'hieroglyphic, Old Persian, Elamite and Akkadian inscriptions','text','The statue bears hieroglyphic and three-language cuneiform inscription programs.','susa.darius.inscriptions','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Multilingual inscription program','Darius I','Each inscription edition remains a future independent text witness.','2026-08-25T00:00:00Z'),
('claim.v0120.statue_atum_ra','museum.iran.darius_susa_statue','ASSOCIATED_WITH','deity.egyptian.atum_ra',NULL,NULL,'The Egyptian theological interpretation of the statue associates Darius with Atum-Ra.','susa.darius.egyptian_theology','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Egyptian statue program','Dynasty 27','Kept separate from cuneiform Ahuramazda ancestry/protection language.','2026-08-25T00:00:00Z'),
('claim.v0120.atum_horakhty_component_atum','deity.egyptian.atum_horakhty','COMPOSITE_EXPRESSION_OF','deity.egyptian.atum',NULL,NULL,'The registered hymn address combines Atum with Horakhty.','egypt.atum_horakhty.components','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Book of the Dead Chapter 15 sun hymn','New Kingdom hymn tradition','Limited to the registered passage.','2026-08-25T00:00:00Z'),
('claim.v0120.atum_horakhty_component_horakhty','deity.egyptian.atum_horakhty','COMPOSITE_EXPRESSION_OF','deity.egyptian.ra_horakhty',NULL,NULL,'The registered hymn address combines Atum with the Horakhty expression represented by the existing Ra-Horakhty dossier.','egypt.atum_horakhty.components','SUPPORTED',0.94,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Book of the Dead Chapter 15 sun hymn','New Kingdom hymn tradition','The database mapping is explicit and remains witness-scoped.','2026-08-25T00:00:00Z'),
('claim.v0120.hymn_mentions_atum_horakhty','text.egypt.sun_hymn_standard_c_prime','MENTIONED_IN','deity.egyptian.atum_horakhty',NULL,NULL,'The hymn passage addresses the rising solar deity as Atum-Horakhty.','egypt.bd15.hymn_entities','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','UCL transliteration and translation','Lines 15-28 on page','Predicate direction reflects entity mention projection used by the schema.','2026-08-25T00:00:00Z'),
('claim.v0120.hymn_mentions_ra','text.egypt.sun_hymn_standard_c_prime','MENTIONED_IN','deity.egyptian.ra',NULL,NULL,'The same hymn passage directly addresses Ra in his rising.','egypt.bd15.hymn_entities','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','UCL transliteration and translation','Lines 15-28 on page',NULL,'2026-08-25T00:00:00Z'),
('claim.v0120.hymn_part_chapter15','text.egypt.sun_hymn_standard_c_prime','PART_OF','text.egypt.book_dead_chapter15',NULL,NULL,'UCL presents Standard Hymn C-prime within its Book of the Dead Chapter 15 research page.','egypt.bd15.structure','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Modern scholarly organization','Current digital edition','Structural relation, not an assertion that every manuscript contains it.','2026-08-25T00:00:00Z'),
('claim.v0120.chapter15_part_book','text.egypt.book_dead_chapter15','PART_OF','text.egypt.book_dead',NULL,NULL,'Chapter 15 is a modern numbered grouping within the Book of the Dead research corpus.','egypt.bd15.structure','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Modern scholarly organization','Modern numbering since Lepsius','Does not imply one fixed ancient book sequence.','2026-08-25T00:00:00Z'),
('claim.v0120.chapter15_variants','text.egypt.book_dead_chapter15','ASSOCIATED_WITH',NULL,'multiple different sun hymns across papyri and tomb-chapel witnesses','text','UCL cautions that Chapter 15 encompasses numerous different hymns and was extended as a modern label.','egypt.bd15.variants','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Digital-edition context','New Kingdom through later witnesses','Prevents a false single-text model.','2026-08-25T00:00:00Z'),
('claim.v0120.solarforms_atum','concept.egyptian.rising_setting_solar_forms','ASSOCIATED_WITH','deity.egyptian.atum',NULL,NULL,'The Met curatorial context presents Atum as a favored setting-sun focal deity connected with continued life.','egypt.solar_forms.context','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Funerary stela curatorial context','ca. 721-525 BCE','Contextual claim; the Pakeshi stela itself does not depict Atum.','2026-08-25T00:00:00Z'),
('claim.v0120.solarforms_ra_horakhty','concept.egyptian.rising_setting_solar_forms','ASSOCIATED_WITH','deity.egyptian.ra_horakhty',NULL,NULL,'The Met curatorial context presents Ra-Horakhty as a favored rising-sun focal deity connected with continued life.','egypt.solar_forms.context','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Funerary stela curatorial context','ca. 721-525 BCE','Contextual claim; the Pakeshi stela itself does not depict Ra-Horakhty.','2026-08-25T00:00:00Z'),
('claim.v0120.pakeshi_non_depiction_guard','concept.egyptian.rising_setting_solar_forms','ASSOCIATED_WITH',NULL,'Pakeshi stela 90.6.30 depicts Osiris and the Four Sons of Horus, not Atum or Ra-Horakhty','text','The object description separates its general solar curatorial context from the figures actually depicted on the stela.','egypt.solar_forms.evidence_limit','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Met object description','Object 90.6.30','Explicit guard against converting contextual commentary into a depiction edge.','2026-08-25T00:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(id,7),id,
 CASE WHEN id LIKE 'claim.v0120.atum_ra_%' OR id='claim.v0120.darius_protected_atum_ra' OR id IN ('claim.v0120.statue_made_egypt','claim.v0120.statue_atum_ra') THEN 'source.egypt.late_period_temples.uee2026'
      WHEN id LIKE 'claim.v0120.hymn_%' OR id LIKE 'claim.v0120.chapter15_%' OR id LIKE 'claim.v0120.atum_horakhty_%' THEN 'source.egypt.book_dead15.ucl'
      WHEN id IN ('claim.v0120.statue_represents_darius','claim.v0120.statue_found_susa','claim.v0120.statue_multilingual') THEN 'source.iran.susa_darius.achemenet'
      ELSE 'source.egypt.pakeshi_stela.met.90_6_30' END,
 CASE WHEN id LIKE 'claim.v0120.atum_ra_%' OR id='claim.v0120.darius_protected_atum_ra' OR id IN ('claim.v0120.statue_made_egypt','claim.v0120.statue_atum_ra') THEN 'UEE Late Period Temples v2, page 16'
      WHEN id LIKE 'claim.v0120.hymn_%' OR id LIKE 'claim.v0120.atum_horakhty_%' THEN 'UCL Book of the Dead 15, transliteration/translation lines 15-40'
      WHEN id LIKE 'claim.v0120.chapter15_%' THEN 'UCL Book of the Dead 15, introductory notes'
      WHEN id LIKE 'claim.v0120.statue_%' THEN 'Achemenet Susa statue presentation'
      ELSE 'Met object 90.6.30 catalogue context and object description' END,
 CASE WHEN id LIKE 'claim.v0120.solarforms_%' OR id='claim.v0120.pakeshi_non_depiction_guard' THEN '90.6.30' ELSE NULL END,
 CASE WHEN id LIKE 'claim.v0120.hymn_%' OR id LIKE 'claim.v0120.chapter15_%' OR id LIKE 'claim.v0120.atum_horakhty_%' THEN 'ANCIENT_TEXT'
      WHEN id LIKE 'claim.v0120.statue_%' OR id LIKE 'claim.v0120.solarforms_%' OR id='claim.v0120.pakeshi_non_depiction_guard' THEN 'MUSEUM_OBJECT'
      ELSE 'MODERN_SCHOLARSHIP' END,
 'SUPPORTS',confidence,'Independent summary; exact page or object locator retained.'
FROM claims WHERE id LIKE 'claim.v0120.%';

INSERT OR IGNORE INTO identity_candidates(id,entity_a_id,entity_b_id,assessment,confidence,source_id,notes) VALUES
('identity.v0120.atum_ra_atum','deity.egyptian.atum_ra','deity.egyptian.atum','IDENTIFIED_IN_SOURCE',0.98,'source.egypt.late_period_temples.uee2026','Retain both entities and component edge; no redirect.'),
('identity.v0120.atum_ra_ra','deity.egyptian.atum_ra','deity.egyptian.ra','IDENTIFIED_IN_SOURCE',0.98,'source.egypt.late_period_temples.uee2026','Retain both entities and component edge; no redirect.'),
('identity.v0120.atum_horakhty_atum','deity.egyptian.atum_horakhty','deity.egyptian.atum','IDENTIFIED_IN_SOURCE',0.98,'source.egypt.book_dead15.ucl','Witness-scoped composite address; no redirect.'),
('identity.v0120.atum_ra_vs_atum_horakhty','deity.egyptian.atum_ra','deity.egyptian.atum_horakhty','EXPLICITLY_DISTINCT',0.99,'source.egypt.book_dead15.ucl','Different registered names and witnesses; comparison is allowed but no merge is supported.');

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0120.atum_composite_name_scope','deity.egyptian.atum','egypt.atum.composite_name_scope','claim.v0120.atum_ra_component_atum','claim.v0120.atum_horakhty_component_atum','WITNESS_SCOPE','OPEN','Atum-Ra appears in the Persian-period Darius-statue synthesis while Atum-Horakhty appears in a sun-hymn witness; shared Atum does not establish a single interchangeable name.','Keep separate composite entities and expand dated primary witnesses before considering any narrower identity claim.');

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,
 next_action='Add Pyramid and Coffin Text locators, inscription edition for the Darius statue, and further dated Atum-Ra/Atum-Horakhty witnesses',
 updated_at='2026-08-25T07:00:00Z' WHERE id='queue.v0110.egypt.ra_atum_composite';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,
 next_action='Expand Ra, Atum, Khepri and Horakhty forms through Pyramid/Coffin Texts and dated material witnesses without forcing a triad',
 updated_at='2026-08-25T07:00:00Z' WHERE id='queue.v070.egypt.heliopolis_solar_forms';
INSERT OR IGNORE INTO queue_status_history(id,queue_id,old_status,new_status,changed_at,reason) VALUES
('queuehist.v0120.ra_atum','queue.v0110.egypt.ra_atum_composite','SOURCE_FOUND','PARTIAL','2026-08-25T07:00:00Z','Added Atum-Ra, Atum-Horakhty, Chapter 15 hymn and Susa statue witness layers.'),
('queuehist.v0120.heliopolis','queue.v070.egypt.heliopolis_solar_forms','SOURCE_FOUND','PARTIAL','2026-08-25T07:00:00Z','Added Heliopolitan Atum-Ra context and a distinct Atum-Horakhty sun-hymn witness; older textual chronology remains open.');

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0120.egypt.darius_statue_inscriptions','Darius Susa statue Egyptian and cuneiform inscription editions','darius susa statue egyptian cuneiform inscription editions','INSCRIPTION','civ.egyptian','museum.iran.darius_susa_statue','claim.v0120.statue_multilingual','source.iran.susa_darius.achemenet','The multilingual object needs each inscription registered as an independent text witness.',99,'SOURCE_FOUND',0,'Add edition identifiers, language, line locators and translation provenance for each inscription','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('queue.v0120.egypt.atum_ra_early_witnesses','Atum-Ra primary witnesses before Dynasty 27','atum ra primary witnesses before dynasty 27','DEITY','civ.egyptian','deity.egyptian.atum_ra','claim.v0120.atum_ra_component_atum','source.egypt.late_period_temples.uee2026','The current composite baseline is secure but late and cannot establish first attestation.',99,'DISCOVERED',0,'Search Pyramid/Coffin Texts, temple inscriptions and dated objects; record exact name order','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('queue.v0120.egypt.bd15_witnesses','Book of the Dead Chapter 15 manuscript witness registry','book dead chapter 15 manuscript witness registry','MANUSCRIPT','civ.egyptian','text.egypt.book_dead_chapter15','claim.v0120.chapter15_variants','source.egypt.book_dead15.ucl','UCL explicitly warns that many different hymns occupy the modern chapter grouping.',98,'SOURCE_FOUND',0,'Register each papyrus/tomb witness, repository, date, hymn version and image/text rights separately','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('queue.v0120.egypt.atum_horakhty_variants','Atum-Horakhty spelling and hymn variants','atum horakhty spelling hymn variants','DEITY','civ.egyptian','deity.egyptian.atum_horakhty','claim.v0120.hymn_mentions_atum_horakhty','source.egypt.book_dead15.ucl','One digital hymn witness is insufficient for a diachronic identity history.',98,'DISCOVERED',0,'Add manuscript-specific spellings, translations and related horizon forms without merger','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('queue.v0120.iran.darius_statue_provenance','Darius Susa statue excavation, transfer and museum inventory','darius susa statue excavation transfer museum inventory','MUSEUM_OBJECT','civ.persian','museum.iran.darius_susa_statue','claim.v0120.statue_found_susa','source.iran.susa_darius.achemenet','Object history requires excavation publication, exact findspot and official current inventory.',98,'SOURCE_FOUND',0,'Register excavation report, palace gate subsite, object dimensions, inventory and official custody source','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z'),
('queue.v0120.egypt.solar_rising_setting_corpus','Rising and setting solar deity corpus by witness','rising setting solar deity corpus witness','CONCEPT','civ.egyptian','concept.egyptian.rising_setting_solar_forms','claim.v0120.solarforms_atum','source.egypt.pakeshi_stela.met.90_6_30','Museum context opens a comparative corpus but cannot define a universal taxonomy.',97,'DISCOVERED',0,'Add text- and object-specific claims; separate actual depictions from curatorial context','2026-08-25T00:00:00Z','2026-08-25T00:00:00Z');
INSERT OR IGNORE INTO queue_discoveries(id,queue_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,discovered_at)
SELECT 'discovery.'||substr(id,7),id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,'2026-08-25T00:00:00Z' FROM collection_queue WHERE id LIKE 'queue.v0120.%';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260825.v0120_ra_atum_witness_layers','2026-08-25T00:00:00Z','2026-08-25T07:00:00Z','Atum-Ra and Atum-Horakhty composite expressions, Chapter 15 sun hymn, Darius Susa statue and rising/setting solar comparison','Start from priority-99 permanent queue; use university digital text, peer-reviewed Egyptology, scholarly object project and official museum catalogue; separate text, object, interpretation and cross-civilization layers','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Older composite witnesses, manuscript variants, inscription editions, provenance and museum inventory remain queued.');
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260825.v0120_ra_atum_witness_layers','SOURCE',id,'REGISTER','AUTHORITY_AND_LOCATOR_RETAINED' FROM sources WHERE accessed_date='2026-08-25';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260825.v0120_ra_atum_witness_layers','CLAIM',id,'REGISTER','SOURCE_LOCATED' FROM claims WHERE id LIKE 'claim.v0120.%';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260825.v0120_ra_atum_witness_layers','ENTITY',id,'CREATE','WITNESS_LAYER_REGISTERED' FROM entities WHERE created_at='2026-08-25T00:00:00Z';

UPDATE entities SET evidence_status='SOURCE_BACKED',updated_at='2026-08-25T07:00:00Z'
WHERE id IN (SELECT subject_id FROM claims WHERE id LIKE 'claim.v0120.%')
AND NOT EXISTS (SELECT 1 FROM claims c WHERE c.subject_id=entities.id AND NOT EXISTS (SELECT 1 FROM evidence e WHERE e.claim_id=c.id));
UPDATE entities SET evidence_status='PARTIAL',updated_at='2026-08-25T07:00:00Z'
WHERE evidence_status<>'SOURCE_BACKED' AND id IN (SELECT object_entity_id FROM claims WHERE id LIKE 'claim.v0120.%' AND object_entity_id IS NOT NULL);
UPDATE civilizations SET research_status='COLLECTING',evidence_status='PARTIAL' WHERE id IN ('civ.egyptian','civ.persian');
UPDATE project_metadata SET value='0.12.0-ra-atum-witness-layers-20260825',updated_at='2026-08-25T07:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='19',updated_at='2026-08-25T07:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-25T07:00:00Z',updated_at='2026-08-25T07:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.12.0',19,'0.12.0-ra-atum-witness-layers-20260825',NULL,'2026-08-25T07:00:00Z',NULL,'Ra-Atum witness-layer checkpoint: distinct Atum-Ra and Atum-Horakhty composites, Chapter 15 sun-hymn structure, Darius Susa statue cross-civilization context, rising/setting comparison guardrails and six permanent follow-up branches.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES
(19,'20260825_v0120_ra_atum_witness_layers','2026-08-25T07:00:00Z');

COMMIT;
