BEGIN IMMEDIATE;

-- v0.13.0 resolves the highest-priority source-found branch opened in v0.12.
-- The trilingual cuneiform inscription DSab, the five hieroglyphic texts and
-- the subject-peoples list remain distinct witnesses on one archaeological object.

INSERT OR IGNORE INTO languages(id,canonical_name,name_zh,iso_639_3,script_name,historical_stage,notes) VALUES
('lang.peo','Old Persian','古波斯语','peo','Old Persian cuneiform','Achaemenid','Distinct from Middle Persian lang.pal.'),
('lang.elx','Elamite','埃兰语','elx','Elamite cuneiform','Achaemenid administrative/royal inscription stage','Language of one DSab version; not merged with Akkadian.');

INSERT OR IGNORE INTO sources(
 id,title,source_type,evidence_tier,institution,author_or_editor,language_id,
 publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,
 access_or_reuse_restrictions,community_permission_required,translation_status,
 verification_status,notes
) VALUES
('source.persia.dsab.vallat1974','La triple inscription cunéiforme de la statue de Darius Ier (DSab)','SCHOLARLY_EDITION',2,'Revue d’assyriologie et d’archéologie orientale / JSTOR','François Vallat','lang.en','1974','2026-08-26','https://www.jstor.org/stable/23282203','RA 68.2, pp. 157-166; JSTOR 23282203','Article copyright applies; bibliography, locators and independent summaries only','Published edition of the DSab trilingual cuneiform inscription','Do not reproduce the modern edition or translation in bulk',0,'French scholarly edition; ancient texts in Old Persian, Elamite and Akkadian','URL_SYNTAX_VALID','Canonical bibliographic anchor for DSab; exact line-level collation remains open where the accessible record does not expose the full edition.'),
('source.egypt.darius_hieroglyphs.yoyotte1973','Les inscriptions hiéroglyphiques égyptiennes de la statue de Darius à Suse','SCHOLARLY_EDITION',2,'Académie des Inscriptions et Belles-Lettres / Persée','Jean Yoyotte','lang.en','1973','2026-08-26','https://www.persee.fr/doc/crai_0065-0536_1973_num_117_2_12879','CRAI 117-2, pp. 256-266','Article copyright and Persée terms apply; metadata, locators and independent summaries only','Preliminary scholarly publication of the Egyptian inscription program','Do not reproduce the article or figures in bulk',0,'French article; Egyptian hieroglyphic texts discussed','URL_SYNTAX_VALID','Primary scholarly anchor for the Egyptian-language program and its royal-theological interpretation.'),
('source.iranica.susa_achaemenid','Susa iii. The Achaemenid Period','SCHOLARLY_REFERENCE',2,'Encyclopaedia Iranica','Rémy Boucharlat','lang.en','2009-07-20','2026-08-26','https://www.iranicaonline.org/articles/susa-iii-the-achaemenid-period/','SUSA iii','Encyclopaedia Iranica rights apply; metadata and independent summaries only','Scholarly synthesis of the archaeological and inscription context','No bulk reproduction',0,'English scholarly reference','URL_SYNTAX_VALID','Identifies DSab, the Egyptian origin, Heliopolis destination, Susa transfer, base symbolism and labelled subject peoples.'),
('source.iranica.epigraphy_old_persian','Epigraphy i. Old Persian and Middle Iranian epigraphy','SCHOLARLY_REFERENCE',2,'Encyclopaedia Iranica',NULL,'lang.en',NULL,'2026-08-26','https://www.iranicaonline.org/articles/epigraphy-i/','EPIGRAPHY i','Encyclopaedia Iranica rights apply; metadata and independent summaries only','Scholarly epigraphic overview','No bulk reproduction',0,'English scholarly reference','URL_SYNTAX_VALID','States that DSab is trilingual and accompanied by five hieroglyphic texts, including a province list.'),
('source.persia.dsab.achemenet','Susa: Central Part of the Statue','SCHOLARLY_PROJECT',3,'Achemenet / Musée du Louvre research network','Pierre Briant project','lang.en',NULL,'2026-08-26','https://www.achemenet.com/en/visit/?/susa/the-statue-of-darius/6=','DSab object presentation','Project website rights apply; metadata and independent summaries only','Scholarly object presentation with inscription placement and Vallat translation attribution','No images or extended modern translation packaged',0,'English presentation; ancient cuneiform languages identified','URL_SYNTAX_VALID','Confirms several inscriptions, the three imperial cuneiform languages and the DSab opening on the pleated robe.');

INSERT OR IGNORE INTO entities(
 id,canonical_name,name_zh,original_name,transliteration,primary_type,
 primary_civilization_id,primary_region_id,historical_period,description,
 research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('text.persia.dsab','DSab Trilingual Inscription','DSab 三语楔形文字铭文',NULL,'DSab','TEXT','civ.persian','region.west_asia','Reign of Darius I, 522-486 BCE','苏萨大流士雕像上的古波斯语、埃兰语与阿卡德语三语铭文；三个语言版本作为同一铭文组的独立见证。 / Trilingual cuneiform inscription on the Darius statue, with Old Persian, Elamite and Akkadian witnesses.','PARTIAL','SOURCE_BACKED',1,'{"inscription_code":"DSab","witness_model":"parallel language versions","object_id":"museum.iran.darius_susa_statue"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('text.persia.dsab.old_persian','DSab Old Persian Version','DSab 古波斯语版本',NULL,NULL,'TEXT','civ.persian','region.west_asia','Reign of Darius I, 522-486 BCE','DSab 的古波斯语版本，单独保存语言、载体与版本证据。 / Old Persian version of DSab, retained as a distinct textual witness.','PARTIAL','SOURCE_BACKED',1,'{"parent_inscription":"text.persia.dsab","language":"lang.peo"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('text.persia.dsab.elamite','DSab Elamite Version','DSab 埃兰语版本',NULL,NULL,'TEXT','civ.persian','region.west_asia','Reign of Darius I, 522-486 BCE','DSab 的埃兰语版本，不与古波斯语或阿卡德语文本合并。 / Elamite version of DSab, retained independently.','PARTIAL','SOURCE_BACKED',1,'{"parent_inscription":"text.persia.dsab","language":"lang.elx"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('text.persia.dsab.akkadian','DSab Akkadian Version','DSab 阿卡德语版本',NULL,NULL,'TEXT','civ.babylonian','region.west_asia','Reign of Darius I, 522-486 BCE','DSab 的阿卡德语版本，作为阿契美尼德王室多语铭文的一层。 / Akkadian version of DSab in the Achaemenid multilingual program.','PARTIAL','SOURCE_BACKED',1,'{"parent_inscription":"text.persia.dsab","language":"lang.akk"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('text.egypt.darius_susa_hieroglyphic_program','Darius Susa Statue Hieroglyphic Program','苏萨大流士雕像象形文字铭文组',NULL,NULL,'TEXT','civ.egyptian','region.northeast_africa','Egyptian Dynasty 27 / reign of Darius I','雕像上的五组埃及象形文字文本总档；与 DSab 三语楔形文字铭文分开。 / Corpus record for five hieroglyphic texts on the statue, separate from DSab.','PARTIAL','SOURCE_BACKED',1,'{"witness_count":5,"language":"lang.egy","object_id":"museum.iran.darius_susa_statue"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('text.egypt.darius_susa_hieroglyphic_province_list','Darius Statue Hieroglyphic Subject-Peoples List','大流士雕像象形文字属地名单',NULL,NULL,'TEXT','civ.egyptian','region.northeast_africa','Egyptian Dynasty 27 / reign of Darius I','雕像基座两侧人物与椭圆名框组成的属地名单；当前基线登记二十四个形象，不把其直接等同于现代国家。 / Base list of twenty-four labelled subject figures; ancient labels are not automatically mapped to modern states.','PARTIAL','SOURCE_BACKED',1,'{"hieroglyphic_text_number":5,"figure_count":24,"mapping_guard":"ancient ethnonyms are not modern-state identities"}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('concept.persia.darius_statue_subject_peoples','Darius Statue Subject Peoples','大流士雕像属民表现体系',NULL,NULL,'CONCEPT','civ.persian','region.west_asia','Reign of Darius I, 522-486 BCE','用于连接基座人物、象形文字名框与帝国属地表达的比较实体，不宣称名单等于固定民族或现代疆界。 / Comparison concept linking base figures, cartouches and imperial subject representation without modern ethnic equivalence.','PARTIAL','SOURCE_BACKED',1,'{"comparison_only":true,"no_modern_ethnic_equivalence":true}','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.13.0 Darius statue inscription checkpoint' FROM entities WHERE created_at='2026-08-26T00:00:00Z';

INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) VALUES
('text.persia.dsab','civ.persian','ROYAL_INSCRIPTION','SUPPORTED','Achaemenid royal inscription commissioned by Darius I'),
('text.persia.dsab.old_persian','civ.persian','LANGUAGE_WITNESS','SUPPORTED','Old Persian version'),
('text.persia.dsab.elamite','civ.persian','IMPERIAL_LANGUAGE_WITNESS','SUPPORTED','Elamite version in Achaemenid royal context'),
('text.persia.dsab.akkadian','civ.persian','IMPERIAL_LANGUAGE_WITNESS','SUPPORTED','Akkadian version in Achaemenid royal context'),
('text.persia.dsab.akkadian','civ.babylonian','LANGUAGE_TRADITION','SUPPORTED','Akkadian textual tradition; not an origin claim for the object'),
('text.egypt.darius_susa_hieroglyphic_program','civ.egyptian','CREATION_CONTEXT','SUPPORTED','Egyptian language and sculptural program'),
('text.egypt.darius_susa_hieroglyphic_province_list','civ.egyptian','TEXTUAL_FORM','SUPPORTED','Egyptian hieroglyphic labels and iconographic format'),
('text.egypt.darius_susa_hieroglyphic_province_list','civ.persian','IMPERIAL_SUBJECT','SUPPORTED','Represents Achaemenid imperial subject peoples'),
('concept.persia.darius_statue_subject_peoples','civ.persian','IMPERIAL_CONTEXT','SUPPORTED','Achaemenid subject representation');

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0130.dsab.code','text.persia.dsab','DSab','dsab','lang.en','Latin','CATALOGUE_CODE',1,'source.persia.dsab.vallat1974','Standard Achaemenid inscription siglum'),
('name.v0130.dsab.en','text.persia.dsab','Trilingual Inscription of the Darius Statue','trilingual inscription darius statue','lang.en','Latin','DESCRIPTIVE',0,'source.persia.dsab.vallat1974',NULL),
('name.v0130.dsab.peo.en','text.persia.dsab.old_persian','DSab Old Persian Version','dsab old persian version','lang.en','Latin','DESCRIPTIVE',1,'source.persia.dsab.vallat1974','Language-witness label'),
('name.v0130.dsab.elx.en','text.persia.dsab.elamite','DSab Elamite Version','dsab elamite version','lang.en','Latin','DESCRIPTIVE',1,'source.persia.dsab.vallat1974','Language-witness label'),
('name.v0130.dsab.akk.en','text.persia.dsab.akkadian','DSab Akkadian Version','dsab akkadian version','lang.en','Latin','DESCRIPTIVE',1,'source.persia.dsab.vallat1974','Language-witness label'),
('name.v0130.hieroglyphs.en','text.egypt.darius_susa_hieroglyphic_program','Five Hieroglyphic Texts of the Darius Statue','five hieroglyphic texts darius statue','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.epigraphy_old_persian','Corpus label, not an ancient title'),
('name.v0130.province_list.en','text.egypt.darius_susa_hieroglyphic_province_list','Hieroglyphic Province List','hieroglyphic province list','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.epigraphy_old_persian','Modern descriptive title');
INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0130.subjects.en','concept.persia.darius_statue_subject_peoples','Darius Statue Subject Peoples','darius statue subject peoples','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.susa_achaemenid','Modern comparison label with anti-anachronism guardrail');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.persia.dsab','Royal inscription',NULL,'Darius I royal authority',NULL,'Reign of Darius I','The statue itself','Parallel Old Persian, Elamite and Akkadian versions','National Museum of Iran','Current exact inventory verification remains queued','Ancient text public domain; modern editions/translations protected','Trilingual royal inscription conventionally designated DSab.'),
('text.persia.dsab.old_persian','Royal inscription language witness','lang.peo','Darius I royal authority',NULL,'Reign of Darius I','The statue itself','Old Persian version of DSab','National Museum of Iran',NULL,'Ancient text public domain; modern editions/translations protected','Old Persian language witness of DSab.'),
('text.persia.dsab.elamite','Royal inscription language witness','lang.elx','Darius I royal authority',NULL,'Reign of Darius I','The statue itself','Elamite version of DSab','National Museum of Iran',NULL,'Ancient text public domain; modern editions/translations protected','Elamite language witness of DSab.'),
('text.persia.dsab.akkadian','Royal inscription language witness','lang.akk','Darius I royal authority',NULL,'Reign of Darius I','The statue itself','Akkadian version of DSab','National Museum of Iran',NULL,'Ancient text public domain; modern editions/translations protected','Akkadian language witness of DSab.'),
('text.egypt.darius_susa_hieroglyphic_program','Royal monumental inscription corpus','lang.egy','Darius I royal authority',NULL,'Egyptian Dynasty 27','The statue itself','Five separately located hieroglyphic texts','National Museum of Iran',NULL,'Ancient text public domain; modern editions/translations protected','Five-text Egyptian hieroglyphic program associated with the statue.'),
('text.egypt.darius_susa_hieroglyphic_province_list','Royal monumental list','lang.egy','Darius I royal authority',NULL,'Egyptian Dynasty 27','The statue base','Twenty-four labelled subject figures on two sides of the base','National Museum of Iran',NULL,'Ancient text public domain; modern editions/translations protected','Hieroglyphic labels identify represented subject peoples on the statue base.');

INSERT OR IGNORE INTO claims(
 id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,
 variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,
 knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at
) VALUES
('claim.v0130.dsab_on_statue','text.persia.dsab','DEPICTED_ON','museum.iran.darius_susa_statue',NULL,NULL,'DSab is inscribed on the Darius statue from Susa.','susa.darius.inscription_carrier','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Achaemenid royal inscription','522-486 BCE','The object and text remain separate entities.','2026-08-26T00:00:00Z'),
('claim.v0130.dsab_old_persian_part','text.persia.dsab.old_persian','PART_OF','text.persia.dsab',NULL,NULL,'The Old Persian text is one language witness of DSab.','dsab.language_versions','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','DSab','522-486 BCE',NULL,'2026-08-26T00:00:00Z'),
('claim.v0130.dsab_elamite_part','text.persia.dsab.elamite','PART_OF','text.persia.dsab',NULL,NULL,'The Elamite text is one language witness of DSab.','dsab.language_versions','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','DSab','522-486 BCE',NULL,'2026-08-26T00:00:00Z'),
('claim.v0130.dsab_akkadian_part','text.persia.dsab.akkadian','PART_OF','text.persia.dsab',NULL,NULL,'The Akkadian text is one language witness of DSab.','dsab.language_versions','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','DSab','522-486 BCE',NULL,'2026-08-26T00:00:00Z'),
('claim.v0130.dsab_mentions_ahuramazda','text.persia.dsab','MENTIONS','deity.zoroastrian.ahura_mazda',NULL,NULL,'DSab invokes Ahuramazda and asks for protection of Darius and his work.','dsab.divine_reference','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Achaemenid royal theology','Darius I','Summary only; no extended modern translation stored.','2026-08-26T00:00:00Z'),
('claim.v0130.dsab_made_egypt','text.persia.dsab','ASSOCIATED_WITH',NULL,'Darius ordered the stone statue to be made in Egypt','text','DSab states that Darius ordered the stone statue to be made in Egypt.','dsab.statue_origin_statement','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','DSab','Darius I','Textual statement is distinct from geological provenance analysis.','2026-08-26T00:00:00Z'),
('claim.v0130.dsab_persian_holds_egypt','text.persia.dsab','ASSOCIATED_WITH',NULL,'the Persian holds Egypt','text','DSab frames the statue as a future-visible statement of Persian rule over Egypt.','dsab.imperial_statement','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','DSab','Darius I','Paraphrase of the registered translation; not a modern endorsement.','2026-08-26T00:00:00Z'),
('claim.v0130.hieroglyphic_program_on_statue','text.egypt.darius_susa_hieroglyphic_program','DEPICTED_ON','museum.iran.darius_susa_statue',NULL,NULL,'Five hieroglyphic texts accompany the cuneiform inscription on the statue.','susa.darius.inscription_carrier','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Egyptian inscription program','Darius I',NULL,'2026-08-26T00:00:00Z'),
('claim.v0130.hieroglyphic_program_distinct_dsab','text.egypt.darius_susa_hieroglyphic_program','ASSOCIATED_WITH','text.persia.dsab',NULL,NULL,'The hieroglyphic program and DSab occur on one object but are distinct textual corpora.','susa.darius.multilingual_layers','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Multilingual statue program','Darius I','No VARIANT_OF or identity edge is created.','2026-08-26T00:00:00Z'),
('claim.v0130.province_list_part_program','text.egypt.darius_susa_hieroglyphic_province_list','PART_OF','text.egypt.darius_susa_hieroglyphic_program',NULL,NULL,'The labelled subject-peoples list is one of the five hieroglyphic texts.','susa.darius.hieroglyphic_structure','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Egyptian inscription program','Darius I',NULL,'2026-08-26T00:00:00Z'),
('claim.v0130.province_list_24','text.egypt.darius_susa_hieroglyphic_province_list','ASSOCIATED_WITH',NULL,'twenty-four labelled subject figures on the two sides of the base','text','The base sides represent twenty-four subject figures, each identified by a hieroglyphic name label.','susa.darius.subject_count','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Statue base','Darius I','Count is for this monument, not a universal Achaemenid province count.','2026-08-26T00:00:00Z'),
('claim.v0130.province_list_represents_subjects','text.egypt.darius_susa_hieroglyphic_province_list','REPRESENTS','concept.persia.darius_statue_subject_peoples',NULL,NULL,'The base list represents subject peoples within the statue’s imperial program.','susa.darius.subject_representation','SUPPORTED',0.97,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Statue base','Darius I','Ancient labels will be registered individually before entity mappings.','2026-08-26T00:00:00Z'),
('claim.v0130.subjects_no_modern_equivalence','concept.persia.darius_statue_subject_peoples','ASSOCIATED_WITH',NULL,'ancient labels and figures must not be automatically equated with modern nations or ethnic identities','text','The project preserves ancient labels before proposing any modern geographic or ethnic mapping.','susa.darius.mapping_guard','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Cross-cultural identity handling','Current project','Explicit anti-anachronism guardrail.','2026-08-26T00:00:00Z'),
('claim.v0130.statue_intended_heliopolis','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'intended for the temple of Heliopolis','text','Encyclopaedia Iranica reports the scholarly reconstruction that the statue was intended for the temple of Heliopolis.','susa.darius.original_destination','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Object itinerary reconstruction','Darius I','Registered as scholarly reconstruction rather than direct inscription wording.','2026-08-26T00:00:00Z'),
('claim.v0130.statue_transfer_xerxes','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'brought to Susa by Xerxes','text','Encyclopaedia Iranica reports that Xerxes brought the statue to Susa.','susa.darius.transfer','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Object itinerary reconstruction','Xerxes I','A dedicated Xerxes and transfer-evidence dossier remains queued.','2026-08-26T00:00:00Z'),
('claim.v0130.statue_wadi_hammamat','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'metamorphic sandstone from Wadi Hammamat','text','The stone type supports an Egyptian provenance and is associated with Wadi Hammamat.','susa.darius.material_provenance','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Material provenance','Modern analysis','Material evidence is kept distinct from DSab’s origin statement.','2026-08-26T00:00:00Z'),
('claim.v0130.statue_base_union_symbol','museum.iran.darius_susa_statue','DEPICTS',NULL,'Egyptian symbol of the union of Upper and Lower Egypt on the front and back of the base','text','The base front and back carry an Egyptian symbol of the union of Upper and Lower Egypt.','susa.darius.base_iconography','SUPPORTED',0.97,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Statue base','Darius I',NULL,'2026-08-26T00:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(id,7),id,
 CASE
  WHEN id LIKE 'claim.v0130.dsab_%' THEN CASE WHEN id IN ('claim.v0130.dsab_made_egypt','claim.v0130.dsab_persian_holds_egypt','claim.v0130.dsab_mentions_ahuramazda') THEN 'source.persia.dsab.achemenet' ELSE 'source.persia.dsab.vallat1974' END
  WHEN id LIKE 'claim.v0130.hieroglyphic_%' OR id LIKE 'claim.v0130.province_list_part_%' THEN 'source.iranica.epigraphy_old_persian'
  WHEN id LIKE 'claim.v0130.province_list_%' THEN 'source.iranica.susa_achaemenid'
  WHEN id='claim.v0130.subjects_no_modern_equivalence' THEN 'source.iranica.susa_achaemenid'
  ELSE 'source.iranica.susa_achaemenid' END,
 CASE
  WHEN id LIKE 'claim.v0130.dsab_%' THEN CASE WHEN id IN ('claim.v0130.dsab_made_egypt','claim.v0130.dsab_persian_holds_egypt','claim.v0130.dsab_mentions_ahuramazda') THEN 'Achemenet central part, DSab presentation and attributed translation' ELSE 'Vallat 1974, RA 68.2, pp. 157-166' END
  WHEN id LIKE 'claim.v0130.hieroglyphic_%' OR id LIKE 'claim.v0130.province_list_part_%' THEN 'Encyclopaedia Iranica, Epigraphy i, DSab paragraph'
  WHEN id LIKE 'claim.v0130.province_list_%' OR id='claim.v0130.subjects_no_modern_equivalence' THEN 'Encyclopaedia Iranica, Susa iii, statue paragraph'
  ELSE 'Encyclopaedia Iranica, Susa iii, statue paragraph' END,
 CASE WHEN id LIKE 'claim.v0130.dsab_%' THEN 'DSab' ELSE NULL END,
 CASE WHEN id LIKE 'claim.v0130.statue_%' OR id LIKE 'claim.v0130.province_list_24' THEN 'ARCHAEOLOGICAL' WHEN id='claim.v0130.subjects_no_modern_equivalence' THEN 'MODERN_SCHOLARSHIP' ELSE 'INSCRIPTION' END,
 'SUPPORTS',confidence,'Independent summary; source and section/page locator retained.'
FROM claims WHERE id LIKE 'claim.v0130.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0130.statue_origin_evidence_layers','museum.iran.darius_susa_statue','susa.darius.creation','claim.v0130.dsab_made_egypt','claim.v0130.statue_wadi_hammamat','EVIDENCE_LAYER','OPEN','The inscription states Egyptian manufacture while material analysis independently supports Egyptian stone provenance; these are converging but different evidence types.','Keep textual assertion and archaeometric interpretation separate.'),
('conflict.v0130.dsab_vs_hieroglyphic_scope','museum.iran.darius_susa_statue','susa.darius.multilingual_layers','claim.v0130.dsab_on_statue','claim.v0130.hieroglyphic_program_on_statue','TEXTUAL_SCOPE','OPEN','DSab and five hieroglyphic texts share one carrier but are not one interchangeable text.','Maintain separate corpus entities, languages and source editions.');

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,last_error=NULL,
 next_action='Expand line-level editions, exact placements and individual hieroglyphic text numbering; keep each language witness distinct',
 updated_at='2026-08-26T07:00:00Z' WHERE id='queue.v0120.egypt.darius_statue_inscriptions';
INSERT OR IGNORE INTO queue_status_history(id,queue_id,old_status,new_status,changed_at,reason) VALUES
('queuehist.v0130.darius_inscriptions','queue.v0120.egypt.darius_statue_inscriptions','SOURCE_FOUND','BASELINE_COMPLETE','2026-08-26T07:00:00Z','Registered DSab, three language witnesses, the five-text hieroglyphic program and its subject-peoples list with scholarly locators.');

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0130.persia.dsab_line_editions','DSab line-by-line Old Persian, Elamite and Akkadian editions','dsab line editions old persian elamite akkadian','INSCRIPTION','civ.persian','text.persia.dsab','claim.v0130.dsab_old_persian_part','source.persia.dsab.vallat1974','The bibliographic baseline identifies parallel witnesses but a rights-safe line-by-line apparatus remains incomplete.',99,'SOURCE_FOUND',0,'Register edition-specific line locators, transliteration rights and variant readings without copying protected translations','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('queue.v0130.egypt.darius_hieroglyphic_texts_1_4','Darius statue hieroglyphic texts 1-4 individual dossiers','darius statue hieroglyphic texts 1 4 dossiers','INSCRIPTION','civ.egyptian','text.egypt.darius_susa_hieroglyphic_program','claim.v0130.hieroglyphic_program_on_statue','source.egypt.darius_hieroglyphs.yoyotte1973','The five-text count is secure, but texts 1-4 need separate locations and exact edition locators.',99,'SOURCE_FOUND',0,'Use Yoyotte editions to register each numbered text, carrier position, transliteration and divine names','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('queue.v0130.egypt.darius_subject_cartouches','Darius statue twenty-four subject cartouches','darius statue twenty four subject cartouches','INSCRIPTION','civ.egyptian','text.egypt.darius_susa_hieroglyphic_province_list','claim.v0130.province_list_24','source.iranica.susa_achaemenid','Each ancient label and figure requires independent identity assessment.',98,'DISCOVERED',0,'Register R/L position, hieroglyphic label, scholarly reading and geographic mapping confidence for all twenty-four','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('queue.v0130.persia.xerxes_statue_transfer','Xerxes and the Darius statue transfer to Susa','xerxes darius statue transfer susa','EVENT','civ.persian','museum.iran.darius_susa_statue','claim.v0130.statue_transfer_xerxes','source.iranica.susa_achaemenid','The reported transfer needs its underlying historical and archaeological argument.',98,'SOURCE_FOUND',0,'Add Xerxes entity if absent, gate context, transfer chronology and source disagreement','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('queue.v0130.egypt.heliopolis_darius_destination','Heliopolis destination of the Darius statue','heliopolis destination darius statue','ARCHAEOLOGICAL_SITE','civ.egyptian','museum.iran.darius_susa_statue','claim.v0130.statue_intended_heliopolis','source.iranica.susa_achaemenid','The intended temple destination is a scholarly reconstruction requiring primary argument and site context.',97,'SOURCE_FOUND',0,'Register Heliopolis site and temple context; separate proposed destination from confirmed findspot','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z'),
('queue.v0130.egypt.wadi_hammamat_provenance','Wadi Hammamat stone provenance of the Darius statue','wadi hammamat stone provenance darius statue','ARCHAEOLOGICAL_SITE','civ.egyptian','museum.iran.darius_susa_statue','claim.v0130.statue_wadi_hammamat','source.iranica.susa_achaemenid','Material source and quarry landscape can connect object, site and archaeometric evidence.',97,'SOURCE_FOUND',0,'Add quarry site, geological study, sampling method and confidence; do not infer workshop location from stone alone','2026-08-26T00:00:00Z','2026-08-26T00:00:00Z');
INSERT OR IGNORE INTO queue_discoveries(id,queue_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,discovered_at)
SELECT 'discovery.'||substr(id,7),id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,'2026-08-26T00:00:00Z' FROM collection_queue WHERE id LIKE 'queue.v0130.%';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260826.v0130_darius_statue_inscriptions','2026-08-26T00:00:00Z','2026-08-26T07:00:00Z','DSab trilingual inscription, five-text Egyptian hieroglyphic program, subject-peoples list and object itinerary evidence layers','Resolve the highest-priority SOURCE_FOUND queue branch using scholarly editions, Encyclopaedia Iranica and Achemenet; preserve language witnesses and evidence layers independently','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Line-by-line editions, texts 1-4, all cartouches, transfer argument, Heliopolis and quarry provenance remain queued.');
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260826.v0130_darius_statue_inscriptions','SOURCE',id,'REGISTER','AUTHORITY_AND_LOCATOR_RETAINED' FROM sources WHERE accessed_date='2026-08-26';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260826.v0130_darius_statue_inscriptions','CLAIM',id,'REGISTER','SOURCE_LOCATED' FROM claims WHERE id LIKE 'claim.v0130.%';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260826.v0130_darius_statue_inscriptions','ENTITY',id,'CREATE','INSCRIPTION_LAYER_REGISTERED' FROM entities WHERE created_at='2026-08-26T00:00:00Z';

UPDATE civilizations SET research_status='COLLECTING',evidence_status='PARTIAL' WHERE id IN ('civ.egyptian','civ.persian','civ.babylonian');
UPDATE project_metadata SET value='0.13.0-darius-statue-inscriptions-20260826',updated_at='2026-08-26T07:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='20',updated_at='2026-08-26T07:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-26T07:00:00Z',updated_at='2026-08-26T07:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.13.0',20,'0.13.0-darius-statue-inscriptions-20260826',NULL,'2026-08-26T07:00:00Z',NULL,'Darius statue inscription checkpoint: DSab and its three language witnesses, five-text hieroglyphic corpus, subject-peoples list, separate textual/material evidence layers and six permanent follow-up branches.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES
(20,'20260826_v0130_darius_statue_inscriptions','2026-08-26T07:00:00Z');

COMMIT;
