BEGIN IMMEDIATE;

-- v0.14.0 extends the Darius statue dossier from inscription layers into a
-- provenance chain. Ancient manufacture, reconstructed royal transfer,
-- archaeological findspot, modern discovery and present custody stay distinct.

INSERT OR IGNORE INTO sources(
 id,title,source_type,evidence_tier,institution,author_or_editor,language_id,
 publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,
 access_or_reuse_restrictions,community_permission_required,translation_status,
 verification_status,notes
) VALUES
('source.iran.susa_darius_statue.achemenet','Susa: The Statue of Darius','SCHOLARLY_PROJECT',3,'Achemenet / Musee du Louvre research network','Pierre Briant project','lang.en',NULL,'2026-08-27','https://www.achemenet.com/en/visit/?/susa/the-statue-of-darius/','Darius statue overview','Project website rights apply; metadata, locators and independent summaries only','Scholarly archaeological presentation produced with museum and excavation partners','Do not package page images or extended text',0,'English project presentation','URL_SYNTAX_VALID','Records the chance discovery on 24 December 1972, preserved height, missing upper part and current display at the National Museum of Iran.'),
('source.iran.susa_darius_foundation.achemenet','Susa: The Statue on its Foundation','SCHOLARLY_PROJECT',3,'Achemenet / Musee du Louvre research network','Pierre Briant project','lang.en',NULL,'2026-08-27','https://www.achemenet.com/en/visit/?/susa/the-statue-of-darius/3=','Darius statue foundation','Project website rights apply; metadata, locators and independent summaries only','Scholarly archaeological object-context presentation','Do not package page images or extended text',0,'English project presentation','URL_SYNTAX_VALID','Describes the statue fixed with lead to two stone slabs set on a larger foundation; construction observation kept separate from itinerary reconstruction.'),
('source.iran.susa_darius_gate.achemenet','Susa: The Darius Gate','OFFICIAL_ARCHAEOLOGICAL_PROJECT',3,'Achemenet / Musee du Louvre / National Museum of Iran research network','Pierre Briant project','lang.en',NULL,'2026-08-27','https://www.achemenet.com/en/visit/?/susa/darius-gate/','Darius Gate, Susa','Project website rights apply; metadata, locators and independent summaries only','Scholarly archaeological-site presentation with institutional partners','Do not package page images or extended text',0,'English project presentation','URL_SYNTAX_VALID','Project-level record for the mud-brick gate and its archaeological context.'),
('source.iran.susa_royal_city.met1992','The Royal City of Susa: Ancient Near Eastern Treasures in the Louvre','MUSEUM_PUBLICATION',3,'The Metropolitan Museum of Art / Musee du Louvre','Prudence O. Harper; Joan Aruz; Francoise Tallon','lang.en','1992','2026-08-27','https://www.metmuseum.org/met-publications/royal-city-of-susa-ancient-near-eastern-treasures-in-the-louvre','ISBN publication, 336 pages','Publication copyright applies; the linked museum record and PDF terms govern reuse','Museum and scholarly synthesis of Susa excavation history, monuments, objects and conservation','Bibliographic data and independent summaries only; no bulk reproduction',0,'English museum publication','URL_SYNTAX_VALID','Authority-level bibliography for the wider Susa excavation setting; not used to invent an exact statue inventory number.');

INSERT OR IGNORE INTO entities(
 id,canonical_name,name_zh,original_name,transliteration,primary_type,
 primary_civilization_id,primary_region_id,historical_period,description,
 research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('historical.achaemenid.xerxes_i','Xerxes I','薛西斯一世','Xsayarsa','Xerxes I','HISTORICAL_FIGURE','civ.persian','region.west_asia','Achaemenid king, 486-465 BCE','阿契美尼德国王；本批仅登记其完成苏萨王宫工程及被学界归因的大流士雕像转运。 / Achaemenid king, limited here to sourced Susa building completion and the attributed statue transfer.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"HISTORICAL_PERSON","identity_guard":"not merged with later namesakes"}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('site.iran.susa','Susa Archaeological Site','苏萨考古遗址','Susa','Susa','ARCHAEOLOGICAL_SITE','civ.persian','region.west_asia','Multi-period settlement; Achaemenid royal residence after ca. 520 BCE','伊朗胡齐斯坦的多时期现实考古遗址；本档案只扩展阿契美尼德王城与雕像发现语境。 / Real multi-period site in Khuzestan, here scoped to the Achaemenid royal city and statue find context.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","period_sensitive":true}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('site.iran.susa_darius_gate','Darius Gate at Susa','苏萨大流士门','Gate of Darius','Darius Gate','ARCHAEOLOGICAL_SITE','civ.persian','region.west_asia','Begun under Darius I; completed under Xerxes I','苏萨王宫的官方入口建筑子档；与整个苏萨遗址及王宫保持独立。 / Monument-level record for the official palace entrance at Susa, distinct from the whole site and palace.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","part_of":"site.iran.susa","construction_phase_guard":true}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('event.persia.darius_statue_transfer_egypt_susa','Reconstructed Transfer of the Darius Statue to Susa','大流士雕像转运苏萨（学术重建）',NULL,NULL,'EVENT','civ.persian','region.west_asia','Attributed to the reign of Xerxes I, after 486 BCE','学术资料重建的历史转运事件；不是现存古代叙事原文，也不把“由薛西斯带到苏萨”升级为无争议事实。 / Scholarly reconstruction of the statue transfer, not an extant ancient narrative and not treated as undisputed fact.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"HISTORICAL_RECONSTRUCTION","route_start":"Egypt/Heliopolis proposed","route_end":"Susa","attribution":"Xerxes I"}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('event.archaeology.darius_statue_discovery_1972','Discovery of the Darius Statue at Susa (1972)','1972年苏萨大流士雕像发现事件',NULL,NULL,'EVENT','civ.persian','region.west_asia','24 December 1972','1972年12月24日在苏萨考古现场偶然发现雕像的现代考古事件；与古代转运事件分开。 / Modern archaeological discovery on 24 December 1972, separate from the ancient transfer reconstruction.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"MODERN_ARCHAEOLOGICAL_EVENT","date":"1972-12-24"}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('institution.iran.national_museum','National Museum of Iran','伊朗国家博物馆',NULL,NULL,'INSTITUTION','civ.persian','region.west_asia','Modern museum institution','当前展示苏萨大流士雕像的现代博物馆机构；未核实的馆藏号不写入。 / Modern institution displaying the Darius statue; no unverified inventory number is asserted.','PARTIAL','SOURCE_BACKED',1,'{"institution_type":"MUSEUM","inventory_guard":"exact number remains unverified"}','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.14.0 Darius statue provenance checkpoint' FROM entities WHERE created_at='2026-08-27T00:00:00Z';

INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) VALUES
('historical.achaemenid.xerxes_i','civ.persian','HISTORICAL_CONTEXT','SUPPORTED','Achaemenid king'),
('site.iran.susa','civ.persian','HISTORICAL_CONTEXT','SUPPORTED','Achaemenid royal residence layer'),
('site.iran.susa_darius_gate','civ.persian','ROYAL_ARCHITECTURE','SUPPORTED','Darius/Xerxes construction phases'),
('event.persia.darius_statue_transfer_egypt_susa','civ.persian','ROYAL_ITINERARY_RECONSTRUCTION','SUPPORTED','Transfer attributed to Xerxes'),
('event.persia.darius_statue_transfer_egypt_susa','civ.egyptian','ORIGIN_CONTEXT','SUPPORTED','Egyptian manufacture and proposed Heliopolis destination'),
('event.archaeology.darius_statue_discovery_1972','civ.persian','ARCHAEOLOGICAL_CONTEXT','SUPPORTED','Modern discovery of Achaemenid object'),
('institution.iran.national_museum','civ.persian','MODERN_CUSTODY','SUPPORTED','Modern Iranian museum institution');

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0140.xerxes.en','historical.achaemenid.xerxes_i','Xerxes I','xerxes i','lang.en','Latin','PREFERRED',1,'source.iranica.susa_achaemenid','Historical ruler; later namesakes remain separate.'),
('name.v0140.xerxes.oldpersian','historical.achaemenid.xerxes_i','Xsayarsa','xsayarsa','lang.peo','Latin transliteration','ORIGINAL_TRANSLITERATION',1,'source.iranica.susa_achaemenid','Conventional normalized transliteration without special characters.'),
('name.v0140.susa.en','site.iran.susa','Susa','susa','lang.en','Latin','PREFERRED',1,'source.iranica.susa_achaemenid',NULL),
('name.v0140.susa.zh','site.iran.susa','苏萨','苏萨','lang.zh','Han','TRANSLATION',1,NULL,NULL),
('name.v0140.gate.en','site.iran.susa_darius_gate','Darius Gate','darius gate','lang.en','Latin','PREFERRED',1,'source.iran.susa_darius_gate.achemenet',NULL),
('name.v0140.transfer.en','event.persia.darius_statue_transfer_egypt_susa','Reconstructed Transfer of the Darius Statue to Susa','reconstructed transfer darius statue susa','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.susa_achaemenid','Modern event label; reconstruction status must remain visible.'),
('name.v0140.discovery.en','event.archaeology.darius_statue_discovery_1972','Discovery of the Darius Statue at Susa (1972)','discovery darius statue susa 1972','lang.en','Latin','DESCRIPTIVE',1,'source.iran.susa_darius_statue.achemenet','Modern archaeological event label.'),
('name.v0140.nmi.en','institution.iran.national_museum','National Museum of Iran','national museum iran','lang.en','Latin','PREFERRED',1,'source.iran.susa_darius_statue.achemenet',NULL),
('name.v0140.nmi.zh','institution.iran.national_museum','伊朗国家博物馆','伊朗国家博物馆','lang.zh','Han','TRANSLATION',1,NULL,NULL);

INSERT OR IGNORE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,date_range,builders,architecture_summary,excavation_summary,major_finds_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.iran.susa','ARCHAEOLOGICAL_SITE','Susa','Shush','IR','Multi-period; Achaemenid royal city after ca. 520 BCE','Multiple periods; Darius I and successors in the Achaemenid layer','Royal palace, Apadana and monumental access structures on shaped mounds','French and Iranian campaigns across multiple periods; Achaemenid evidence remains incomplete','Darius statue, palace inscriptions, architectural and other multi-period finds','UNESCO World Heritage property; exact component mapping not expanded in this batch','REAL_ARCHAEOLOGICAL','SOURCE_BACKED'),
('site.iran.susa_darius_gate','MONUMENT','Gate of Darius','Susa archaeological site','IR','Achaemenid, Darius I to Xerxes I','Begun by Darius I; completed by Xerxes I','Square official entrance with a hypostyle central hall; mud-brick construction with stone elements','Excavated within the palace approach; statue found beside the passage','Egyptian statue of Darius I and inscribed column bases',NULL,'REAL_ARCHAEOLOGICAL','SOURCE_BACKED');

INSERT OR IGNORE INTO myth_event_profiles(entity_id,event_type,time_layer,cause_summary,process_summary,result_summary,symbolism_summary) VALUES
('event.persia.darius_statue_transfer_egypt_susa','HISTORICAL_RECONSTRUCTION','Early fifth century BCE, attributed to Xerxes I','The proposed Heliopolis destination and the reason for relocation remain matters of scholarly reconstruction','Object was moved from its Egyptian setting to the official palace entrance at Susa, according to the registered synthesis','Statue installed beside the Darius Gate passage','Cross-regional royal monument itinerary; interpretation kept separate from direct inscription statements'),
('event.archaeology.darius_statue_discovery_1972','MODERN_ARCHAEOLOGICAL_DISCOVERY','1972-12-24','Chance discovery during Susa excavation work','Fragmentary over-life-size statue recovered at the Darius Gate context','Object conserved and displayed at the National Museum of Iran','Modern discovery history only; no mythic status');

INSERT OR IGNORE INTO claims(
 id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,
 variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,
 knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at
) VALUES
('claim.v0140.susa_darius_residence','site.iran.susa','ASSOCIATED_WITH','historical.achaemenid.darius_i',NULL,NULL,'Darius I chose Susa as a royal residence soon after 520 BCE.','susa.achaemenid.royal_residence','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Achaemenid Susa','after ca. 520 BCE','Residence context; not a claim that Susa began with Darius.','2026-08-27T00:00:00Z'),
('claim.v0140.gate_part_susa','site.iran.susa_darius_gate','PART_OF','site.iran.susa',NULL,NULL,'The Darius Gate is a monument-level component of the Achaemenid royal complex at Susa.','susa.darius_gate.context','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Susa royal complex','Achaemenid','Whole site and monument remain separate records.','2026-08-27T00:00:00Z'),
('claim.v0140.gate_begun_darius','site.iran.susa_darius_gate','CREATED_BY','historical.achaemenid.darius_i',NULL,NULL,'The official palace gate was begun under Darius I.','susa.darius_gate.phases','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Susa building phases','522-486 BCE','Construction phase, not sole-builder simplification.','2026-08-27T00:00:00Z'),
('claim.v0140.gate_finished_xerxes','site.iran.susa_darius_gate','CREATED_BY','historical.achaemenid.xerxes_i',NULL,NULL,'The gate was completed under Xerxes I.','susa.darius_gate.phases','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Susa building phases','486-465 BCE','Completion phase kept distinct from inception.','2026-08-27T00:00:00Z'),
('claim.v0140.gate_official_entrance','site.iran.susa_darius_gate','ASSOCIATED_WITH',NULL,'official entrance to the palace of Darius','text','The gate functioned as the official entrance to the palace complex.','susa.darius_gate.function','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Susa palace approach','Achaemenid','The source notes it may not have been the only entrance.','2026-08-27T00:00:00Z'),
('claim.v0140.statue_at_gate','museum.iran.darius_susa_statue','EXCAVATED_AT','site.iran.susa_darius_gate',NULL,NULL,'The surviving statue was discovered in the Darius Gate passage context at Susa.','susa.darius_statue.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Susa excavation','1972','Findspot is distinct from proposed original destination.','2026-08-27T00:00:00Z'),
('claim.v0140.statue_probable_pair','site.iran.susa_darius_gate','ASSOCIATED_WITH',NULL,'the passage was probably flanked by two statues of Darius','text','The archaeological synthesis reconstructs a probable pair of statues flanking the passage.','susa.darius_statue.pair_reconstruction','INTERPRETIVE',0.78,'MEDIUM','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Darius Gate reconstruction','Achaemenid','Only one surviving statue is registered; no second object entity is created.','2026-08-27T00:00:00Z'),
('claim.v0140.transfer_subject','event.persia.darius_statue_transfer_egypt_susa','HAS_PARTICIPANT','museum.iran.darius_susa_statue',NULL,NULL,'The Darius statue is the object involved in the reconstructed transfer from Egypt to Susa.','susa.darius.transfer.event','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Object itinerary','early fifth century BCE','Event record models the interpretation without asserting a documented route itinerary.','2026-08-27T00:00:00Z'),
('claim.v0140.transfer_xerxes','historical.achaemenid.xerxes_i','PARTICIPATED_IN','event.persia.darius_statue_transfer_egypt_susa',NULL,NULL,'Encyclopaedia Iranica attributes the transfer of the statue to Xerxes I.','susa.darius.transfer.attribution','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Object itinerary reconstruction','reign of Xerxes I','Attribution is not direct ancient narrative testimony.','2026-08-27T00:00:00Z'),
('claim.v0140.transfer_arrived_susa','event.persia.darius_statue_transfer_egypt_susa','ASSOCIATED_WITH','site.iran.susa',NULL,NULL,'The reconstructed transfer ends at Susa, where the statue was installed at the palace gate.','susa.darius.transfer.destination','SUPPORTED',0.94,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Object itinerary reconstruction','early fifth century BCE','Arrival context is supported by findspot and installation.','2026-08-27T00:00:00Z'),
('claim.v0140.discovery_event_statue','event.archaeology.darius_statue_discovery_1972','HAS_PARTICIPANT','museum.iran.darius_susa_statue',NULL,NULL,'The modern discovery event concerns the surviving Darius statue.','susa.darius.discovery.event','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern excavation history','1972-12-24',NULL,'2026-08-27T00:00:00Z'),
('claim.v0140.discovery_date','event.archaeology.darius_statue_discovery_1972','ASSOCIATED_WITH',NULL,'24 December 1972','date','Achemenet records the chance discovery on 24 December 1972.','susa.darius.discovery.date','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern excavation history','1972-12-24',NULL,'2026-08-27T00:00:00Z'),
('claim.v0140.discovery_at_gate','event.archaeology.darius_statue_discovery_1972','ASSOCIATED_WITH','site.iran.susa_darius_gate',NULL,NULL,'The discovery occurred in the Darius Gate context.','susa.darius.discovery.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern excavation history','1972-12-24',NULL,'2026-08-27T00:00:00Z'),
('claim.v0140.statue_held_nmi','museum.iran.darius_susa_statue','HELD_BY_MUSEUM','institution.iran.national_museum',NULL,NULL,'The statue is displayed at the National Museum of Iran in Tehran.','susa.darius.modern_custody','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern custody','current project presentation','Exact inventory number remains deliberately unset.','2026-08-27T00:00:00Z'),
('claim.v0140.statue_foundation_lead','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'fixed with lead to two stone slabs set on a larger foundation','text','The statue was fixed with lead to two stone slabs resting on a larger foundation.','susa.darius.installation','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Darius Gate installation','Achaemenid','Physical installation observation, separate from transfer motive.','2026-08-27T00:00:00Z'),
('claim.v0140.inventory_unverified','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'exact current museum inventory number remains unverified in the authority set','text','This release does not assign an exact museum inventory number because the checked authority pages do not expose one reliably.','susa.darius.modern_inventory','INTERPRETIVE',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Modern custody','2026-08-27','Explicit gap marker; not an absence claim about the museum records.','2026-08-27T00:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes) VALUES
('evidence.v0140.susa_darius_residence','claim.v0140.susa_darius_residence','source.iranica.susa_achaemenid','Archaeological data and royal-residence overview; lines 37-39',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.98,'Date and historical scope preserved.'),
('evidence.v0140.gate_part_susa','claim.v0140.gate_part_susa','source.iranica.susa_achaemenid','Palace approach and Gate of Darius; lines 61-63',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.99,'Monument/site hierarchy.'),
('evidence.v0140.gate_begun_darius','claim.v0140.gate_begun_darius','source.iranica.susa_achaemenid','Gate construction phases; line 62','XSd context','MODERN_SCHOLARSHIP','SUPPORTS',0.98,'Phase attribution from archaeological and inscription synthesis.'),
('evidence.v0140.gate_finished_xerxes','claim.v0140.gate_finished_xerxes','source.iranica.susa_achaemenid','Gate construction phases; line 62','XSd context','MODERN_SCHOLARSHIP','SUPPORTS',0.98,'Completion attribution retained separately.'),
('evidence.v0140.gate_official_entrance','claim.v0140.gate_official_entrance','source.iranica.susa_achaemenid','Gate function; line 62',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.96,'Source caveat that another entrance may have existed is retained in claim notes.'),
('evidence.v0140.statue_at_gate','claim.v0140.statue_at_gate','source.iranica.susa_achaemenid','Gate passage and statue; lines 62-64','DSab carrier context','ARCHAEOLOGICAL','SUPPORTS',0.99,'Find context and object identity.'),
('evidence.v0140.statue_probable_pair','claim.v0140.statue_probable_pair','source.iranica.susa_achaemenid','Gate passage reconstruction; line 63',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.78,'Probability language preserved; no phantom object record.'),
('evidence.v0140.transfer_subject','claim.v0140.transfer_subject','source.iranica.susa_achaemenid','Statue itinerary synthesis; line 64',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.90,'Event model derived from source interpretation.'),
('evidence.v0140.transfer_xerxes','claim.v0140.transfer_xerxes','source.iranica.susa_achaemenid','Statue itinerary synthesis; line 64',NULL,'MODERN_SCHOLARSHIP','SUPPORTS',0.90,'Royal attribution remains interpretive.'),
('evidence.v0140.transfer_arrived_susa','claim.v0140.transfer_arrived_susa','source.iranica.susa_achaemenid','Statue itinerary and gate context; lines 63-64',NULL,'ARCHAEOLOGICAL','SUPPORTS',0.94,'Findspot plus installation context.'),
('evidence.v0140.discovery_event_statue','claim.v0140.discovery_event_statue','source.iran.susa_darius_statue.achemenet','Statue overview, discovery paragraph','Darius statue overview','ARCHAEOLOGICAL','SUPPORTS',0.99,'Modern discovery record.'),
('evidence.v0140.discovery_date','claim.v0140.discovery_date','source.iran.susa_darius_statue.achemenet','Statue overview, discovery date','Darius statue overview','ARCHAEOLOGICAL','SUPPORTS',0.99,'Exact date retained.'),
('evidence.v0140.discovery_at_gate','claim.v0140.discovery_at_gate','source.iranica.susa_achaemenid','Gate passage and statue; line 63',NULL,'ARCHAEOLOGICAL','SUPPORTS',0.99,'Monument-level find context.'),
('evidence.v0140.statue_held_nmi','claim.v0140.statue_held_nmi','source.iran.susa_darius_statue.achemenet','Statue overview, present display','Darius statue overview','MUSEUM_OBJECT','SUPPORTS',0.99,'Modern custody; inventory number not inferred.'),
('evidence.v0140.statue_foundation_lead','claim.v0140.statue_foundation_lead','source.iran.susa_darius_foundation.achemenet','Foundation description','Darius statue foundation','ARCHAEOLOGICAL','SUPPORTS',0.98,'Installation observation.'),
('evidence.v0140.inventory_unverified','claim.v0140.inventory_unverified','source.iran.susa_darius_statue.achemenet','Checked overview metadata','Darius statue overview','MUSEUM_OBJECT','SUPPORTS',1.0,'Audit finding limited to the checked authority set; does not claim no inventory number exists.');

INSERT OR IGNORE INTO event_participants(event_id,participant_id,role,outcome,claim_id) VALUES
('event.persia.darius_statue_transfer_egypt_susa','museum.iran.darius_susa_statue','TRANSFERRED_OBJECT','Installed at Susa gate','claim.v0140.transfer_subject'),
('event.persia.darius_statue_transfer_egypt_susa','historical.achaemenid.xerxes_i','ATTRIBUTED_ROYAL_AGENT','Transfer attributed in modern scholarship','claim.v0140.transfer_xerxes'),
('event.archaeology.darius_statue_discovery_1972','museum.iran.darius_susa_statue','DISCOVERED_OBJECT','Recovered fragmentary and later displayed in Tehran','claim.v0140.discovery_event_statue');

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0140.statue_transfer_directness','event.persia.darius_statue_transfer_egypt_susa','susa.darius.transfer.evidence_status','claim.v0130.statue_transfer_xerxes','claim.v0140.transfer_xerxes','EVIDENCE_LIMIT','OPEN','Two database claims repeat the same scholarly attribution, but neither is a direct ancient account of the transfer route or motive.','Treat the transfer as a sourced historical reconstruction until excavation publications or primary documentation provide a stronger chain.'),
('conflict.v0140.statue_pair_reconstruction','site.iran.susa_darius_gate','susa.darius.statue_count','claim.v0140.statue_at_gate','claim.v0140.statue_probable_pair','RECONSTRUCTION_LIMIT','OPEN','One surviving statue is archaeologically registered while the flanking pair is a probable architectural reconstruction.','Do not create or merge a second statue object without independent remains or catalogue evidence.');

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,last_error=NULL,
 next_action='Expand the underlying excavation argument, gate phasing and route chronology while preserving the transfer as a reconstruction',
 updated_at='2026-08-27T07:00:00Z' WHERE id='queue.v0130.persia.xerxes_statue_transfer';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,
 next_action='Register exact excavation locus, field publication and official museum inventory when an authority record exposes them',
 updated_at='2026-08-27T07:00:00Z' WHERE id='queue.v0120.iran.darius_statue_provenance';

INSERT OR IGNORE INTO queue_status_history(id,queue_id,old_status,new_status,changed_at,reason) VALUES
('queuehist.v0140.xerxes_transfer','queue.v0130.persia.xerxes_statue_transfer','SOURCE_FOUND','BASELINE_COMPLETE','2026-08-27T07:00:00Z','Added Xerxes, Susa, Darius Gate and a separately qualified transfer-event reconstruction.'),
('queuehist.v0140.statue_provenance','queue.v0120.iran.darius_statue_provenance','SOURCE_FOUND','PARTIAL','2026-08-27T07:00:00Z','Added discovery date, gate find context, installation foundation and modern custody while leaving exact inventory and field locus open.');

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0140.iran.darius_statue_field_publication','Darius statue 1972 excavation locus and field publication','darius statue 1972 excavation locus field publication','ARCHAEOLOGICAL_SITE','civ.persian','event.archaeology.darius_statue_discovery_1972','claim.v0140.discovery_at_gate','source.iran.susa_darius_statue.achemenet','The public project page gives the date and gate context but not a complete locus sheet or excavation stratigraphy.',99,'SOURCE_FOUND',0,'Locate the Perrot mission field publication; register trench, locus, stratigraphy, excavators and page/plate locators without copying protected figures','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('queue.v0140.iran.darius_statue_inventory','Darius statue National Museum of Iran inventory record','darius statue national museum iran inventory','MUSEUM_OBJECT','civ.persian','museum.iran.darius_susa_statue','claim.v0140.inventory_unverified','source.iran.susa_darius_statue.achemenet','Present custody is secure, but the checked authority set does not expose a reliably citable inventory number.',99,'NEEDS_REVIEW',0,'Use an official National Museum catalogue or direct collection record; never infer the inventory from secondary pages','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('queue.v0140.persia.darius_gate_phases','Darius Gate construction phases and XSd inscription','darius gate phases xsd inscription','ARCHAEOLOGICAL_SITE','civ.persian','site.iran.susa_darius_gate','claim.v0140.gate_finished_xerxes','source.iranica.susa_achaemenid','The gate has at least Darius inception and Xerxes completion layers; exact architecture and inscription locators remain incomplete.',98,'SOURCE_FOUND',0,'Register plans, dimensions, column-base inscriptions and Darius/Xerxes phase evidence with edition-specific locators','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('queue.v0140.persia.darius_statue_second_pair','Probable second Darius statue at the Susa gate','probable second darius statue susa gate','MUSEUM_OBJECT','civ.persian','site.iran.susa_darius_gate','claim.v0140.statue_probable_pair','source.iranica.susa_achaemenid','The architectural synthesis suggests a pair, but only one surviving object is registered.',97,'CONFLICT',0,'Search excavation plans and fragments; create a second object only if independent material or catalogue evidence exists','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('queue.v0140.persia.transfer_route_argument','Darius statue Egypt-to-Susa transfer route and motive argument','darius statue egypt susa transfer route motive','EVENT','civ.persian','event.persia.darius_statue_transfer_egypt_susa','claim.v0140.transfer_xerxes','source.iranica.susa_achaemenid','The attribution to Xerxes is registered, but route, date, motive and underlying argument are not directly attested in the checked source set.',98,'SOURCE_FOUND',0,'Audit excavation publications, Egyptian destination argument and Achaemenid chronology; record disagreements rather than selecting a single motive','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z'),
('queue.v0140.iran.susa_unesco_component','Susa UNESCO property component and management context','susa unesco component management context','ARCHAEOLOGICAL_SITE','civ.persian','site.iran.susa','claim.v0140.susa_darius_residence','source.iran.susa_royal_city.met1992','The real-site dossier should connect to the official UNESCO nomination and management records without flattening all periods into an Achaemenid site.',96,'DISCOVERED',0,'Register UNESCO property identifiers, component boundaries and multi-period statements from UNESCO and Iranian authorities','2026-08-27T00:00:00Z','2026-08-27T00:00:00Z');

INSERT OR IGNORE INTO queue_discoveries(id,queue_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,discovered_at)
SELECT 'discovery.'||substr(id,7),id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,'2026-08-27T00:00:00Z' FROM collection_queue WHERE id LIKE 'queue.v0140.%';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260827.v0140_darius_statue_provenance','2026-08-27T00:00:00Z','2026-08-27T07:00:00Z','Darius statue Susa find context, gate construction phases, Xerxes transfer reconstruction, 1972 discovery and modern custody','Continue two source-found permanent-queue branches with archaeological project pages, scholarly reference and museum publication; preserve ancient manufacture, reconstructed transfer, excavation and custody as distinct layers','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Exact field locus, museum inventory, transfer argument, second-statue evidence and UNESCO component mapping remain queued.');
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260827.v0140_darius_statue_provenance','SOURCE',id,'REGISTER','AUTHORITY_AND_RIGHTS_RETAINED' FROM sources WHERE accessed_date='2026-08-27';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260827.v0140_darius_statue_provenance','CLAIM',id,'REGISTER','SOURCE_LOCATED' FROM claims WHERE id LIKE 'claim.v0140.%';
INSERT OR IGNORE INTO research_session_items(session_id,item_kind,item_id,action,result)
SELECT 'research.20260827.v0140_darius_statue_provenance','ENTITY',id,'CREATE','PROVENANCE_LAYER_REGISTERED' FROM entities WHERE created_at='2026-08-27T00:00:00Z';

UPDATE museum_object_profiles SET acquisition_notes='Displayed at the National Museum of Iran; exact inventory number remains queued and is not inferred from secondary records' WHERE entity_id='museum.iran.darius_susa_statue';
UPDATE civilizations SET research_status='COLLECTING',evidence_status='PARTIAL' WHERE id IN ('civ.egyptian','civ.persian');
UPDATE project_metadata SET value='0.14.0-darius-statue-provenance-20260827',updated_at='2026-08-27T07:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='21',updated_at='2026-08-27T07:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T07:00:00Z',updated_at='2026-08-27T07:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.14.0',21,'0.14.0-darius-statue-provenance-20260827',NULL,'2026-08-27T07:00:00Z',NULL,'Darius statue provenance checkpoint: Susa and Darius Gate site layers, Xerxes I, separately qualified transfer and discovery events, modern custody, physical foundation evidence and six permanent follow-up branches.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES
(21,'20260827_v0140_darius_statue_provenance','2026-08-27T07:00:00Z');

COMMIT;
