BEGIN IMMEDIATE;

-- v0.16.0 completes a first archaeological chain around the statue while
-- keeping World Heritage scope, ancient carrier evidence, reconstructed
-- itinerary and modern inventory practice separate.

INSERT OR IGNORE INTO sources(
 id,title,source_type,evidence_tier,institution,author_or_editor,language_id,
 publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,
 access_or_reuse_restrictions,community_permission_required,translation_status,
 verification_status,notes
) VALUES
('source.unesco.susa.1455','Susa — World Heritage List','OFFICIAL_HERITAGE_RECORD',3,'UNESCO World Heritage Centre','UNESCO World Heritage Centre','lang.en','2015','2026-08-27','https://whc.unesco.org/en/list/1455/','World Heritage property 1455','UNESCO page terms apply; metadata and independent summaries only','Official serial-property description and inscription metadata','Do not package UNESCO images or large text extracts',0,'Official English page','URL_SYNTAX_VALID','The property is multi-period and includes archaeological mounds plus the palace across the river; it must not be reduced to the Achaemenid layer.'),
('source.unesco.susa.maps1455','Susa — maps of the inscribed property','OFFICIAL_HERITAGE_RECORD',3,'UNESCO World Heritage Centre','UNESCO World Heritage Centre','lang.en','2015','2026-08-27','https://whc.unesco.org/en/list/1455/maps/','1455-001 and 1455-002','UNESCO page terms apply; component metadata and independent summaries only','Official component identifiers, coordinates and areas','No map-image redistribution',0,'Official English page','URL_SYNTAX_VALID','Lists Susa archaeological complex (1455-001, 346.5 ha) and Ardeshir Palace (1455-002, 3.5 ha).'),
('source.iran.susa_xsd.achemenet','Susa: The Inscribed Column Bases of the Darius Gate','SCHOLARLY_PROJECT',3,'Achemenet / Musée du Louvre research network','Pierre Briant project','lang.en',NULL,'2026-08-27','https://www.achemenet.com/en/visit/?/susa/the-inscribed-column-bases-of-the-darius-gate/2=','XSd','Project website rights apply; metadata, locators and independent summaries only','Scholarly archaeological and epigraphic presentation of the gate column bases','Do not package page images or extended translation',0,'English presentation of a trilingual ancient inscription','URL_SYNTAX_VALID','Records the short trilingual XSd inscription on a visible plinth edge and its attribution of the portico to Darius in Xerxes voice.'),
('source.egypt.darius_stone.trichet1990','L’origine égyptienne de la statue de Darius','SCHOLARLY_ARTICLE',3,'Tübingen University Library bibliographic network','J. Trichet and collaborators','lang.fra','1990','2026-08-27','https://vergil.uni-tuebingen.de/keibi/Record/KEI00077397','Bibliographic follow-up listed under KeiBi 38:559','Article copyright applies; bibliography and independent summaries only','Scientific provenance study cited by the Darius-statue research bibliography','Underlying article required for laboratory-method expansion',0,'French scholarly article','URL_SYNTAX_VALID','Registered only as the scientific-provenance research branch; exact analytical method and sample chain are not inferred from the bibliography.'),
('source.iran.darius_inventory.wasmuth2019','Transient or Eternal? Cross-Regional Identity Display Reconsidered: The Missing Head of the Statue of Darius I (NMI 4112)','SCHOLARLY_ARTICLE',3,'Journal of Ancient Egyptian Interconnections','Melanie Wasmuth','lang.en','2019','2026-08-27','https://core.ac.uk/download/pdf/328853988.pdf','JAEI 24, pp. 49-66; cited object label NMI 4112','Article copyright applies; bibliography and independent summaries only','Modern scholarly discussion using an NMI object identifier','Identifier remains a scholarly citation until matched to an official National Museum of Iran collection record',0,'English scholarly article','URL_SYNTAX_VALID','Provides a scholarly usage of NMI 4112; it does not replace an official museum catalogue confirmation.');

INSERT OR IGNORE INTO entities(
 id,canonical_name,name_zh,original_name,transliteration,primary_type,
 primary_civilization_id,primary_region_id,historical_period,description,
 research_status,evidence_status,record_version,metadata_json,created_at,updated_at
) VALUES
('text.archaeology.darius_statue_susa_dossier_1972','1972 Darius Statue Susa Report Dossier','1972年苏萨大流士雕像报告组','Une statue de Darius découverte à Suse',NULL,'TEXT','civ.persian','region.west_asia','Published 1972','包含考古语境、器物描述、DSab 与象形文字四部分的学术报告组；各分部页码保持独立。 / Scholarly report dossier with separate archaeological, object, DSab and hieroglyphic sections.','PARTIAL','SOURCE_BACKED',1,'{"document_role":"COMPOSITE_SCHOLARLY_DOSSIER","parts":["Kervran 235-239","Stronach 241-246","Vallat 247-251","Yoyotte 253-266"]}','2026-08-27T09:00:00Z','2026-08-27T09:00:00Z'),
('text.persia.xsd','XSd Inscription','XSd 铭文','XSd','XSd','INSCRIPTION','civ.persian','region.west_asia','Reign of Xerxes I','苏萨大流士门柱础上的短篇三语铭文；文本见证与门楼建筑分开。 / Short trilingual inscription on column bases of the Darius Gate, separate from the architecture it labels.','PARTIAL','SOURCE_BACKED',1,'{"witness_role":"MONUMENTAL_INSCRIPTION","languages":["lang.peo","lang.elx","lang.akk"],"carrier":"site.iran.susa_darius_gate"}','2026-08-27T09:00:00Z','2026-08-27T09:00:00Z'),
('site.egypt.heliopolis_atum_precinct','Atum Precinct at Heliopolis','赫利奥波利斯阿图姆圣区','Iunu',NULL,'ARCHAEOLOGICAL_SITE','civ.egyptian','region.northeast_africa','Ancient Egyptian; proposed Darius-statue destination','现实古代圣区的研究定位档；与“雕像原拟安置于此”的现代学术重建分开。 / Real ancient cult precinct record, distinct from the modern reconstruction that the statue was intended for it.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_HISTORICAL_SITE","itinerary_role":"PROPOSED_DESTINATION_ONLY"}','2026-08-27T09:00:00Z','2026-08-27T09:00:00Z'),
('site.egypt.wadi_hammamat_quarries','Wadi Hammamat Quarry Landscape','瓦迪哈马马特采石景观','Wadi Hammamat',NULL,'ARCHAEOLOGICAL_SITE','civ.egyptian','region.northeast_africa','Ancient Egyptian quarry and route landscape','雕像石材来源论证涉及的现实采石景观；具体采样、岩相与化学方法仍需原始科技报告。 / Real quarry landscape associated with the stone-provenance argument; sampling and analytical methods remain to be audited.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","provenance_role":"SCIENTIFIC_SOURCE_HYPOTHESIS"}','2026-08-27T09:00:00Z','2026-08-27T09:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes)
SELECT id,primary_type,1,'v0.16.0 Darius archaeological chain' FROM entities WHERE created_at='2026-08-27T09:00:00Z';

INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) VALUES
('text.archaeology.darius_statue_susa_dossier_1972','civ.persian','MODERN_ARCHAEOLOGICAL_SCHOLARSHIP','SUPPORTED','Report on an Achaemenid object found at Susa'),
('text.archaeology.darius_statue_susa_dossier_1972','civ.egyptian','OBJECT_ORIGIN_CONTEXT','SUPPORTED','Contains the Egyptian-inscription report'),
('text.persia.xsd','civ.persian','ROYAL_INSCRIPTION','SUPPORTED','Xerxes-period gate inscription'),
('site.egypt.heliopolis_atum_precinct','civ.egyptian','CULT_PLACE','SUPPORTED','Ancient Egyptian Heliopolis context'),
('site.egypt.wadi_hammamat_quarries','civ.egyptian','QUARRY_LANDSCAPE','SUPPORTED','Egyptian Eastern Desert stone source context');

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0160.dossier.fr','text.archaeology.darius_statue_susa_dossier_1972','Une statue de Darius découverte à Suse','une statue de darius decouverte a suse','lang.fra','Latin','ORIGINAL_TITLE',1,'source.biblio.tuebingen.darius_dossier1972',NULL),
('name.v0160.xsd','text.persia.xsd','XSd','xsd','lang.en','Latin','CATALOGUE_LABEL',1,'source.iran.susa_xsd.achemenet','Modern epigraphic siglum.'),
('name.v0160.heliopolis.en','site.egypt.heliopolis_atum_precinct','Atum Precinct at Heliopolis','atum precinct heliopolis','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.susa_achaemenid','Proposed itinerary role remains qualified.'),
('name.v0160.heliopolis.egy','site.egypt.heliopolis_atum_precinct','Iunu','iunu','lang.egy','Latin transliteration','HISTORICAL_NAME',1,'source.iranica.susa_achaemenid','Normalized transliteration.'),
('name.v0160.wadi.en','site.egypt.wadi_hammamat_quarries','Wadi Hammamat Quarries','wadi hammamat quarries','lang.en','Latin','DESCRIPTIVE',1,'source.iranica.susa_achaemenid',NULL);

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.archaeology.darius_statue_susa_dossier_1972','SCHOLARLY_REPORT_DOSSIER','lang.fra','Kervran, Stronach, Vallat and Yoyotte',NULL,'1972','Journal asiatique 260','Four separately paginated specialist contributions','University and research libraries','Journal asiatique 260, pp. 235-266','Modern article copyright applies','Composite publication record preserving its archaeology, object description, cuneiform and hieroglyphic divisions.'),
('text.persia.xsd','ROYAL_MONUMENTAL_INSCRIPTION','lang.peo','Xerxes I',NULL,'Reign of Xerxes I','Stone column-base carriers at Susa','Parallel Old Persian, Elamite and Akkadian versions','Susa archaeological site','XSd','Ancient inscription public domain; modern editions retain rights','Short royal inscription linking Xerxes voice, Darius and the gate portico.');

INSERT OR REPLACE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,date_range,builders,architecture_summary,excavation_summary,major_finds_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.iran.susa','ARCHAEOLOGICAL_SITE','Susa','Shush','IR','Late fifth millennium BCE to thirteenth century CE; multiple superimposed settlements','Multiple periods; Darius I and successors in the Achaemenid layer','Serial World Heritage property with archaeological mounds east of the Shavur and a palace component west of the river','Long-running excavations exposed administrative, residential and palatial structures across many periods','Darius statue, palace inscriptions, architecture and multi-period finds','UNESCO 1455, inscribed 2015 under criteria (i)(ii)(iii)(iv); components 1455-001 and 1455-002','REAL_ARCHAEOLOGICAL','SOURCE_BACKED'),
('site.egypt.heliopolis_atum_precinct','CULT_PRECINCT','Iunu','Heliopolis / Matariya area','EG','Ancient Egyptian through later reuse','Multiple rulers and temple institutions','Atum cult precinct; no reconstructed Darius-statue installation is treated as excavated fact','Ancient site remains survive in a heavily transformed urban landscape','Monumental fragments and inscriptions; Darius statue destination remains a scholarly proposal',NULL,'REAL_HISTORIC','SOURCE_BACKED'),
('site.egypt.wadi_hammamat_quarries','QUARRY_LANDSCAPE','Wadi Hammamat','Wadi Hammamat','EG','Pharaonic through later quarry and route use','Multiple quarrying expeditions','Eastern Desert quarry and route landscape','Rock inscriptions and extraction traces document long use','Stone and inscription contexts; exact Darius-statue sample chain remains queued',NULL,'REAL_ARCHAEOLOGICAL','SOURCE_BACKED');

INSERT OR IGNORE INTO claims(
 id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,
 variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,
 knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at
) VALUES
('claim.v0160.dossier_statue','text.archaeology.darius_statue_susa_dossier_1972','ASSOCIATED_WITH','museum.iran.darius_susa_statue',NULL,NULL,'The 1972 dossier is the composite first-report publication for the Susa Darius statue.','darius.report.publication','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','SCHOLARLY_INTERPRETATION','Modern archaeology','1972','Publication relation, not an ancient witness.','2026-08-27T09:00:00Z'),
('claim.v0160.dossier_context_section','text.archaeology.darius_statue_susa_dossier_1972','HAS_PART',NULL,'Kervran archaeological-context report, pp. 235-239','text','The dossier separates Kervran’s archaeological-context contribution at pages 235–239.','darius.report.sections','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','SCHOLARLY_INTERPRETATION','Modern archaeology','1972',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.dossier_object_section','text.archaeology.darius_statue_susa_dossier_1972','HAS_PART',NULL,'Stronach description and comment, pp. 241-246','text','The dossier separates Stronach’s object description and comment at pages 241–246.','darius.report.sections','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','SCHOLARLY_INTERPRETATION','Modern archaeology','1972',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.xsd_on_gate','text.persia.xsd','DEPICTED_ON','site.iran.susa_darius_gate',NULL,NULL,'XSd is carried on inscribed column bases of the Darius Gate.','susa.gate.xsd.carrier','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Achaemenid Susa','reign of Xerxes I',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.xsd_three_languages','text.persia.xsd','ASSOCIATED_WITH',NULL,'parallel Old Persian, Elamite and Akkadian versions','text','XSd is a short trilingual inscription with Old Persian, Elamite and Akkadian versions.','susa.gate.xsd.languages','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Achaemenid royal inscription','reign of Xerxes I',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.xsd_attributes_darius','text.persia.xsd','MENTIONS','historical.achaemenid.darius_i',NULL,NULL,'In Xerxes’ royal voice, XSd attributes construction of the portico to his father Darius.','susa.gate.xsd.construction','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Achaemenid royal inscription','reign of Xerxes I','This is what the inscription says, not a complete archaeological phase model.','2026-08-27T09:00:00Z'),
('claim.v0160.susa_unesco','site.iran.susa','ASSOCIATED_WITH',NULL,'UNESCO World Heritage property 1455, inscribed in 2015','text','Susa is World Heritage property 1455, inscribed in 2015.','susa.unesco.status','SUPPORTED',1.0,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern heritage administration','2015-present',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.susa_component_001','site.iran.susa','ASSOCIATED_WITH',NULL,'component 1455-001: Susa archaeological complex, 346.5 ha','text','UNESCO component 1455-001 is the Susa archaeological complex with a listed property area of 346.5 hectares.','susa.unesco.components','SUPPORTED',1.0,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','World Heritage property','2015',NULL,'2026-08-27T09:00:00Z'),
('claim.v0160.susa_multiperiod','site.iran.susa','ASSOCIATED_WITH',NULL,'multiple superimposed urban settlements from the late fifth millennium BCE to the thirteenth century CE','text','The UNESCO description presents Susa as a multi-period succession, not solely an Achaemenid site.','susa.unesco.period_scope','SUPPORTED',1.0,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Susa','long duration','Prevents period flattening.','2026-08-27T09:00:00Z'),
('claim.v0160.heliopolis_proposed','museum.iran.darius_susa_statue','ASSOCIATED_WITH','site.egypt.heliopolis_atum_precinct',NULL,NULL,'Heliopolis is registered as a proposed original destination of the Darius statue, not as a certain excavated installation.','darius.statue.original_destination','INTERPRETIVE',0.74,'MEDIUM','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Object itinerary reconstruction','reign of Darius I','Proposal preserved alongside competing destination discussion.','2026-08-27T09:00:00Z'),
('claim.v0160.wadi_provenance','museum.iran.darius_susa_statue','ASSOCIATED_WITH','site.egypt.wadi_hammamat_quarries',NULL,NULL,'The statue’s stone is associated in scholarship with the Wadi Hammamat quarry landscape.','darius.statue.stone_provenance','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Scientific provenance','modern analysis','Exact sampling and laboratory method remain queued.','2026-08-27T09:00:00Z'),
('claim.v0160.inventory_scholarly_label','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'NMI 4112 is used as an object identifier in Wasmuth 2019','text','A 2019 scholarly article cites the statue as NMI 4112.','darius.statue.modern_inventory','SUPPORTED',0.90,'HIGH','VERIFIED','HISTORICAL_REALITY','SCHOLARLY_INTERPRETATION','Modern scholarship','2019','Scholarly usage is not yet an official museum catalogue confirmation.','2026-08-27T09:00:00Z'),
('claim.v0160.inventory_official_gap','museum.iran.darius_susa_statue','ASSOCIATED_WITH',NULL,'official National Museum of Iran collection-page confirmation of NMI 4112 remains unavailable in the checked authority set','text','The project retains NMI 4112 as a scholarly cited candidate until an official National Museum of Iran record is matched.','darius.statue.modern_inventory','INTERPRETIVE',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Modern custody','2026-08-27','Explicit audit state.','2026-08-27T09:00:00Z'),
('claim.v0160.transfer_route_limit','event.persia.darius_statue_transfer_egypt_susa','ASSOCIATED_WITH',NULL,'no checked ancient itinerary narrates the complete Egypt-to-Susa route or motive','text','The Egypt-to-Susa route and motive remain a scholarly reconstruction rather than a continuous ancient itinerary record.','darius.statue.transfer.evidence_limit','INTERPRETIVE',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Object itinerary','current audit','Absence is scoped to checked sources.','2026-08-27T09:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes) VALUES
('evidence.v0160.dossier_statue','claim.v0160.dossier_statue','source.biblio.tuebingen.darius_dossier1972','Title and complete Journal asiatique record','KeiBi 38:559','MODERN_SCHOLARSHIP','SUPPORTS',0.99,NULL),
('evidence.v0160.dossier_context_section','claim.v0160.dossier_context_section','source.biblio.tuebingen.darius_dossier1972','Kervran, pp. 235-239','KeiBi 38:559','MODERN_SCHOLARSHIP','SUPPORTS',0.99,NULL),
('evidence.v0160.dossier_object_section','claim.v0160.dossier_object_section','source.biblio.tuebingen.darius_dossier1972','Stronach, pp. 241-246','KeiBi 38:559','MODERN_SCHOLARSHIP','SUPPORTS',0.99,NULL),
('evidence.v0160.xsd_on_gate','claim.v0160.xsd_on_gate','source.iran.susa_xsd.achemenet','Column bases and visible plinth edge','XSd','INSCRIPTION','SUPPORTS',0.99,NULL),
('evidence.v0160.xsd_three_languages','claim.v0160.xsd_three_languages','source.iran.susa_xsd.achemenet','XSd presentation','XSd','INSCRIPTION','SUPPORTS',0.99,NULL),
('evidence.v0160.xsd_attributes_darius','claim.v0160.xsd_attributes_darius','source.iran.susa_xsd.achemenet','XSd translation synopsis','XSd','INSCRIPTION','SUPPORTS',0.98,'Short paraphrase only; no extended translation reproduced.'),
('evidence.v0160.susa_unesco','claim.v0160.susa_unesco','source.unesco.susa.1455','Official property metadata','1455','OFFICIAL_SITE','SUPPORTS',1.0,NULL),
('evidence.v0160.susa_component_001','claim.v0160.susa_component_001','source.unesco.susa.maps1455','Geographical data, component 1455-001','1455-001','OFFICIAL_SITE','SUPPORTS',1.0,NULL),
('evidence.v0160.susa_multiperiod','claim.v0160.susa_multiperiod','source.unesco.susa.1455','Official brief synthesis','1455','OFFICIAL_SITE','SUPPORTS',1.0,NULL),
('evidence.v0160.heliopolis_proposed','claim.v0160.heliopolis_proposed','source.iranica.susa_achaemenid','Statue origin and intended-destination discussion','SUSA iii','MODERN_SCHOLARSHIP','SUPPORTS',0.74,'Proposal remains qualified.'),
('evidence.v0160.wadi_provenance','claim.v0160.wadi_provenance','source.iranica.susa_achaemenid','Stone provenance summary','SUSA iii','MODERN_SCHOLARSHIP','SUPPORTS',0.90,'Scientific study branch is separately registered.'),
('evidence.v0160.inventory_scholarly_label','claim.v0160.inventory_scholarly_label','source.iran.darius_inventory.wasmuth2019','Title and article object label','JAEI 24, pp. 49-66','MODERN_SCHOLARSHIP','SUPPORTS',0.90,'Scholarly identifier only.'),
('evidence.v0160.inventory_official_gap','claim.v0160.inventory_official_gap','source.iran.darius_inventory.wasmuth2019','Scholarly use of NMI 4112 contrasted with absent checked official collection page','NMI 4112','MODERN_SCHOLARSHIP','CONTEXT',1.0,'Audit statement is limited to checked authority set.'),
('evidence.v0160.transfer_route_limit','claim.v0160.transfer_route_limit','source.iranica.susa_achaemenid','Transfer attribution summary without a continuous ancient itinerary','SUSA iii','MODERN_SCHOLARSHIP','SUPPORTS',1.0,'Evidence-limit statement.');

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0160.darius_inventory_authority','museum.iran.darius_susa_statue','darius.statue.modern_inventory','claim.v0160.inventory_scholarly_label','claim.v0160.inventory_official_gap','AUTHORITY_GAP','OPEN','NMI 4112 is used in specialist scholarship, while an official National Museum of Iran collection-page match remains unavailable in the checked source set.','Keep the profile catalogue value noncommittal until a museum catalogue, label publication or direct institutional response confirms the identifier.'),
('conflict.v0160.darius_original_destination','museum.iran.darius_susa_statue','darius.statue.original_destination','claim.v0130.statue_intended_heliopolis','claim.v0160.heliopolis_proposed','INTERPRETATION_SCOPE','OPEN','The Heliopolis destination appears in scholarly synthesis but is not an excavated installation context or continuous ancient itinerary.','Retain as a proposed destination; collect full Yoyotte argument and competing Pithom/Heliopolis readings before stronger wording.');

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,last_error=NULL,next_action='Add exact trench, locus, plates and stratigraphy from the underlying Kervran and Stronach reports when full text is lawfully accessible',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0140.iran.darius_statue_field_publication';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,next_action='Match scholarly identifier NMI 4112 against an official National Museum of Iran catalogue, label publication or institutional response',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0140.iran.darius_statue_inventory';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,last_error=NULL,next_action='Expand XSd into three language witnesses and connect architectural phases to excavation plans',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0140.persia.darius_gate_phases';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,last_error=NULL,next_action='Add UNESCO nomination and management-plan evidence without collapsing the property to its Achaemenid layer',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0140.iran.susa_unesco_component';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,next_action='Audit the complete Heliopolis/Pithom destination argument and distinguish temple theology from physical installation evidence',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0130.egypt.heliopolis_darius_destination';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,next_action='Retrieve the Trichet scientific report and register sample, petrography, analytical method and uncertainty',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0130.egypt.wadi_hammamat_provenance';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,last_error=NULL,next_action='Search for ancient or administrative transfer documentation; keep route and motive reconstructed until then',updated_at='2026-08-27T09:00:00Z' WHERE id='queue.v0140.persia.transfer_route_argument';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260827.v0160_darius_archaeological_chain','2026-08-27T08:05:00Z','2026-08-27T09:00:00Z','Darius statue field-report bibliography, XSd gate witness, UNESCO Susa components, proposed Egyptian destination, quarry provenance and inventory audit','Link official UNESCO records, institutional archaeological pages and scholarly publication metadata while retaining authority and reconstruction limits','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Official inventory confirmation, exact excavation locus, scientific sample chain and complete transfer argument remain queued.');

UPDATE project_metadata SET value='0.16.0-darius-archaeological-chain-20260827',updated_at='2026-08-27T09:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='23',updated_at='2026-08-27T09:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T09:00:00Z',updated_at='2026-08-27T09:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES
('release.0.16.0',23,'0.16.0-darius-archaeological-chain-20260827',NULL,'2026-08-27T09:00:00Z',NULL,'Darius archaeological-chain checkpoint: 1972 report dossier, XSd gate inscription, official UNESCO property components, qualified Heliopolis and Wadi Hammamat links, and a transparent NMI 4112 authority gap.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES
(23,'20260827_v0160_darius_archaeological_chain','2026-08-27T09:00:00Z');

COMMIT;
