BEGIN IMMEDIATE;

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.greek.ieleusis71.phi','I.Eleusis 71 — Decree of the Eleusinians','ACADEMIC_EPIGRAPHIC_DATABASE',3,'Packard Humanities Institute','PHI Greek Inscriptions','lang.grc',NULL,'2026-08-27','https://epigraphy.packhum.org/text/346531','I.Eleusis 71; IG II² 1185','Database terms apply; locators and independent summaries only','Academic digital edition with findspot qualification and concordance','Do not bulk reproduce edition text',0,'Ancient Greek edition metadata; project summary in English/Chinese','URL_SYNTAX_VALID','A fourth-century decree from Eleusis explicitly recorded as not from the sanctuary of Demeter and Kore.'),
('source.greek.ieleusis72.phi','I.Eleusis 72 — Decree honoring Hierokleides','ACADEMIC_EPIGRAPHIC_DATABASE',3,'Packard Humanities Institute','PHI Greek Inscriptions','lang.grc',NULL,'2026-08-27','https://epigraphy.packhum.org/text/346532','I.Eleusis 72','Database terms apply; locators and independent summaries only','Academic digital edition with object description and findspot qualification','Do not bulk reproduce edition text',0,'Ancient Greek edition metadata; project summary in English/Chinese','URL_SYNTAX_VALID','Decree honoring the hierophant Hierokleides; several white-marble stele fragments, not from the sanctuary.'),
('source.greek.sacred_way.efada','Ancient Iera Odos (Sacred Way)','OFFICIAL_ARCHAEOLOGICAL_SITE',3,'Ephorate of Antiquities of West Attica, Hellenic Ministry of Culture','Ephorate of Antiquities of West Attica','lang.en',NULL,'2026-08-27','https://www.efada.gr/en-us/Archaeological-Sites-Monuments/-Catalogue-of-Sites-Monuments/ancient-iera-odos-sacred-way-municipalities-of-egaleo-chaidari-aspropyrgos-elefsina','Iera Odos site catalogue','Official site terms apply; metadata and independent summaries only','Regional archaeological authority describing route segments and monuments','Do not package images',0,'Official English page','URL_SYNTAX_VALID','Records the route, Aphrodite sanctuary and Hadrianic bridge as distinct archaeological components.'),
('source.greek.eleusis_acropolis_exhibition2018','Eleusis: The Great Mysteries','MUSEUM_EXHIBITION_RECORD',3,'Acropolis Museum / Ephorate of Antiquities of West Attica','Acropolis Museum','lang.en','2018','2026-08-27','https://www.theacropolismuseum.gr/en/temporary-exhibitions/eleusis-great-mysteries','Temporary exhibition, 2018','Museum page terms apply; metadata and independent summaries only','Modern exhibition connecting Eleusis, the Athens Eleusinion, Sacred Way and objects','Do not treat exhibition design as ancient ritual evidence',0,'Official English museum page','URL_SYNTAX_VALID','Useful for network context; the reconstructed darkened Anaktoron in the exhibition remains modern interpretation.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('museum.nam.ninnion_tablet_a11036','Ninnion Tablet A11036','宁尼翁陶板 A11036','Νίννιον',NULL,'MUSEUM_OBJECT','civ.greek','region.mediterranean','Classical Greek, about fourth century BCE','雅典国家考古博物馆的陶制奉献板；登记馆藏、奉献语境与图像解释边界，不把图像当作秘仪全程记录。 / Clay votive tablet in the National Archaeological Museum; custody and dedication are registered without treating its imagery as a complete ritual record.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_MUSEUM_OBJECT","secrecy_guard":"ICONOGRAPHY_IS_NOT_COMPLETE_RITUAL_DISCLOSURE"}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z'),
('text.greek.ieleusis71','I.Eleusis 71','I.Eleusis 71 铭文','I.Eleusis 71','I.Eleusis 71','INSCRIPTION','civ.greek','region.mediterranean','ca. mid-fourth century BCE?','厄琉息斯人法令残片；PHI 明确标注并非出自得墨忒耳与科瑞圣区。 / Fragmentary decree of the Eleusinians, explicitly catalogued as not from the sanctuary.','PARTIAL','SOURCE_BACKED',1,'{"witness_role":"INSCRIPTION","findspot_scope":"ELEUSIS_NOT_SANCTUARY"}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z'),
('text.greek.ieleusis72','I.Eleusis 72','I.Eleusis 72 铭文','I.Eleusis 72','I.Eleusis 72','INSCRIPTION','civ.greek','region.mediterranean','Hellenistic or Roman-period catalogue context; edition date retained separately','厄琉息斯人纪念祭司 Hierokleides 的法令残片；不把城镇出土范围误写为圣区出土。 / Decree honoring the hierophant Hierokleides; Eleusis locality is not collapsed into sanctuary provenance.','PARTIAL','SOURCE_BACKED',1,'{"witness_role":"INSCRIPTION","findspot_scope":"ELEUSIS_NOT_SANCTUARY"}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z'),
('site.greece.sacred_way_aphrodite_daphne','Sanctuary of Aphrodite at Daphne','达夫尼阿佛洛狄忒圣所',NULL,NULL,'ARCHAEOLOGICAL_SITE','civ.greek','region.mediterranean','Classical to Roman use','圣道中段的露天阿佛洛狄忒圣所；与整条圣道和厄琉息斯圣区分开。 / Open-air Aphrodite sanctuary along the middle Sacred Way, distinct from the route and Eleusis sanctuary.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","route_component":true}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z'),
('site.greece.sacred_way_roman_bridge','Roman Bridge over the Eleusinian Cephissus','厄琉息斯基菲索斯河罗马桥',NULL,NULL,'ARCHAEOLOGICAL_SITE','civ.greek','region.mediterranean','Hadrianic period','圣道接近厄琉息斯入口处保存的罗马时期桥梁；代表路线的一个有年代层，不等于整条道路。 / Preserved Hadrianic bridge near Eleusis, one dated layer of the route rather than the whole road.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_ARCHAEOLOGICAL","route_component":true,"phase":"HADRIANIC"}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z'),
('concept.greek.eleusinian_relief_copy_network','Great Eleusinian Relief Copy Network','大厄琉息斯浮雕摹本网络',NULL,NULL,'CONCEPT','civ.greek','region.mediterranean','Classical original and later copies','用于连接原作与古代摹本的研究导航概念；成员器物不合并。 / Research navigation concept linking an original and ancient copies without merging objects.','PARTIAL','SOURCE_BACKED',1,'{"comparison_only":true,"identity_merge":false}','2026-08-27T10:00:00Z','2026-08-27T10:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.17.0 Eleusis network' FROM entities WHERE created_at='2026-08-27T10:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,'civ.greek','ELEUSINIAN_CONTEXT','SUPPORTED','Eleusis network expansion' FROM entities WHERE created_at='2026-08-27T10:00:00Z';

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0170.ninnion.en','museum.nam.ninnion_tablet_a11036','Ninnion Tablet','ninnion tablet','lang.en','Latin','PREFERRED',1,'source.greek.eleusinian_relief.nam126',NULL),
('name.v0170.ninnion.cat','museum.nam.ninnion_tablet_a11036','A11036','a11036','lang.en','Latin','CATALOGUE_LABEL',0,'source.greek.eleusinian_relief.nam126','National Archaeological Museum number.'),
('name.v0170.ieleusis71','text.greek.ieleusis71','I.Eleusis 71','i eleusis 71','lang.en','Latin','CATALOGUE_LABEL',1,'source.greek.ieleusis71.phi',NULL),
('name.v0170.ieleusis72','text.greek.ieleusis72','I.Eleusis 72','i eleusis 72','lang.en','Latin','CATALOGUE_LABEL',1,'source.greek.ieleusis72.phi',NULL),
('name.v0170.aphrodite.en','site.greece.sacred_way_aphrodite_daphne','Sanctuary of Aphrodite at Daphne','sanctuary aphrodite daphne','lang.en','Latin','PREFERRED',1,'source.greek.sacred_way.efada',NULL),
('name.v0170.bridge.en','site.greece.sacred_way_roman_bridge','Roman Bridge over the Eleusinian Cephissus','roman bridge eleusinian cephissus','lang.en','Latin','DESCRIPTIVE',1,'source.greek.sacred_way.efada',NULL),
('name.v0170.reliefnetwork.en','concept.greek.eleusinian_relief_copy_network','Great Eleusinian Relief Copy Network','great eleusinian relief copy network','lang.en','Latin','DESCRIPTIVE',1,'source.greek.eleusinian_relief.met141309','Modern research label.');

INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.nam.ninnion_tablet_a11036','National Archaeological Museum, Athens','A11036','Clay votive tablet','Dedicated to the sanctuary at Eleusis','Classical period; exact date expansion remains queued','Official museum page identifies Ninnion as dedicator; iconographic identifications beyond the page remain interpretive.');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.greek.ieleusis71','DECREE','lang.grc',NULL,NULL,'ca. mid-fourth century BCE?','Fragmentary marble stele','Stoichedon 27 in PHI record','Epigraphic collection context','I.Eleusis 71; IG II² 1185','Ancient text public domain; editions retain rights','Decree of the Eleusinians, explicitly not from the sanctuary.'),
('text.greek.ieleusis72','HONORIFIC_DECREE','lang.grc',NULL,NULL,'Edition date retained in PHI record','Several white-marble stele fragments','Fragmentary inscription','Epigraphic collection context','I.Eleusis 72','Ancient text public domain; editions retain rights','Decree honoring the hierophant Hierokleides; not from the sanctuary.');

INSERT OR IGNORE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,date_range,builders,architecture_summary,excavation_summary,major_finds_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.greece.sacred_way_aphrodite_daphne','OPEN_AIR_SANCTUARY',NULL,'Chaidari / Daphne','GR','Classical to Roman period',NULL,'Small temple, courtyard, altar and a four-sided building; natural rock niches held offerings','Official regional archaeological catalogue record','Inscriptions and offerings associated with Aphrodite',NULL,'REAL_ARCHAEOLOGICAL','SOURCE_BACKED'),
('site.greece.sacred_way_roman_bridge','BRIDGE',NULL,'Elefsina','GR','Hadrianic period','Roman-period builders','Bridge carrying a dated Sacred Way segment over the Eleusinian Cephissus','Official regional archaeological catalogue record','Preserved road-and-bridge fabric',NULL,'REAL_ARCHAEOLOGICAL','SOURCE_BACKED');

UPDATE place_profiles SET date_range='Late Geometric worship through Roman period and closure in 392 CE; prehistoric phases also excavated',architecture_summary='Successive sanctuary and Telesterion phases include Peisistratid, Periclean/Lykourgean and Roman monumental building programmes; phase boundaries must remain explicit',excavation_summary='Systematic excavations from 1882 onward; 1930s campaigns exposed Telesterion remains and a longer prehistoric-to-late-antique sequence' WHERE entity_id='site.greece.eleusis_telesterion';

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0170.ninnion_held','museum.nam.ninnion_tablet_a11036','HELD_BY_MUSEUM','institution.nam_athens',NULL,NULL,'The National Archaeological Museum in Athens holds the Ninnion Tablet as A11036.','eleusis.ninnion.custody','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Modern custody','current museum page',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.ninnion_dedication','museum.nam.ninnion_tablet_a11036','HAS_DEDICATION',NULL,'dedicated to the Eleusinian sanctuary by a woman named Ninnion','text','The museum catalogue identifies the object as a dedication to the same sanctuary by Ninnion.','eleusis.ninnion.dedication','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','Classical period','No complete ritual reconstruction follows from this dedication.','2026-08-27T10:00:00Z'),
('claim.v0170.ninnion_secrecy_limit','museum.nam.ninnion_tablet_a11036','ASSOCIATED_WITH','concept.greek.eleusinian_secrecy',NULL,NULL,'The tablet may inform iconographic study, but it is not treated as a complete disclosure of secret rites.','eleusis.ninnion.interpretive_limit','INTERPRETIVE',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project method','current','Evidence-limit rule.','2026-08-27T10:00:00Z'),
('claim.v0170.i71_eleusis','text.greek.ieleusis71','ASSOCIATED_WITH','site.greece.eleusis',NULL,NULL,'I.Eleusis 71 belongs to the Eleusis inscription corpus at the locality level.','eleusis.inscription.locality','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Eleusis','ca. mid-fourth century BCE?',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.i71_not_sanctuary','text.greek.ieleusis71','ASSOCIATED_WITH',NULL,'not from the sanctuary of Demeter and Kore','text','PHI explicitly records I.Eleusis 71 as not from the sanctuary.','eleusis.inscription.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','modern catalogue statement','Negative provenance is source-scoped.','2026-08-27T10:00:00Z'),
('claim.v0170.i72_eleusis','text.greek.ieleusis72','ASSOCIATED_WITH','site.greece.eleusis',NULL,NULL,'I.Eleusis 72 belongs to the Eleusis inscription corpus at the locality level.','eleusis.inscription.locality','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Eleusis','edition context',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.i72_hierokleides','text.greek.ieleusis72','ASSOCIATED_WITH',NULL,'decree honoring the hierophant Hierokleides','text','The PHI catalogue describes I.Eleusis 72 as a decree honoring the hierophant Hierokleides.','eleusis.inscription.content','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Eleusis','ancient decree',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.i72_not_sanctuary','text.greek.ieleusis72','ASSOCIATED_WITH',NULL,'not from the sanctuary of Demeter and Kore','text','PHI explicitly records I.Eleusis 72 as not from the sanctuary.','eleusis.inscription.findspot','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis','modern catalogue statement',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.aphrodite_part_way','site.greece.sacred_way_aphrodite_daphne','PART_OF','site.greece.sacred_way',NULL,NULL,'The Aphrodite sanctuary is a distinct monument along the Sacred Way.','eleusis.sacred_way.components','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Sacred Way','Classical to Roman',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.aphrodite_worship','deity.greek.aphrodite','WORSHIPPED_AT','site.greece.sacred_way_aphrodite_daphne',NULL,NULL,'Offerings and inscriptions identify worship of Aphrodite at the Daphne sanctuary.','eleusis.sacred_way.aphrodite','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Daphne sanctuary','Classical to Roman',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.bridge_part_way','site.greece.sacred_way_roman_bridge','PART_OF','site.greece.sacred_way',NULL,NULL,'The Roman bridge preserves one dated component of the Sacred Way near Eleusis.','eleusis.sacred_way.components','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Sacred Way','Hadrianic period',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.bridge_hadrianic','site.greece.sacred_way_roman_bridge','ASSOCIATED_WITH',NULL,'Hadrianic-period bridge about one kilometre east of the Eleusis sanctuary entrance','text','The official catalogue dates the preserved bridge to the Hadrianic age and locates it east of the sanctuary entrance.','eleusis.sacred_way.bridge_date','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Eleusis approach','Hadrianic period',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.telesterion_phases','site.greece.eleusis_telesterion','ASSOCIATED_WITH',NULL,'successive prehistoric, Archaic/Classical and Roman architectural phases','text','The official archaeological history presents the Telesterion and sanctuary through successive phases rather than one timeless building.','eleusis.telesterion.phases','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Eleusis','long duration','Exact plan-by-plan phase catalogue remains queued.','2026-08-27T10:00:00Z'),
('claim.v0170.reliefnetwork_original','concept.greek.eleusinian_relief_copy_network','HAS_MEMBER','museum.nam.great_eleusinian_relief_126',NULL,NULL,'The National Archaeological Museum relief is the original-side member of the registered copy network.','eleusis.relief.copy_network','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Museum objects','modern comparison',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.reliefnetwork_metcopy','concept.greek.eleusinian_relief_copy_network','HAS_MEMBER','museum.met.eleusinian_relief_14_130_9',NULL,NULL,'The Metropolitan Museum fragments are a Roman-copy member of the network.','eleusis.relief.copy_network','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Museum objects','Roman copy and modern study',NULL,'2026-08-27T10:00:00Z'),
('claim.v0170.reliefnetwork_no_merge','concept.greek.eleusinian_relief_copy_network','ASSOCIATED_WITH',NULL,'copy-network membership never merges the original and Roman fragments into one object','text','The copy network preserves object identity, provenance and catalogue number separately.','eleusis.relief.copy_network.method','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project method','current',NULL,'2026-08-27T10:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE
  WHEN c.id LIKE 'claim.v0170.ninnion_%' THEN 'source.greek.eleusinian_relief.nam126'
  WHEN c.id LIKE 'claim.v0170.i71_%' THEN 'source.greek.ieleusis71.phi'
  WHEN c.id LIKE 'claim.v0170.i72_%' THEN 'source.greek.ieleusis72.phi'
  WHEN c.id LIKE 'claim.v0170.aphrodite_%' OR c.id LIKE 'claim.v0170.bridge_%' THEN 'source.greek.sacred_way.efada'
  WHEN c.id='claim.v0170.telesterion_phases' THEN 'source.greek.eleusis.efada'
  WHEN c.id='claim.v0170.reliefnetwork_metcopy' THEN 'source.greek.eleusinian_relief.met141309'
  ELSE 'source.greek.eleusinian_relief.nam126' END,
 CASE WHEN c.id LIKE 'claim.v0170.i71_%' THEN 'I.Eleusis 71 metadata and findspot note'
      WHEN c.id LIKE 'claim.v0170.i72_%' THEN 'I.Eleusis 72 metadata and findspot note'
      ELSE 'Official object, site or museum record cited in claim notes' END,
 NULL,
 CASE WHEN c.knowledge_layer='TEXTUAL_WITNESS' THEN 'INSCRIPTION' WHEN c.knowledge_layer='ARCHAEOLOGICAL' THEN 'ARCHAEOLOGICAL' ELSE 'MODERN_SCHOLARSHIP' END,
 'SUPPORTS',c.confidence,'v0.17 source-located evidence; no restricted ritual content reproduced'
FROM claims c WHERE c.id LIKE 'claim.v0170.%';

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Continue corpus expansion with edition concordance and exact findspot; keep town-level and sanctuary-level provenance separate',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.v080.greek.eleusis_inscription_corpus';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Create plan-by-plan Telesterion phase records from excavation publications and conservation documentation',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.v080.greek.telesterion_phases';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add further dated road segments, cemeteries, shrines and geospatial coordinates from official records',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.v080.greek.sacred_way_monuments';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Expand iconographic readings only from museum catalogues and peer-reviewed studies; preserve secrecy limit',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.v080.greek.ninnion_tablet';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add more securely catalogued ancient copies, casts and provenance events without merging objects',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.v080.greek.eleusinian_relief_copy_network';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Continue public archaeology, inscription and object layers; do not infer restricted ritual content',updated_at='2026-08-27T10:00:00Z' WHERE id='queue.greek.v050.eleusis_layers';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES
('research.20260827.v0170_eleusis_network','2026-08-27T09:05:00Z','2026-08-27T10:00:00Z','Eleusis inscription locality boundaries, Ninnion Tablet, Telesterion phases, Sacred Way monuments and relief copy network','Use PHI, Greek archaeological authorities and museum records; preserve secrecy and object-identity limits','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Mystery content is not reconstructed.');
UPDATE project_metadata SET value='0.17.0-eleusis-network-20260827',updated_at='2026-08-27T10:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='24',updated_at='2026-08-27T10:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T10:00:00Z',updated_at='2026-08-27T10:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.17.0',24,'0.17.0-eleusis-network-20260827',NULL,'2026-08-27T10:00:00Z',NULL,'Eleusis network checkpoint: two additional inscription witnesses with findspot guards, Ninnion Tablet A11036, two dated Sacred Way monuments, Telesterion phase scope and an object-preserving relief copy network.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(24,'20260827_v0170_eleusis_network','2026-08-27T10:00:00Z');
COMMIT;
