BEGIN IMMEDIATE;

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.japan.korin_wind_thunder.tnm','Wind God and Thunder God by Ogata Kōrin','MUSEUM_CATALOGUE',3,'Tokyo National Museum','Tokyo National Museum','lang.en',NULL,'2026-08-27','https://www.tnm.jp/modules/r_collection/index.php?colid=A11189.1&controller=dtl&lang=en','A-11189-1','Museum page terms apply; metadata and independent summaries only','Official collection record for the eighteenth-century Kōrin screens','Do not package collection images',0,'Official English museum record','URL_SYNTAX_VALID','Important Cultural Property; Edo period, eighteenth century; color on gold-leafed paper.'),
('source.japan.korin_hoitsu.emuseum','Wind God and Thunder God / Summer and Autumn Grasses — e-Museum dossier','NATIONAL_DIGITAL_MUSEUM',3,'National Institutes for Cultural Heritage, Japan','e-Museum','lang.en',NULL,'2026-08-27','https://emuseum.nich.go.jp/detail?content_base_id=100321&content_part_id=001&content_pict_id=002&langId=en','e-Museum 100321','National digital museum terms apply; metadata and independent summaries only','Official object-history record for Kōrin front and Hōitsu reverse, later separated for conservation','Do not package images',0,'Official English digital museum record','URL_SYNTAX_VALID','Records that Kōrin copied Sōtatsu and Hōitsu painted the reverse; later conservation reformatted the two sides as separate screen pairs.'),
('source.japan.korin_wind_thunder.colbase','風神雷神図屏風 — ColBase A-11189-1','NATIONAL_COLLECTION_DATABASE',3,'National Institutes for Cultural Heritage, Japan','ColBase','lang.jpn',NULL,'2026-08-27','https://colbase.nich.go.jp/collection_items/tnm/A-11189-1','A-11189-1','Collection database terms apply; metadata and independent summaries only','National integrated collection record identifying Kōrin’s traced copy','Do not package images',0,'Japanese official collection record','URL_SYNTAX_VALID','Official Japanese record describes Kōrin’s work as a faithful traced copy; object identity remains separate from Sōtatsu’s screens.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('deity.japanese.karaijin','Karaijin','加雷神／地方雷神','Karaijin','Karaijin','DEITY','civ.japanese_shinto','region.east_asia','Regional/local shrine traditions','國學院资料列为地方神社所奉雷神名之一；本档与 Raijin 泛称及贺茂别雷大神分开。 / Name used for thunder kami at local shrines in the Kokugakuin overview; distinct from the generic Raijin dossier and Kamo Wakeikazuchi.','PARTIAL','SOURCE_BACKED',1,'{"identity_scope":"REGIONAL_THUNDER_KAMI_LABEL","merge_guard":["deity.japanese.raijin","deity.japanese.kamo_wakeikazuchi"]}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('text.japan.yamashiro_fudoki_kamo_fragment','Yamashiro Fudoki Kamo Fragment','《山城国风土记》贺茂残片','山城国風土記逸文','Yamashiro no kuni fudoki itsubun','TEXT','civ.japanese_shinto','region.east_asia','Ancient provincial record surviving only in later quotations','只登记可追踪的逸文见证，不虚构完整《山城国风土记》手稿。 / Fragment witness surviving through later quotation chains; no complete manuscript is reconstructed.','PARTIAL','SOURCE_BACKED',1,'{"witness_role":"QUOTED_FRAGMENT","complete_manuscript":false,"quotation_chain_pending":true}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('institution.japan.tokyo_national_museum','Tokyo National Museum','东京国立博物馆','東京国立博物館','Tokyo Kokuritsu Hakubutsukan','INSTITUTION','civ.japanese_shinto','region.east_asia','Modern museum','保存光琳《风神雷神图屏风》等日本文化财产的现代机构。 / Modern museum holding Kōrin’s Wind and Thunder God screens.','PARTIAL','SOURCE_BACKED',1,'{"institution_type":"MUSEUM"}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('historical.japan.ogata_korin','Ogata Kōrin','尾形光琳','尾形光琳','Ogata Kōrin','HISTORICAL_FIGURE','civ.japanese_shinto','region.east_asia','1658-1716','江户时代艺术家；本批仅登记其有馆藏证据的风神雷神屏风摹本。 / Edo-period artist, scoped here to the museum-documented Wind and Thunder God screens.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"HISTORICAL_PERSON"}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('museum.tnm.korin_wind_thunder_a11189_1','Wind God and Thunder God Screens by Ogata Kōrin A-11189-1','尾形光琳《风神雷神图屏风》A-11189-1','風神雷神図屏風',NULL,'MUSEUM_OBJECT','civ.japanese_shinto','region.east_asia','Edo period, eighteenth century','东京国立博物馆重要文化财产；与宗达原作保持为两件不同对象。 / Tokyo National Museum Important Cultural Property; a distinct object from Sōtatsu’s earlier screens.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_MUSEUM_OBJECT","copy_relation":"DOCUMENTED","not_same_object_as":"museum.japan.sotatsu_wind_thunder_screens"}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('historical.japan.sakai_hoitsu','Sakai Hōitsu','酒井抱一','酒井抱一','Sakai Hōitsu','HISTORICAL_FIGURE','civ.japanese_shinto','region.east_asia','1761-1828','江户时代艺术家；宗达与光琳作品接受史中的独立人物。 / Edo-period artist in the reception history of Sōtatsu and Kōrin.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"HISTORICAL_PERSON"}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('modern_work.japan.hoitsu_wind_thunder_version','Wind and Thunder God Screens attributed to Sakai Hōitsu — research record','酒井抱一《风神雷神图》版本研究档','風神雷神図屏風',NULL,'MODERN_WORK','civ.japanese_shinto','region.east_asia','Edo period, later reception of Sōtatsu','京都国立博物馆仅确认抱一亦作过版本；馆藏、编号与精确年代未核实前不补写。 / Research record for the Hōitsu version noted by Kyoto National Museum; custody, catalogue and exact date remain unasserted.','PARTIAL','SOURCE_BACKED',1,'{"object_status":"WORK_LEVEL_RECORD","catalogue_pending":true,"custody_pending":true}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z'),
('concept.japan.wind_thunder_screen_copy_network','Sōtatsu–Kōrin–Hōitsu Wind and Thunder Screen Network','宗达—光琳—抱一风雷屏风网络',NULL,NULL,'CONCEPT','civ.japanese_shinto','region.east_asia','Seventeenth to nineteenth century reception','连接三位艺术家相关版本的研究导航；成员的作者、馆藏和对象身份不合并。 / Research navigation linking related versions while preserving authorship, custody and object identity.','PARTIAL','SOURCE_BACKED',1,'{"comparison_only":true,"identity_merge":false}','2026-08-27T11:00:00Z','2026-08-27T11:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.18.0 Japanese thunder witnesses' FROM entities WHERE created_at='2026-08-27T11:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,'civ.japanese_shinto','JAPANESE_TRADITION_CONTEXT','SUPPORTED','v0.18 scoped association' FROM entities WHERE created_at='2026-08-27T11:00:00Z';

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0180.karaijin','deity.japanese.karaijin','Karaijin','karaijin','lang.jpn','Latin transliteration','PREFERRED',1,'source.japanese.raijin.kokugakuin','Regional label; no automatic identity merge.'),
('name.v0180.fragment.jp','text.japan.yamashiro_fudoki_kamo_fragment','山城国風土記逸文','山城国風土記逸文','lang.jpn','Japanese','ORIGINAL_TITLE',1,'source.japanese.kamo_genealogy.kokugakuin','Fragment, not a complete manuscript.'),
('name.v0180.tnm.en','institution.japan.tokyo_national_museum','Tokyo National Museum','tokyo national museum','lang.en','Latin','PREFERRED',1,'source.japan.korin_wind_thunder.tnm',NULL),
('name.v0180.korin.jp','historical.japan.ogata_korin','尾形光琳','尾形光琳','lang.jpn','Japanese','ORIGINAL',1,'source.japan.korin_wind_thunder.tnm',NULL),
('name.v0180.korinobject.jp','museum.tnm.korin_wind_thunder_a11189_1','風神雷神図屏風','風神雷神図屏風','lang.jpn','Japanese','ORIGINAL_TITLE',1,'source.japan.korin_wind_thunder.colbase','Catalogue A-11189-1.'),
('name.v0180.hoitsu.jp','historical.japan.sakai_hoitsu','酒井抱一','酒井抱一','lang.jpn','Japanese','ORIGINAL',1,'source.japan.korin_hoitsu.emuseum',NULL),
('name.v0180.hoitsuwork.jp','modern_work.japan.hoitsu_wind_thunder_version','風神雷神図屏風','風神雷神図屏風 抱一版','lang.jpn','Japanese','DESCRIPTIVE',1,'source.japanese.raijin_screen.kyohaku','Work-level label; exact object record queued.'),
('name.v0180.network.en','concept.japan.wind_thunder_screen_copy_network','Sōtatsu–Kōrin–Hōitsu Wind and Thunder Screen Network','sotatsu korin hoitsu wind thunder screen network','lang.en','Latin','DESCRIPTIVE',1,'source.japanese.raijin_screen.kyohaku','Modern research label.');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.japan.yamashiro_fudoki_kamo_fragment','QUOTED_FRAGMENT','lang.ojp',NULL,NULL,'Provincial gazetteer tradition; exact original date and transmission require edition audit','Later quotation witnesses','Fragment concerning Kamo genealogy','Quotation-chain repositories pending','Yamashiro no kuni fudoki itsubun','Ancient fragment public domain; modern editions retain rights','Fragmentary witness for Tamayorihime, the red arrow, Honoikazuchi of Otokuni and Kamo Wakeikazuchi.');

INSERT OR IGNORE INTO deity_profiles(entity_id,deity_class,pantheon_or_family,rank_or_status,domains_json,powers_json,limitations_json,appearance_json,symbols_json,cult_summary,final_fate_summary) VALUES
('deity.japanese.karaijin','Regional Japanese thunder kami','Local shrine traditions','Scoped regional dossier','["thunder","rain associations in some local traditions"]','[]','["not merged with generic Raijin","not merged with Kamo Wakeikazuchi","shrine-specific dossiers remain queued"]','{}','[]','Kokugakuin lists Karaijin among thunder kami enshrined in various localities; exact shrine contexts require separate authority records.',NULL);

INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.tnm.korin_wind_thunder_a11189_1','Tokyo National Museum','A-11189-1','Pair of folding screens; color on gold-leafed paper','Japan','Edo period, eighteenth century','Official TNM and ColBase records; separate from Sōtatsu original and Hōitsu research record.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0180.karaijin_regional','deity.japanese.karaijin','ASSOCIATED_WITH','deity.japanese.raijin',NULL,NULL,'Karaijin is registered under the broader thunder-kami research umbrella but remains a distinct regional dossier.','japan.thunder.identity_scope','INTERPRETIVE',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Japanese local shrine traditions','modern academic overview','Association does not mean identity.','2026-08-27T11:00:00Z'),
('claim.v0180.karaijin_distinct_kamo','deity.japanese.karaijin','ASSOCIATED_WITH',NULL,'must not be merged with Kamo Wakeikazuchi solely because both are thunder kami','text','Kokugakuin lists Karaijin and Kamo Wakeikazuchi as separate local shrine examples.','japan.thunder.identity_scope','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Japanese local shrine traditions','current identity audit','No IDENTIFIED_WITH edge is created.','2026-08-27T11:00:00Z'),
('claim.v0180.raijin_manifestations','deity.japanese.raijin','ASSOCIATED_WITH',NULL,'serpent or child manifestation motifs in some local traditions','text','The Kokugakuin overview notes serpent or child manifestation forms for thunder-god traditions.','japan.raijin.regional_motifs','SUPPORTED',0.92,'HIGH','VERIFIED','IN_TRADITION','RITUAL_PRACTICE','Regional Japanese traditions','unspecified local traditions','Not generalized to every shrine.','2026-08-27T11:00:00Z'),
('claim.v0180.raijin_rain','deity.japanese.raijin','ASSOCIATED_WITH',NULL,'rain production in some local traditions','text','The academic overview notes an association between thunder deities and rain production.','japan.raijin.regional_motifs','SUPPORTED',0.92,'HIGH','VERIFIED','IN_TRADITION','RITUAL_PRACTICE','Regional Japanese traditions','unspecified local traditions','Scope remains regional.','2026-08-27T11:00:00Z'),
('claim.v0180.fragment_mentions_tamayori','text.japan.yamashiro_fudoki_kamo_fragment','MENTIONS','deity.japanese.tamayorihime_kamo',NULL,NULL,'The fragmentary Kamo genealogy names Tamayorihime.','japan.kamo.fragment_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Kamo tradition','fragment witness',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.fragment_mentions_hono','text.japan.yamashiro_fudoki_kamo_fragment','MENTIONS','deity.japanese.honoikazuchi_otokuni',NULL,NULL,'The fragment identifies the red arrow as a transformation of Honoikazuchi worshipped in Otokuni District.','japan.kamo.fragment_witness','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Kamo tradition','fragment witness','Does not identify this deity with the Kojiki underworld thunder entity.','2026-08-27T11:00:00Z'),
('claim.v0180.fragment_mentions_wake','text.japan.yamashiro_fudoki_kamo_fragment','MENTIONS','deity.japanese.kamo_wakeikazuchi',NULL,NULL,'The fragment is a textual witness for the birth genealogy of Kamo Wakeikazuchi.','japan.kamo.fragment_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Kamo tradition','fragment witness',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.fragment_incomplete','text.japan.yamashiro_fudoki_kamo_fragment','ASSOCIATED_WITH',NULL,'survives as a fragmentary quotation tradition, not a complete manuscript','text','The project does not reconstruct a complete Yamashiro Fudoki from the surviving excerpt.','japan.kamo.fragment_status','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Transmission history','current audit',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.festival_chokusai807','festival.japan.kamo_aoi','ASSOCIATED_WITH',NULL,'became an imperial-court-supported chokusai in 807 according to shrine history','text','The official shrine history dates chokusai status to 807.','japan.kamo.festival_phases','SUPPORTED',0.98,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo living public practice','807','Shrine historical framing retained.','2026-08-27T11:00:00Z'),
('claim.v0180.festival_saio810','festival.japan.kamo_aoi','ASSOCIATED_WITH',NULL,'Saio princess-priestess custom began in 810 and ended in 1212 according to shrine history','text','The official shrine page gives a distinct historical Saio phase from 810 to 1212.','japan.kamo.festival_phases','SUPPORTED',0.97,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo living public practice','810-1212',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.festival_revival1953','festival.japan.kamo_aoi','ASSOCIATED_WITH',NULL,'grand imperial-messenger procession revived in 1953','text','The official shrine history records the postwar procession revival in 1953.','japan.kamo.festival_phases','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo living public practice','1953',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.festival_saiodai1956','festival.japan.kamo_aoi','ASSOCIATED_WITH',NULL,'modern Saiodai segment added in 1956','text','The official shrine history distinguishes the 1956 Saiodai addition from ancient Saio practice.','japan.kamo.festival_phases','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Kamigamo living public practice','1956-present','Prevents timeless-festival flattening.','2026-08-27T11:00:00Z'),
('claim.v0180.korin_created','museum.tnm.korin_wind_thunder_a11189_1','CREATED_BY','historical.japan.ogata_korin',NULL,NULL,'Tokyo National Museum attributes A-11189-1 to Ogata Kōrin.','japan.wind_thunder.korin_object','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Edo painting','eighteenth century',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.korin_held','museum.tnm.korin_wind_thunder_a11189_1','HELD_BY_MUSEUM','institution.japan.tokyo_national_museum',NULL,NULL,'Tokyo National Museum holds the Kōrin screens under A-11189-1.','japan.wind_thunder.korin_object','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Modern custody','current catalogue',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.korin_depicts_raijin','museum.tnm.korin_wind_thunder_a11189_1','DEPICTS','deity.japanese.raijin',NULL,NULL,'The Kōrin screens depict the Thunder God.','japan.wind_thunder.korin_iconography','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Edo painting','eighteenth century','Visual reception, not ancient textual fact.','2026-08-27T11:00:00Z'),
('claim.v0180.korin_depicts_fujin','museum.tnm.korin_wind_thunder_a11189_1','DEPICTS','deity.japanese.fujin',NULL,NULL,'The Kōrin screens depict the Wind God.','japan.wind_thunder.korin_iconography','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Edo painting','eighteenth century',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.korin_copy_sotatsu','museum.tnm.korin_wind_thunder_a11189_1','LATER_COPY_OF','museum.japan.sotatsu_wind_thunder_screens',NULL,NULL,'Official Japanese collection records identify Kōrin’s screens as a traced copy of Sōtatsu’s composition.','japan.wind_thunder.copy_network','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Rinpa reception','eighteenth century','Objects remain distinct.','2026-08-27T11:00:00Z'),
('claim.v0180.hoitsu_created','modern_work.japan.hoitsu_wind_thunder_version','CREATED_BY','historical.japan.sakai_hoitsu',NULL,NULL,'Kyoto National Museum notes a later Hōitsu version in the reception history of Sōtatsu’s screens.','japan.wind_thunder.copy_network','SUPPORTED',0.90,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Rinpa reception','later Edo period','Exact object catalogue remains queued.','2026-08-27T11:00:00Z'),
('claim.v0180.hoitsu_copy_sotatsu','modern_work.japan.hoitsu_wind_thunder_version','LATER_COPY_OF','museum.japan.sotatsu_wind_thunder_screens',NULL,NULL,'The registered Hōitsu work-level record represents a later replication of Sōtatsu’s composition.','japan.wind_thunder.copy_network','SUPPORTED',0.88,'MEDIUM','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Rinpa reception','later Edo period','Work-level, not fully catalogued object-level relation.','2026-08-27T11:00:00Z'),
('claim.v0180.network_sotatsu','concept.japan.wind_thunder_screen_copy_network','HAS_MEMBER','museum.japan.sotatsu_wind_thunder_screens',NULL,NULL,'The Sōtatsu screens are the earlier member of the registered network.','japan.wind_thunder.copy_network','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.network_korin','concept.japan.wind_thunder_screen_copy_network','HAS_MEMBER','museum.tnm.korin_wind_thunder_a11189_1',NULL,NULL,'The Kōrin screens are a separately catalogued member of the network.','japan.wind_thunder.copy_network','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern',NULL,'2026-08-27T11:00:00Z'),
('claim.v0180.network_hoitsu','concept.japan.wind_thunder_screen_copy_network','HAS_MEMBER','modern_work.japan.hoitsu_wind_thunder_version',NULL,NULL,'The Hōitsu work-level record is a distinct later member of the network.','japan.wind_thunder.copy_network','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern','Custody and catalogue pending.','2026-08-27T11:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0180.karaijin_%' OR c.id LIKE 'claim.v0180.raijin_%' THEN 'source.japanese.raijin.kokugakuin'
      WHEN c.id LIKE 'claim.v0180.fragment_%' THEN 'source.japanese.kamo_genealogy.kokugakuin'
      WHEN c.id LIKE 'claim.v0180.festival_%' THEN 'source.japanese.kamo_festival.official'
      WHEN c.id IN ('claim.v0180.korin_copy_sotatsu') THEN 'source.japan.korin_wind_thunder.colbase'
      WHEN c.id LIKE 'claim.v0180.korin_%' THEN 'source.japan.korin_wind_thunder.tnm'
      ELSE 'source.japanese.raijin_screen.kyohaku' END,
 'Authority record and scoped summary',NULL,
 CASE WHEN c.knowledge_layer='TEXTUAL_WITNESS' THEN 'MANUSCRIPT' WHEN c.knowledge_layer='RITUAL_PRACTICE' THEN 'OFFICIAL_SITE' ELSE 'MODERN_SCHOLARSHIP' END,
 'SUPPORTS',c.confidence,'v0.18 evidence; modern image reception and living public practice remain distinct'
FROM claims c WHERE c.id LIKE 'claim.v0180.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0180.honoikazuchi_witness_scope','deity.japanese.honoikazuchi_otokuni','japan.honoikazuchi.identity','claim.v0100.hono_parent_kamo','claim.v0180.fragment_mentions_hono','IDENTITY_SCOPE','OPEN','The Otokuni Honoikazuchi is securely attached to the Kamo fragment, but name similarity does not establish identity with the Kojiki underworld thunder being.','Retain separate entities and compare original-language witnesses, cult locations and transmission histories.'),
('conflict.v0180.hoitsu_object_gap','modern_work.japan.hoitsu_wind_thunder_version','japan.wind_thunder.hoitsu_catalogue','claim.v0180.hoitsu_created','claim.v0180.network_hoitsu','CATALOGUE_GAP','OPEN','Museum scholarship confirms a Hōitsu version, while an exact object-level holding institution and catalogue number are not yet attached.','Replace the work-level record with or link it to a museum object only after an official catalogue match.');

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add shrine-specific Karaijin records and local names without merging them into generic Raijin',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v060.japanese.raijin_regional';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add edition, quotation source and transmission chain for each Yamashiro Fudoki fragment witness',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v0100.japanese.kamo_fragment_witnesses';
UPDATE collection_queue SET status='CONFLICT',attempts=attempts+1,next_action='Compare Kojiki text, Otokuni shrine evidence and philology; preserve separate identities',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v0100.japanese.honoikazuchi_identity';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add primary court records and cancellation/revival episodes with exact dates',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v0100.japanese.kamo_festival_history';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Match Hōitsu and later versions to official museum objects; add conservation and front/back separation events',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v0100.japanese.sotatsu_copy_network';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Register shrine-specific Karaijin dossiers from shrine, local-history and academic sources',updated_at='2026-08-27T11:00:00Z' WHERE id='queue.v0100.japanese.karaijin_local';

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0180_japanese_thunder_witnesses','2026-08-27T10:05:00Z','2026-08-27T11:00:00Z','Karaijin scope, Kamo fragment witness, festival phases and Sōtatsu-Kōrin-Hōitsu visual reception','Use Kokugakuin, shrine records and national museum catalogues; keep deity identity, fragment transmission, living practice and art reception separate','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Expandable staged baseline only. Shrine-specific Karaijin and exact Hōitsu object catalogue remain queued.');
UPDATE project_metadata SET value='0.18.0-japanese-thunder-witnesses-20260827',updated_at='2026-08-27T11:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='25',updated_at='2026-08-27T11:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T11:00:00Z',updated_at='2026-08-27T11:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.18.0',25,'0.18.0-japanese-thunder-witnesses-20260827',NULL,'2026-08-27T11:00:00Z',NULL,'Japanese thunder witness checkpoint: distinct Karaijin dossier, Yamashiro Fudoki Kamo fragment, dated festival phases, Kōrin A-11189-1 and a non-merging Sōtatsu-Kōrin-Hōitsu reception network.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(25,'20260827_v0180_japanese_thunder_witnesses','2026-08-27T11:00:00Z');
COMMIT;
