BEGIN IMMEDIATE;

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.norse.uppsala_edda.dg11','Uppsala Edda — DG 11 4to','MANUSCRIPT_CATALOG_AND_EDITION',1,'Uppsala University Library / Viking Society for Northern Research','Heimir Pálsson, ed.','lang.non','2012','2026-08-27','https://vsnr.org/editions/the-uppsala-edda-dg-11-4to/','DG 11 4to','Catalogue metadata and edition terms apply','Independent early witness of Snorri’s Edda','Do not package manuscript images',0,'Old Norse edition with scholarly apparatus','URL_SYNTAX_VALID','Probably the earliest surviving manuscript of Snorri’s Edda; its shorter version must not be silently harmonized with other manuscripts.'),
('source.norse.codex_wormianus.am242','AM 242 fol. — Codex Wormianus','MANUSCRIPT_CATALOG_AND_FACSIMILE',1,'The Arnamagnæan Collection, University of Copenhagen / Árni Magnússon Institute','Handrit.is','lang.non',NULL,'2026-08-27','https://handrit.is/manuscript/view/en/AM02-0242','AM 242 fol.','Institutional catalogue terms apply','Official manuscript catalogue','Do not package manuscript images',0,'Catalogue and facsimile metadata','URL_SYNTAX_VALID','Fourteenth-century Snorra Edda witness; registered for future reading-level collation.'),
('source.norse.uppsala_manuscripta.dg11','Uppsala University Library DG 11 — Manuscripta catalogue','NATIONAL_MANUSCRIPT_CATALOGUE',2,'Uppsala University Library','Manuscripta','lang.non',NULL,'2026-08-27','https://www.manuscripta.se/ms/101032','DG 11','Catalogue terms apply','Codicological description','Metadata reuse only',0,'Catalogue metadata','URL_SYNTAX_VALID','Catalogues the Uppsala Edda as an Icelandic parchment manuscript from around 1300.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('deity.norse.hoenir','Hœnir','赫尼尔','Hœnir','Hœnir','DEITY','civ.norse','region.northern_europe','Old Norse poetic tradition','《女巫的预言》人类起源三神见证中的独立神祇；不与 Vili 自动等同。 / A distinct deity in the Völuspá human-origin triad; not automatically identified with Vili.','PARTIAL','SOURCE_BACKED',1,'{"merge_guard":["deity.norse.vili"],"witness_scope":"VOLUSPA_17_18"}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('deity.norse.lodurr','Lóðurr','洛杜尔','Lóðurr','Lóðurr','DEITY','civ.norse','region.northern_europe','Old Norse poetic tradition','《女巫的预言》人类起源三神见证中的独立神祇；与 Loki 或 Vé 的同一说仅作待审研究问题。 / Distinct deity in Völuspá; proposed identities with Loki or Vé remain unasserted research questions.','PARTIAL','SOURCE_BACKED',1,'{"merge_guard":["deity.norse.ve","deity.norse.loki"],"witness_scope":"VOLUSPA_17_18"}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('person.norse.ask','Ask','阿斯克','Askr','Askr','PERSON','civ.norse','region.northern_europe','Old Norse mythic narrative','古诺斯人类起源叙事中的男性人物，按具体文本见证建档。 / Male figure in Old Norse human-origin narratives, recorded at witness level.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"MYTHIC_PERSON","pair":"person.norse.embla"}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('person.norse.embla','Embla','恩布拉','Embla','Embla','PERSON','civ.norse','region.northern_europe','Old Norse mythic narrative','古诺斯人类起源叙事中的女性人物，按具体文本见证建档。 / Female figure in Old Norse human-origin narratives, recorded at witness level.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"MYTHIC_PERSON","pair":"person.norse.ask"}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('text.norse.voluspa.st17_18','Völuspá stanzas 17–18 witness','《女巫的预言》第17–18节见证','Völuspá 17–18','Völuspá 17–18','TEXT','civ.norse','region.northern_europe','Medieval manuscript witness of an older poetic tradition','独立登记 Óðinn–Hœnir–Lóðurr 与 Ask–Embla 段落，不把它改写成散文埃达三神。 / Witness record for the Óðinn–Hœnir–Lóðurr and Ask–Embla passage.','PARTIAL','SOURCE_BACKED',1,'{"witness":"Codex Regius electronic edition","stanzas":"17-18","harmonize_with_prose_edda":false}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('text.norse.gylfaginning.ch8_9','Gylfaginning chapters 8–9 witness','《欺骗古鲁菲》第8–9章见证','Gylfaginning 8–9','Gylfaginning 8–9','TEXT','civ.norse','region.northern_europe','Thirteenth-century composition in fourteenth-century manuscripts','登记 Borr 之子 Óðinn–Vili–Vé 的宇宙与人类起源叙事；与《女巫的预言》三神并列而非合并。 / Witness for the sons-of-Borr creation narrative.','PARTIAL','SOURCE_BACKED',1,'{"edition":"Faulkes 2005","chapters":"8-9","harmonize_with_voluspa":false}','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.19.0 Norse witness graph' FROM entities WHERE created_at='2026-08-27T12:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,'civ.norse','OLD_NORSE_WITNESS_CONTEXT','SUPPORTED','Witness-scoped association' FROM entities WHERE created_at='2026-08-27T12:00:00Z';

INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0190.hoenir','deity.norse.hoenir','Hœnir','hoenir','lang.non','Latin','ORIGINAL',1,'source.norse.poetic_edda.gks2365','Völuspá witness name.'),
('name.v0190.lodurr','deity.norse.lodurr','Lóðurr','lodurr','lang.non','Latin','ORIGINAL',1,'source.norse.poetic_edda.gks2365','Völuspá witness name.'),
('name.v0190.ask','person.norse.ask','Askr','askr','lang.non','Latin','ORIGINAL',1,'source.norse.poetic_edda.gks2365',NULL),
('name.v0190.embla','person.norse.embla','Embla','embla','lang.non','Latin','ORIGINAL',1,'source.norse.poetic_edda.gks2365',NULL),
('name.v0190.voluspa','text.norse.voluspa.st17_18','Völuspá 17–18','voluspa 17 18','lang.non','Latin','DESCRIPTIVE',1,'source.norse.poetic_edda.gks2365',NULL),
('name.v0190.gylf','text.norse.gylfaginning.ch8_9','Gylfaginning 8–9','gylfaginning 8 9','lang.non','Latin','DESCRIPTIVE',1,'source.norse.gylfaginning.vsnr2005',NULL);

INSERT OR IGNORE INTO deity_profiles(entity_id,deity_class,pantheon_or_family,rank_or_status,domains_json,powers_json,limitations_json,appearance_json,symbols_json,cult_summary,final_fate_summary) VALUES
('deity.norse.hoenir','Æsir-context deity','Old Norse poetic tradition','Völuspá creation-triad member','["human origins in Völuspá"]','[]','["not automatically Vili","claims remain witness-scoped"]','{}','[]',NULL,NULL),
('deity.norse.lodurr','Poetic-tradition deity','Old Norse poetic tradition','Völuspá creation-triad member','["human origins in Völuspá"]','[]','["not automatically Vé","not automatically Loki"]','{}','[]',NULL,NULL);

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,attributed_author,compiler,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.norse.voluspa.st17_18','POETIC_PASSAGE_WITNESS','lang.non',NULL,NULL,'Composition date debated; medieval manuscript witness','Codex Regius GKS 2365 4to','Stanzas 17–18','Árni Magnússon Institute / electronic edition','GKS 2365 4to','Medieval text public domain; edition terms apply','Three deities encounter Ask and Embla and grant qualities in the poem.'),
('text.norse.gylfaginning.ch8_9','PROSE_PASSAGE_WITNESS','lang.non','Snorri Sturluson',NULL,'Thirteenth century','Principal fourteenth-century manuscripts','Chapters 8–9 in Faulkes edition','Multiple repositories','GKS 2367 4to; DG 11 4to; AM 242 fol.','Medieval text public domain; edition terms apply','Sons-of-Borr creation account; manuscript/version comparison remains open.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0190.voluspa_triad','text.norse.voluspa.st17_18','PRESENTS_TRIAD',NULL,'Óðinn–Hœnir–Lóðurr','text','Völuspá 17–18 presents Óðinn, Hœnir and Lóðurr in the Ask–Embla episode.','norse.creation.triad','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá manuscript tradition','stanzas 17–18','Do not substitute Vili or Vé.','2026-08-27T12:00:00Z'),
('claim.v0190.gylf_triad','text.norse.gylfaginning.ch8_9','PRESENTS_TRIAD',NULL,'Óðinn–Vili–Vé, the sons of Borr','text','Gylfaginning identifies the sons of Borr as Óðinn, Vili and Vé in its creation sequence.','norse.creation.triad','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Prose Edda manuscript tradition','chapters 8–9','Do not replace with Hœnir or Lóðurr.','2026-08-27T12:00:00Z'),
('claim.v0190.voluspa_odin','text.norse.voluspa.st17_18','MENTIONS','deity.norse.odin',NULL,NULL,'The passage names Óðinn.','norse.creation.voluspa','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá','17–18',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.voluspa_hoenir','text.norse.voluspa.st17_18','MENTIONS','deity.norse.hoenir',NULL,NULL,'The passage names Hœnir.','norse.creation.voluspa','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá','17–18',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.voluspa_lodurr','text.norse.voluspa.st17_18','MENTIONS','deity.norse.lodurr',NULL,NULL,'The passage names Lóðurr.','norse.creation.voluspa','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá','17–18',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.voluspa_ask','text.norse.voluspa.st17_18','MENTIONS','person.norse.ask',NULL,NULL,'The passage names Ask.','norse.creation.voluspa','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá','17–18',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.voluspa_embla','text.norse.voluspa.st17_18','MENTIONS','person.norse.embla',NULL,NULL,'The passage names Embla.','norse.creation.voluspa','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Völuspá','17–18',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.gylf_odin','text.norse.gylfaginning.ch8_9','MENTIONS','deity.norse.odin',NULL,NULL,'The prose sequence names Óðinn among Borr’s sons.','norse.creation.gylf','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Gylfaginning','8–9',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.gylf_vili','text.norse.gylfaginning.ch8_9','MENTIONS','deity.norse.vili',NULL,NULL,'The prose sequence names Vili among Borr’s sons.','norse.creation.gylf','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Gylfaginning','8–9',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.gylf_ve','text.norse.gylfaginning.ch8_9','MENTIONS','deity.norse.ve',NULL,NULL,'The prose sequence names Vé among Borr’s sons.','norse.creation.gylf','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Gylfaginning','8–9',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.gylf_ask','text.norse.gylfaginning.ch8_9','MENTIONS','person.norse.ask',NULL,NULL,'The prose human-origin sequence identifies Askr.','norse.creation.gylf','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Gylfaginning','chapter 9',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.gylf_embla','text.norse.gylfaginning.ch8_9','MENTIONS','person.norse.embla',NULL,NULL,'The prose human-origin sequence identifies Embla.','norse.creation.gylf','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Gylfaginning','chapter 9',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.skald_meili','text.norse.skaldskaparmal','MENTIONS','deity.norse.meili',NULL,NULL,'Skáldskaparmál preserves Meili in Thor-kenning material.','norse.thor.genealogy.witnesses','SUPPORTED',0.96,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Prose Edda','Thor kennings','Supports a direct textual connection; broader sibling inference remains scoped.','2026-08-27T12:00:00Z'),
('claim.v0190.skald_brokkr','text.norse.skaldskaparmal','MENTIONS','being.norse.brokkr',NULL,NULL,'The treasure-forging narrative names Brokkr.','norse.smith.name_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Prose Edda','Skáldskaparmál treasure narrative',NULL,'2026-08-27T12:00:00Z'),
('claim.v0190.eitri_reading','being.norse.eitri','NAME_WITNESS_FOR',NULL,'Brokkr’s smith-brother in the normalized Skáldskaparmál edition','text','Eitri is retained as the normalized-edition name for Brokkr’s smith-brother.','norse.sindri_eitri.name','SUPPORTED',0.90,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Skáldskaparmál edition','Faulkes edition','Must be checked against each principal manuscript.','2026-08-27T12:00:00Z'),
('claim.v0190.sindri_reading','being.norse.sindri','NAME_WITNESS_FOR',NULL,'a manuscript/variant name associated with Brokkr’s smith-brother','text','Sindri is preserved as a separate record for the manuscript-name problem.','norse.sindri_eitri.name','UNRESOLVED',0.70,'MEDIUM','PROVISIONAL','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Snorra Edda manuscript tradition','principal witnesses pending line collation','No IDENTIFIED_WITH edge is created.','2026-08-27T12:00:00Z'),
('claim.v0190.manuscript_variance','text.norse.prose_edda','ATTESTED_IN',NULL,'GKS 2367 4to, DG 11 4to and AM 242 fol. preserve materially distinct witnesses','text','The Prose Edda is represented by distinct medieval manuscripts that require witness-level comparison.','norse.prose_edda.manuscripts','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Manuscript history','fourteenth century','Do not flatten variant readings into one timeless text.','2026-08-27T12:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0190.voluspa_%' THEN 'source.norse.poetic_edda.gks2365'
      WHEN c.id LIKE 'claim.v0190.gylf_%' THEN 'source.norse.gylfaginning.vsnr2005'
      WHEN c.id IN ('claim.v0190.manuscript_variance') THEN 'source.norse.uppsala_edda.dg11'
      ELSE 'source.norse.skaldskaparmal.vsnr1998' END,
 CASE WHEN c.id LIKE 'claim.v0190.voluspa_%' THEN 'Völuspá 17–18' WHEN c.id LIKE 'claim.v0190.gylf_%' THEN 'Gylfaginning 8–9' ELSE 'Skáldskaparmál edition and notes' END,
 'MEDIEVAL_TEXT','SUPPORTS',c.confidence,'v0.19 witness-scoped evidence'
FROM claims c WHERE c.id LIKE 'claim.v0190.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0190.creation_triads','text.norse.voluspa.st17_18','norse.creation.triad','claim.v0190.voluspa_triad','claim.v0190.gylf_triad','TEXTUAL_VARIANT','OPEN','Völuspá and Gylfaginning present different named creation triads.','Preserve both witness claims; do not equate Hœnir with Vili or Lóðurr with Vé without separate evidence.'),
('conflict.v0190.sindri_eitri','being.norse.eitri','norse.sindri_eitri.name','claim.v0190.eitri_reading','claim.v0190.sindri_reading','MANUSCRIPT_NAME_VARIANT','OPEN','Eitri and Sindri participate in a manuscript/edition naming problem for Brokkr’s smith-brother.','Keep two entities until readings in GKS 2367, DG 11 and AM 242 are collated folio by folio.');

UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add exact skaldic stanza locations for each Thor genealogy edge; separate direct naming from shared-parent inference',updated_at='2026-08-27T12:00:00Z' WHERE id='queue.v060.norse.thor_genealogy_variants';
UPDATE collection_queue SET status='CONFLICT',attempts=attempts+1,next_action='Collate the Brokkr smith-brother reading in GKS 2367, DG 11 and AM 242; keep Eitri and Sindri separate',updated_at='2026-08-27T12:00:00Z' WHERE id IN ('queue.norse.sindri_eitri_identity','queue.norse.brokkr_eitri');
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add manuscript-specific gift wording and later interpretation history without equating the two triads',updated_at='2026-08-27T12:00:00Z' WHERE id='queue.norse.creation_triad_variants';

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0190.norse.voluspa_gifts','Gift vocabulary in Völuspá 17–18 across manuscripts','voluspa gifts manuscript variants','TEXT','civ.norse','text.norse.voluspa.st17_18','claim.v0190.voluspa_triad','source.norse.poetic_edda.gks2365','Gift terms and their allocation vary in translation and interpretation.',93,'SOURCE_FOUND',0,'Collate Old Norse readings and translation choices without converting poetic qualities into fixed domains','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z'),
('queue.v0190.norse.prose_edda_manuscripts','Prose Edda principal-manuscript witness alignment','prose edda manuscript alignment','MANUSCRIPT','civ.norse','text.norse.prose_edda','claim.v0190.manuscript_variance','source.norse.uppsala_edda.dg11','Three principal witnesses registered; passage-level alignment remains open.',96,'SOURCE_FOUND',0,'Create folio-level witness nodes for GKS 2367, DG 11 and AM 242','2026-08-27T12:00:00Z','2026-08-27T12:00:00Z');

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0190_norse_witness_graph','2026-08-27T11:05:00Z','2026-08-27T12:00:00Z','Norse creation triads, Thor-Meili witness and Eitri-Sindri manuscript-name conflict','Use university editions and manuscript catalogues; preserve named witnesses and unresolved identity separately','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Staged baseline; folio-level smith-name collation remains queued.');
UPDATE project_metadata SET value='0.19.0-norse-witness-graph-20260827',updated_at='2026-08-27T12:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='26',updated_at='2026-08-27T12:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T12:00:00Z',updated_at='2026-08-27T12:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.19.0',26,'0.19.0-norse-witness-graph-20260827',NULL,'2026-08-27T12:00:00Z',NULL,'Norse witness graph: distinct Völuspá and Gylfaginning creation triads, Ask and Embla witness nodes, Thor-Meili textual support and open Eitri-Sindri manuscript-name conflict.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(26,'20260827_v0190_norse_witness_graph','2026-08-27T12:00:00Z');
COMMIT;
