BEGIN IMMEDIATE;

INSERT OR IGNORE INTO regions(id,canonical_name,name_zh,parent_id,region_type,notes) VALUES
('region.mesopotamia','Mesopotamia','美索不达米亚','region.west_asia','HISTORICAL_REGION','Historical riverine region; not a modern-state equivalence.'),
('region.levant','Levant','黎凡特','region.west_asia','HISTORICAL_REGION','Broad historical-geographic research region; individual sites remain distinct.');

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.mesopotamia.inanna_ishtar.oracc','Inana/Ištar (goddess)','SPECIALIST_REFERENCE',3,'ORACC / University of Pennsylvania','Ancient Mesopotamian Gods and Goddesses project','lang.en',NULL,'2026-08-27','https://oracc.museum.upenn.edu/amgg/listofdeities/inanaitar/','Academic project terms apply','Diachronic specialist overview linking Sumerian Inana and Akkadian Ištar','Metadata and independent summaries only',0,'English academic overview with original names','URL_SYNTAX_VALID','Used for historically scoped identification; Sumerian and Akkadian corpora remain distinguishable.'),
('source.mesopotamia.anzu_ninurta.oracc','Ninurta, god of victory — Anzu narrative','SCHOLARLY_DIGITAL_EXHIBITION',3,'ORACC / University of Pennsylvania','Nimrud: Materialities of Assyrian Knowledge Production','lang.en','2019','2026-08-27','https://oracc.museum.upenn.edu/nimrud/ancientkalhu/thepeople/ninurta/','Academic project terms apply','Public scholarly synopsis of the Akkadian Anzu narrative','Metadata and independent summaries only',0,'English scholarly synopsis','URL_SYNTAX_VALID','Synopsis states that Anzu steals the Tablet of Destinies and Ninurta overcomes him.'),
('source.mesopotamia.anzu_object.oracc','Anzu the monstrous lion-eagle','SCHOLARLY_DIGITAL_EXHIBITION',3,'ORACC / University of Pennsylvania','Nimrud: Lives of Objects','lang.en','2019','2026-08-27','https://oracc.museum.upenn.edu/nimrud/livesofobjects/anzu/index.html','Academic project terms apply','Object-history and myth synopsis','Metadata and independent summaries only',0,'English scholarly synopsis','URL_SYNTAX_VALID','Separates the mythic creature, text and Tablet of Destinies concept.'),
('source.ugaritic.baal_corpus_ktu15_16.goettingen','Baˁlu Epic KTU 1.1–1.6 — corpus and tablet concordance','SCHOLARLY_PROJECT',2,'Göttingen Academy of Sciences and Humanities / Göttingen University','Edition des ugaritischen poetischen Textkorpus',NULL,NULL,'2026-08-27','https://eupt.uni-goettingen.de/Korpus.html','Academic project terms apply','Current scholarly corpus overview and tablet concordance','Metadata and independent summaries only',0,'German academic synopsis; editions forthcoming','URL_SYNTAX_VALID','Registers KTU 1.5 as AO 16.641+16.642 and KTU 1.6 as AO 16.636; project notes full editions forthcoming.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('concept.mesopotamia.inanna_ishtar_identification','Inana–Ištar Historical Identification','伊南娜—伊什塔尔历史性对应',NULL,NULL,'CONCEPT','civ.akkadian','region.mesopotamia','Third to first millennia BCE, varying by corpus','研究导航：记录跨苏美尔语与阿卡德语传统的历史性对应，同时保留两个神名、语言与文本语料。 / Research node for historical identification across Sumerian and Akkadian corpora without collapsing the records.','PARTIAL','SOURCE_BACKED',1,'{"identity_relation":"HISTORICALLY_SCOPED","merge_entities":false,"languages":["Sumerian","Akkadian"]}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('deity.ugaritic.dagan','Dagan in Ugaritic texts','乌加里特文本中的达贡／达甘','Dagnu','Dagnu','DEITY','civ.ugaritic','region.levant','Late Bronze Age Ugarit','只按乌加里特文本中的神名与巴力亲属称谓建档，不与其他时期地方达贡传统粗暴合并。 / Witness-scoped Ugaritic Dagan dossier.','PARTIAL','SOURCE_BACKED',1,'{"regional_scope":"UGARITIC_TEXTS","merge_guard":"other Dagan/Dagon regional dossiers"}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('text.ugaritic.baal_cycle.ktu1_5','Baal Cycle tablet KTU 1.5','巴力组诗泥板 KTU 1.5','KTU 1.5','KTU 1.5','TABLET','civ.ugaritic','region.levant','Late thirteenth century BCE manuscript context','巴力—穆特阶段的独立泥板见证，馆藏组合 AO 16.641 + 16.642。 / Separate tablet witness for the Baal–Mot sequence.','PARTIAL','SOURCE_BACKED',1,'{"museum_numbers":["AO 16.641","AO 16.642"],"edition_status":"FORTHCOMING_2027_2029"}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('text.ugaritic.baal_cycle.ktu1_6','Baal Cycle tablet KTU 1.6','巴力组诗泥板 KTU 1.6','KTU 1.6','KTU 1.6','TABLET','civ.ugaritic','region.levant','Late thirteenth century BCE manuscript context','巴力—穆特阶段的独立泥板见证，馆藏号 AO 16.636。 / Separate tablet witness for the later Baal–Mot sequence.','PARTIAL','SOURCE_BACKED',1,'{"museum_numbers":["AO 16.636"],"edition_status":"FORTHCOMING_2027_2029"}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('event.ugaritic.baal_mot_ktu15_16','Baal and Mot sequence in KTU 1.5–1.6','巴力与穆特事件序列（KTU 1.5–1.6）',NULL,NULL,'EVENT','civ.ugaritic','region.levant','Late Bronze Age narrative witnessed by KTU 1.5–1.6','把争执、死亡／冥界与返回阶段登记为残缺文本序列，不简化为“巴力永久杀死死亡”。 / Fragmentary narrative sequence, not a timeless claim that Death was permanently destroyed.','PARTIAL','SOURCE_BACKED',1,'{"witnesses":["KTU 1.5","KTU 1.6"],"permanent_death_claim":false}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('creature.akkadian.anzu','Anzu of the Akkadian myth','阿卡德《安祖神话》中的安祖','Anzû','Anzû','MONSTER','civ.akkadian','region.mesopotamia','Second-to-first millennium BCE Akkadian witnesses','与《安祖神话》文本实体分开：这是叙事角色，不是泥板或现代图像。 / Narrative creature kept separate from the Anzu text and material representations.','PARTIAL','SOURCE_BACKED',1,'{"entity_layer":"MYTHIC_ACTOR","not_text":"text.akkadian.anzu"}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('deity.akkadian.ninurta','Ninurta in the Akkadian Anzu myth','阿卡德《安祖神话》中的宁努尔塔','Ninurta','Ninurta','DEITY','civ.akkadian','region.mesopotamia','Second-to-first millennium BCE Akkadian witnesses','本档聚焦《安祖神话》中击败安祖并收回命运泥板的角色。 / Dossier scoped to Ninurta’s role in the Akkadian Anzu myth.','PARTIAL','SOURCE_BACKED',1,'{"witness_scope":"AKKADIAN_ANZU_MYTH"}','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.20.0 ancient Near East witnesses' FROM entities WHERE created_at='2026-08-27T13:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,primary_civilization_id,'WITNESS_SCOPED_CONTEXT','SUPPORTED','v0.20 scoped association' FROM entities WHERE created_at='2026-08-27T13:00:00Z';
INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0200.identification','concept.mesopotamia.inanna_ishtar_identification','Inana–Ištar historical identification','inana istar historical identification','lang.en','Latin','DESCRIPTIVE',1,'source.mesopotamia.inanna_ishtar.oracc','Research label, not an ancient divine name.'),
('name.v0200.dagan','deity.ugaritic.dagan','Dagnu','dagnu','lang.uga','Ugaritic alphabetic cuneiform','ORIGINAL',1,'source.ugaritic.baal_corpus.goettingen','Ugaritic witness scope.'),
('name.v0200.ktu15','text.ugaritic.baal_cycle.ktu1_5','KTU 1.5','ktu 1 5','lang.uga','Modern catalogue label','CATALOGUE',1,'source.ugaritic.baal_corpus_ktu15_16.goettingen',NULL),
('name.v0200.ktu16','text.ugaritic.baal_cycle.ktu1_6','KTU 1.6','ktu 1 6','lang.uga','Modern catalogue label','CATALOGUE',1,'source.ugaritic.baal_corpus_ktu15_16.goettingen',NULL),
('name.v0200.event','event.ugaritic.baal_mot_ktu15_16','Baal and Mot sequence in KTU 1.5–1.6','baal mot sequence ktu 1 5 1 6','lang.en','Latin','DESCRIPTIVE',1,'source.ugaritic.baal_corpus_ktu15_16.goettingen',NULL),
('name.v0200.anzu','creature.akkadian.anzu','Anzû','anzu','lang.akk','Latin transliteration','ORIGINAL',1,'source.mesopotamia.anzu_ninurta.oracc',NULL),
('name.v0200.ninurta','deity.akkadian.ninurta','Ninurta','ninurta','lang.akk','Latin transliteration','ORIGINAL',1,'source.mesopotamia.anzu_ninurta.oracc',NULL);

INSERT OR IGNORE INTO deity_profiles(entity_id,deity_class,pantheon_or_family,rank_or_status,domains_json,powers_json,limitations_json,appearance_json,symbols_json,cult_summary,final_fate_summary) VALUES
('deity.ugaritic.dagan','Ugaritic-text deity','Ugaritic pantheon','Parentage epithet context','[]','[]','["regional witness scope only"]','{}','[]',NULL,NULL),
('deity.akkadian.ninurta','Mesopotamian warrior deity','Akkadian Anzu tradition','Hero of the Anzu narrative','["victory","warrior role"]','[]','["claims limited to registered witnesses"]','{}','[]',NULL,NULL);
INSERT OR IGNORE INTO creature_profiles(entity_id,creature_class,appearance_json,abilities_json,weaknesses_json,habitat_summary,origin_summary,fate_summary) VALUES
('creature.akkadian.anzu','MYTHIC_MONSTROUS_BIRD','{"form":"lion-eagle in later scholarly description"}','["control associated with stolen Tablet of Destinies"]','[]',NULL,'Akkadian Anzu myth witness.','Defeated by Ninurta in the registered synopsis.');
INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.ugaritic.baal_cycle.ktu1_5','CLAY_TABLET_WITNESS','lang.uga','Late Bronze Age','Ras Shamra excavation witness','KTU 1.5','Louvre / registered fragments','AO 16.641 + AO 16.642','Ancient text public domain; modern editions retain rights','Fifth tablet witness in the Baal epic sequence.'),
('text.ugaritic.baal_cycle.ktu1_6','CLAY_TABLET_WITNESS','lang.uga','Late Bronze Age','Ras Shamra excavation witness','KTU 1.6','Louvre','AO 16.636','Ancient text public domain; modern editions retain rights','Sixth tablet witness in the Baal epic sequence.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0200.identification_inanna','concept.mesopotamia.inanna_ishtar_identification','HAS_MEMBER','deity.sumerian.inanna',NULL,NULL,'The research node includes the Sumerian Inana dossier.','mesopotamia.inanna_ishtar.scope','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Sumerian corpus','diachronic',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.identification_ishtar','concept.mesopotamia.inanna_ishtar_identification','HAS_MEMBER','deity.akkadian.ishtar',NULL,NULL,'The research node includes the Akkadian Ištar dossier.','mesopotamia.inanna_ishtar.scope','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Akkadian corpus','diachronic',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.identification_historical','deity.sumerian.inanna','HISTORICALLY_IDENTIFIED_WITH','deity.akkadian.ishtar',NULL,NULL,'Modern Assyriological reference treats Inana/Ištar together while preserving the language-specific names.','mesopotamia.inanna_ishtar.scope','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Mesopotamian traditions','varying periods','A scoped identification relation, not a database merge.','2026-08-27T13:00:00Z'),
('claim.v0200.identification_language_guard','concept.mesopotamia.inanna_ishtar_identification','PRESERVES_DISTINCTION',NULL,'Sumerian Inana textual corpus versus Akkadian Ištar textual corpus','text','The system preserves language, period and witness boundaries inside the historical identification.','mesopotamia.inanna_ishtar.scope','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research method','current checkpoint',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.baal_title_lexeme','concept.ugaritic.baal_title','LEXICAL_MEANING',NULL,'lord / master title lexeme, not automatically one deity in every occurrence','text','The bʿl lexeme can function as a title and must be resolved by context.','ugarit.baal.title_entity','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Ugaritic language','Late Bronze Age','Do not convert every occurrence into the canonical Baal deity.','2026-08-27T13:00:00Z'),
('claim.v0200.baal_title_relation','deity.ugaritic.baal','BEARS_TITLE','concept.ugaritic.baal_title',NULL,NULL,'The Ugaritic storm deity is associated with the bʿl title/name while remaining distinct from the lexeme node.','ugarit.baal.title_entity','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Ugaritic corpus','Late Bronze Age',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.baal_son_dagan','deity.ugaritic.baal','CHILD_OF','deity.ugaritic.dagan',NULL,NULL,'Ugaritic textual formulae call Baal son of Dagan.','ugarit.baal.parentage','SUPPORTED',0.92,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Baal epic','KTU witness set','Exact line collation remains queued.','2026-08-27T13:00:00Z'),
('claim.v0200.baal_son_el','deity.ugaritic.baal','CHILD_OF','deity.ugaritic.el',NULL,NULL,'Other relational language places Baal under El’s paternity in the Ugaritic divine-family discourse.','ugarit.baal.parentage','UNRESOLVED',0.72,'MEDIUM','PROVISIONAL','SCHOLARLY_INTERPRETATION','TEXTUAL_WITNESS','Ugaritic corpus','Late Bronze Age','Do not merge Dagan and El; exact passages require line-level collation.','2026-08-27T13:00:00Z'),
('claim.v0200.ktu15_part','text.ugaritic.baal_cycle.ktu1_5','PART_OF','text.ugaritic.baal_cycle',NULL,NULL,'KTU 1.5 is a distinct tablet witness within the Baal Cycle.','ugarit.baal_mot.tablets','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Ras Shamra tablets','Late Bronze Age',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.ktu16_part','text.ugaritic.baal_cycle.ktu1_6','PART_OF','text.ugaritic.baal_cycle',NULL,NULL,'KTU 1.6 is a distinct tablet witness within the Baal Cycle.','ugarit.baal_mot.tablets','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','ARCHAEOLOGICAL','Ras Shamra tablets','Late Bronze Age',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.event_baal','deity.ugaritic.baal','PARTICIPATED_IN','event.ugaritic.baal_mot_ktu15_16',NULL,NULL,'Baal participates in the KTU 1.5–1.6 sequence.','ugarit.baal_mot.event','SUPPORTED',0.97,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Baal epic','KTU 1.5–1.6',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.event_mot','deity.ugaritic.mot','PARTICIPATED_IN','event.ugaritic.baal_mot_ktu15_16',NULL,NULL,'Mot participates in the KTU 1.5–1.6 sequence.','ugarit.baal_mot.event','SUPPORTED',0.97,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Baal epic','KTU 1.5–1.6',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.event_anat','deity.ugaritic.anat','PARTICIPATED_IN','event.ugaritic.baal_mot_ktu15_16',NULL,NULL,'Anat participates in the Baal–Mot recovery sequence.','ugarit.baal_mot.event','SUPPORTED',0.94,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Baal epic','KTU 1.5–1.6',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.event_no_permanent_death','event.ugaritic.baal_mot_ktu15_16','INTERPRETIVE_LIMIT',NULL,'the fragmentary cycle does not license a timeless claim that death ceased to exist','text','The event is kept as a narrative sequence rather than a universal historical or theological fact.','ugarit.baal_mot.event','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research method','current checkpoint',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.anzu_appears','creature.akkadian.anzu','APPEARS_IN','text.akkadian.anzu',NULL,NULL,'Anzu is the antagonist in the registered Akkadian Anzu text.','mesopotamia.anzu.sequence','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Akkadian Anzu myth','Akkadian witnesses',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.anzu_steals','creature.akkadian.anzu','STEALS','artifact.mesopotamian.tablet_destinies',NULL,NULL,'In the Anzu narrative, Anzu steals the Tablet of Destinies.','mesopotamia.anzu.sequence','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Akkadian Anzu myth','narrative sequence',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.ninurta_appears','deity.akkadian.ninurta','APPEARS_IN','text.akkadian.anzu',NULL,NULL,'Ninurta is the victorious divine hero of the Anzu narrative.','mesopotamia.anzu.sequence','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Akkadian Anzu myth','Akkadian witnesses',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.ninurta_defeats','deity.akkadian.ninurta','DEFEATS','creature.akkadian.anzu',NULL,NULL,'Ninurta defeats Anzu in the scholarly synopsis of the myth.','mesopotamia.anzu.sequence','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Akkadian Anzu myth','narrative sequence',NULL,'2026-08-27T13:00:00Z'),
('claim.v0200.ninurta_recovers','deity.akkadian.ninurta','RECOVERS','artifact.mesopotamian.tablet_destinies',NULL,NULL,'Ninurta’s victory recovers the Tablet of Destinies.','mesopotamia.anzu.sequence','SUPPORTED',0.97,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Akkadian Anzu myth','narrative sequence','Ownership after recovery is a separate textual question.','2026-08-27T13:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0200.identification_%' THEN 'source.mesopotamia.inanna_ishtar.oracc'
      WHEN c.id LIKE 'claim.v0200.anzu_%' OR c.id LIKE 'claim.v0200.ninurta_%' THEN 'source.mesopotamia.anzu_ninurta.oracc'
      ELSE 'source.ugaritic.baal_corpus_ktu15_16.goettingen' END,
 CASE WHEN c.id LIKE 'claim.v0200.identification_%' THEN 'Inana/Ištar specialist overview'
      WHEN c.id LIKE 'claim.v0200.anzu_%' OR c.id LIKE 'claim.v0200.ninurta_%' THEN 'Anzu narrative synopsis'
      ELSE 'KTU corpus overview and concordance' END,
 CASE WHEN c.knowledge_layer='ARCHAEOLOGICAL' THEN 'ARCHAEOLOGICAL' WHEN c.knowledge_layer='MYTHIC_NARRATIVE' OR c.knowledge_layer='TEXTUAL_WITNESS' THEN 'ANCIENT_TEXT' ELSE 'MODERN_SCHOLARSHIP' END,
 'SUPPORTS',c.confidence,'v0.20 source-scoped evidence'
FROM claims c WHERE c.id LIKE 'claim.v0200.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0200.baal_parentage','deity.ugaritic.baal','ugarit.baal.parentage','claim.v0200.baal_son_dagan','claim.v0200.baal_son_el','PARENTAGE_VARIANT','OPEN','Dagan-son formulae and El-paternity discourse must be compared at line and genre level.','Keep Dagan and El distinct; add exact KTU line witnesses before any harmonization.'),
('conflict.v0200.inanna_ishtar_scope','concept.mesopotamia.inanna_ishtar_identification','mesopotamia.inanna_ishtar.scope','claim.v0200.identification_historical','claim.v0200.identification_language_guard','IDENTIFICATION_SCOPE','OPEN','Historical identification does not erase Sumerian/Akkadian language, date and corpus boundaries.','Retain two canonical deity dossiers connected through a dated identification history.');

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add dated bilingual lexical and cultic witnesses for each identification phase',updated_at='2026-08-27T13:00:00Z' WHERE id='queue.mesopotamia.inanna_ishtar';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Extend title-versus-name audit to regional Baal compounds and each corpus occurrence',updated_at='2026-08-27T13:00:00Z' WHERE id='queue.ugarit.baal_title';
UPDATE collection_queue SET status='CONFLICT',attempts=attempts+1,next_action='Collate Dagan and El parentage formulae at exact KTU lines without merging the parent deities',updated_at='2026-08-27T13:00:00Z' WHERE id='queue.v060.ugaritic.baal_parentage';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add column-by-column KTU 1.5 and 1.6 event phases when Göttingen editions publish',updated_at='2026-08-27T13:00:00Z' WHERE id='queue.v060.ugaritic.baal_mot_cycle';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add named tablet witnesses, line locations and variant recensions of the Anzu myth',updated_at='2026-08-27T13:00:00Z' WHERE id='queue.mesopotamia.anzu';

INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0200.mesopotamia.inanna_ishtar_dated','Dated Inana–Ištar identification witnesses','inanna ishtar dated identification','TEXT','civ.akkadian','concept.mesopotamia.inanna_ishtar_identification','claim.v0200.identification_historical','source.mesopotamia.inanna_ishtar.oracc','Overview supports the relation; dated primary-language witnesses remain needed.',96,'SOURCE_FOUND',0,'Register royal inscriptions, hymns and lexical lists by language and century','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z'),
('queue.v0200.ugarit.ktu15_16_editions','KTU 1.5–1.6 forthcoming Göttingen editions','ktu 1 5 1 6 goettingen editions','TEXT','civ.ugaritic','event.ugaritic.baal_mot_ktu15_16','claim.v0200.event_no_permanent_death','source.ugaritic.baal_corpus_ktu15_16.goettingen','Project schedules Baal epic editions for 2027–2029.',97,'SOURCE_FOUND',0,'Revisit when full editions publish; add columns, restorations and apparatus','2026-08-27T13:00:00Z','2026-08-27T13:00:00Z');

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0200_ancient_near_east','2026-08-27T12:05:00Z','2026-08-27T13:00:00Z','Inana–Ištar identification, Baal title and parentage, Baal–Mot tablets, Anzu and Tablet of Destinies','Use ORACC, Göttingen Ugaritic corpus and museum concordances; keep languages, tablets, actors and interpretations distinct','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Staged baseline; forthcoming editions and exact line collation remain queued.');
UPDATE project_metadata SET value='0.20.0-ancient-near-east-witnesses-20260827',updated_at='2026-08-27T13:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='27',updated_at='2026-08-27T13:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T13:00:00Z',updated_at='2026-08-27T13:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.20.0',27,'0.20.0-ancient-near-east-witnesses-20260827',NULL,'2026-08-27T13:00:00Z',NULL,'Ancient Near East checkpoint: historically scoped Inana–Ištar identification, Baal title/entity distinction and parentage conflict, KTU 1.5–1.6 Baal–Mot witnesses, Anzu–Ninurta–Tablet sequence.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(27,'20260827_v0200_ancient_near_east_witnesses','2026-08-27T13:00:00Z');
COMMIT;
