BEGIN IMMEDIATE;

INSERT OR IGNORE INTO civilizations(id,canonical_name,name_zh,original_name,parent_id,region_id,tradition_type,period_start,period_end,description,research_status,evidence_status) VALUES
('civ.chinese','Chinese traditions — cross-period umbrella','中国传统跨时期总类','中國傳統',NULL,'region.east_asia','CROSS_PERIOD_RESEARCH_UMBRELLA',NULL,NULL,'Navigation umbrella for cross-period comparisons; it does not replace Ancient Chinese, Daoist, folk or local civilization dossiers.','PARTIAL','SOURCE_BACKED');

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.china.mogao_thunder.dunhuang','敦煌岁时节令｜惊蛰：“爆裂鼓手”醒万物','OFFICIAL_ART_HISTORY',3,'Dunhuang Academy','Dunhuang Academy','lang.zh',NULL,'2026-08-27','https://www.dha.ac.cn/info/1157/2653.htm','Dunhuang Academy page terms apply','Official public interpretation of thunder-deity imagery in Mogao Caves 285 and 249','Do not package images',0,'Chinese official public article','URL_SYNTAX_VALID','Identifies Western Wei thunder-deity imagery and compares its connected-drum form with Wang Chong’s Lunheng description.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('text.chinese.hongfan.wuxing_passage','Hong Fan Wuxing passage witness','《洪范》五行段落见证','洪范·五行','Hong Fan: Wuxing','TEXT','civ.chinese','region.east_asia','Received Shangshu tradition; dating of layers debated','登记“水、火、木、金、土”及其运动／功用表述的段落级见证，不把后世全部五行理论倒灌其中。 / Passage-level witness for the five named operations and their qualities.','PARTIAL','SOURCE_BACKED',1,'{"witness_scope":"HONG_FAN_FIRST_DIVISION","later_correlative_systems_included":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('text.chinese.hanshu.wuxing_omen_passage','Han Shu Wuxing omen framework witness','《汉书·五行志》灾异框架见证','漢書·五行志','Han Shu Wuxing Zhi','TEXT','civ.chinese','region.east_asia','Eastern Han compilation of Former Han history','登记汉代史书中五行、政德与灾异解释的文本层，与《洪范》原段并列。 / Witness for Han historiographic correlations among phases, governance and anomalies.','PARTIAL','SOURCE_BACKED',1,'{"witness_scope":"HAN_SHU_WUXING_ZHI","same_semantic_layer_as_hongfan":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('concept.chinese.wuxing.hongfan_operations','Hong Fan operational qualities layer','《洪范》五行运动／功用层',NULL,NULL,'CONCEPT','civ.chinese','region.east_asia','Received Hong Fan textual layer','研究导航：润下、炎上、曲直、从革、稼穑等段落语义；不是现代“化学元素”。 / Research layer for operational qualities in the Hong Fan passage.','PARTIAL','SOURCE_BACKED',1,'{"semantic_layer":"HONG_FAN_OPERATIONS","modern_chemical_elements":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('concept.chinese.wuxing.han_correlative_omens','Han historiographic correlative-omen layer','汉代五行灾异解释层',NULL,NULL,'CONCEPT','civ.chinese','region.east_asia','Han historiography','研究导航：汉代史学中五行、政治伦理、气与灾异的对应；不视为《洪范》逐字同义。 / Han historiographic correlation layer, distinct from the Hong Fan passage.','PARTIAL','SOURCE_BACKED',1,'{"semantic_layer":"HAN_HISTORIOGRAPHIC_CORRELATION","same_as_hongfan":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('site.chinese.mogao_cave_249','Mogao Cave 249','莫高窟第249窟','莫高窟第249窟','Mogao Cave 249','ARCHAEOLOGICAL_SITE','civ.chinese','region.east_asia','Western Wei','敦煌研究院公开资料指出窟内保存雷神图像；本档只登记官方公开图像史语境。 / Official Dunhuang Academy public record notes a thunder-deity image in the cave.','PARTIAL','SOURCE_BACKED',1,'{"site_layer":"REAL_ARCHAEOLOGICAL_CAVE","image_reuse":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('concept.chinese.leigong.visual_witnesses','Leigong / thunder-deity visual witness layer','雷公／雷神图像见证层',NULL,NULL,'CONCEPT','civ.chinese','region.east_asia','Han textual description to Western Wei murals','连接《论衡》文字与莫高窟图像的比较导航；相似构图不自动证明同一作者、仪式或连续传承。 / Comparison layer linking textual description and mural witnesses without overclaiming continuity.','PARTIAL','SOURCE_BACKED',1,'{"comparison_only":true,"continuous_lineage_claim":false}','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.21.0 Chinese semantic layers' FROM entities WHERE created_at='2026-08-27T14:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,'civ.chinese','CHINESE_TEXT_OR_VISUAL_CONTEXT','SUPPORTED','v0.21 scoped association' FROM entities WHERE created_at='2026-08-27T14:00:00Z';
INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0210.hongfan','text.chinese.hongfan.wuxing_passage','洪范·五行','洪范 五行','lang.lzh','Han characters','DESCRIPTIVE',1,'source.china.hong_fan.ctext',NULL),
('name.v0210.hanshu','text.chinese.hanshu.wuxing_omen_passage','漢書·五行志','漢書 五行志','lang.lzh','Han characters','DESCRIPTIVE',1,'source.china.han_shu.wuxing_zhi.ctext',NULL),
('name.v0210.hf_layer','concept.chinese.wuxing.hongfan_operations','《洪范》五行运动／功用层','洪范 五行 运动 功用层','lang.zh','Han characters','DESCRIPTIVE',1,'source.china.hong_fan.ctext','Modern research label.'),
('name.v0210.han_layer','concept.chinese.wuxing.han_correlative_omens','汉代五行灾异解释层','汉代 五行 灾异 解释层','lang.zh','Han characters','DESCRIPTIVE',1,'source.china.han_shu.wuxing_zhi.ctext','Modern research label.'),
('name.v0210.cave249','site.chinese.mogao_cave_249','莫高窟第249窟','莫高窟 第249窟','lang.zh','Han characters','PREFERRED',1,'source.china.mogao_thunder.dunhuang',NULL),
('name.v0210.visual','concept.chinese.leigong.visual_witnesses','雷公／雷神图像见证层','雷公 雷神 图像 见证层','lang.zh','Han characters','DESCRIPTIVE',1,'source.china.mogao_thunder.dunhuang','Modern comparison label.');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.chinese.hongfan.wuxing_passage','RECEIVED_CLASSICAL_PASSAGE','lang.lzh','Textual layers and received dating debated','Received editions represented by CTP bibliography','Hong Fan, first division','Chinese Text Project bibliography links multiple editions','Hong Fan / Great Plan','Ancient text public domain; digital edition terms apply','Names water, fire, wood, metal and earth and describes characteristic operations.'),
('text.chinese.hanshu.wuxing_omen_passage','DYNASTIC_HISTORY_TREATISE','lang.lzh','Han Shu compilation','Received editions represented by CTP','Wuxing Zhi','Chinese Text Project bibliography links multiple editions','Han Shu, Wuxing Zhi','Ancient text public domain; digital edition terms apply','Correlates phase disorder with moral-political and anomaly discourse in Han historiography.');
INSERT OR IGNORE INTO place_profiles(entity_id,place_type,ancient_name,modern_name,country_code,latitude,longitude,date_range,builders,architecture_summary,excavation_summary,major_finds_summary,unesco_status,reality_status,evidence_grade) VALUES
('site.chinese.mogao_cave_249','CAVE_TEMPLE_COMPONENT','莫高窟第249窟','Mogao Cave 249','CN',NULL,NULL,'Western Wei',NULL,'Individual cave within the Mogao complex',NULL,'Official public context identifies a thunder-deity mural','Component of UNESCO Mogao Caves 440','REAL','OFFICIAL_SITE');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0210.hongfan_part','text.chinese.hongfan.wuxing_passage','PART_OF','text.chinese.hong_fan',NULL,NULL,'The passage witness is a scoped part of the Hong Fan record.','china.wuxing.semantic_layers','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Received Shangshu tradition','Hong Fan passage',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_mentions','text.chinese.hongfan.wuxing_passage','MENTIONS','concept.chinese.wuxing',NULL,NULL,'The Hong Fan passage explicitly names wuxing.','china.wuxing.semantic_layers','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Received Shangshu tradition','Hong Fan passage',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_sequence','text.chinese.hongfan.wuxing_passage','PRESENTS_SEQUENCE',NULL,'water, fire, wood, metal, earth','text','The passage presents the five in this textual order.','china.wuxing.hongfan','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Hong Fan','first division','Textual list, not a universal chronological sequence.','2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_operations','concept.chinese.wuxing.hongfan_operations','DERIVED_FROM','text.chinese.hongfan.wuxing_passage',NULL,NULL,'The operational-quality layer is derived from the registered passage.','china.wuxing.hongfan','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research navigation','current',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_water','concept.chinese.wuxing.hongfan_operations','DESCRIBES',NULL,'water moistens and descends','text','The passage assigns moistening and descending to water.','china.wuxing.hongfan','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Hong Fan','first division',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_fire','concept.chinese.wuxing.hongfan_operations','DESCRIBES',NULL,'fire flames upward','text','The passage assigns flaming upward to fire.','china.wuxing.hongfan','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Hong Fan','first division',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hongfan_other','concept.chinese.wuxing.hongfan_operations','DESCRIBES',NULL,'wood as bending/straightening, metal as yielding/change, earth as sowing/harvesting','text','The passage gives distinct operational descriptions for wood, metal and earth.','china.wuxing.hongfan','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Hong Fan','first division',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hanshu_part','text.chinese.hanshu.wuxing_omen_passage','PART_OF','text.chinese.han_shu_wuxing_zhi',NULL,NULL,'The witness is scoped to the Han Shu Wuxing Zhi.','china.wuxing.semantic_layers','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Han historiography','Wuxing Zhi',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.hanshu_mentions','text.chinese.hanshu.wuxing_omen_passage','MENTIONS','concept.chinese.wuxing',NULL,NULL,'The Han Shu treatise explicitly organizes material under wuxing.','china.wuxing.semantic_layers','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Han historiography','Wuxing Zhi',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.han_layer','concept.chinese.wuxing.han_correlative_omens','DERIVED_FROM','text.chinese.hanshu.wuxing_omen_passage',NULL,NULL,'The Han correlative-omen layer is derived from the registered Han Shu witness.','china.wuxing.han','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Han historiography','received treatise',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.layers_distinct','concept.chinese.wuxing.han_correlative_omens','PRESERVES_DISTINCTION',NULL,'not identical in semantic scope to the Hong Fan operational-quality passage','text','The checkpoint treats semantic development diachronically rather than flattening all wuxing usage.','china.wuxing.semantic_layers','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research method','current',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.lunheng_drums','text.chinese.lunheng','DESCRIBES','deity.chinese.leigong',NULL,NULL,'The Lei Xu discussion describes a strong figure striking linked drums.','china.leigong.diachronic','SUPPORTED',0.96,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Han textual discourse','Lunheng Lei Xu','Description and authorial argument must be read in chapter context.','2026-08-27T14:00:00Z'),
('claim.v0210.cave285_image','site.chinese.mogao_cave_285','CONTAINS_DEPICTION_OF','deity.chinese.leigong',NULL,NULL,'Dunhuang Academy identifies a Western Wei thunder-deity image with twelve linked drums in Cave 285.','china.leigong.visual','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Mogao visual culture','Western Wei','Modern official identification, not an ancient caption.','2026-08-27T14:00:00Z'),
('claim.v0210.cave249_image','site.chinese.mogao_cave_249','CONTAINS_DEPICTION_OF','deity.chinese.leigong',NULL,NULL,'Dunhuang Academy identifies a thunder-deity image in Cave 249.','china.leigong.visual','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','ARCHAEOLOGICAL','Mogao visual culture','Western Wei','Modern official identification, not an ancient caption.','2026-08-27T14:00:00Z'),
('claim.v0210.visual_lunheng','concept.chinese.leigong.visual_witnesses','HAS_MEMBER','text.chinese.lunheng',NULL,NULL,'The comparison layer includes the Han textual description.','china.leigong.visual','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research comparison','modern',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.visual_285','concept.chinese.leigong.visual_witnesses','HAS_MEMBER','site.chinese.mogao_cave_285',NULL,NULL,'The comparison layer includes Cave 285.','china.leigong.visual','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research comparison','modern',NULL,'2026-08-27T14:00:00Z'),
('claim.v0210.visual_249','concept.chinese.leigong.visual_witnesses','HAS_MEMBER','site.chinese.mogao_cave_249',NULL,NULL,'The comparison layer includes Cave 249.','china.leigong.visual','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research comparison','modern',NULL,'2026-08-27T14:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0210.hongfan_%' THEN 'source.china.hong_fan.ctext' WHEN c.id LIKE 'claim.v0210.hanshu_%' OR c.id='claim.v0210.han_layer' OR c.id='claim.v0210.layers_distinct' THEN 'source.china.han_shu.wuxing_zhi.ctext' WHEN c.id='claim.v0210.lunheng_drums' THEN 'source.chinese.lunheng_leixu.ctext' ELSE 'source.china.mogao_thunder.dunhuang' END,
 CASE WHEN c.id LIKE 'claim.v0210.hongfan_%' THEN 'Hong Fan, first division' WHEN c.id LIKE 'claim.v0210.hanshu_%' OR c.id='claim.v0210.han_layer' OR c.id='claim.v0210.layers_distinct' THEN 'Han Shu, Wuxing Zhi' WHEN c.id='claim.v0210.lunheng_drums' THEN 'Lunheng, Lei Xu' ELSE 'Dunhuang Academy public art-history article' END,
 CASE WHEN c.knowledge_layer='ARCHAEOLOGICAL' THEN 'ARCHAEOLOGICAL' WHEN c.knowledge_layer='TEXTUAL_WITNESS' THEN 'ANCIENT_TEXT' ELSE 'MODERN_SCHOLARSHIP' END,
 'SUPPORTS',c.confidence,'v0.21 semantic- or witness-scoped evidence' FROM claims c WHERE c.id LIKE 'claim.v0210.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0210.wuxing_semantic_layers','concept.chinese.wuxing','china.wuxing.semantic_layers','claim.v0210.hongfan_operations','claim.v0210.han_layer','DIACHRONIC_SEMANTIC_SCOPE','OPEN','Hong Fan operational descriptions and Han historiographic correlations are related but not semantically identical layers.','Retain passage, date, genre and later interpretive systems separately.'),
('conflict.v0210.leigong_visual_continuity','concept.chinese.leigong.visual_witnesses','china.leigong.visual','claim.v0210.lunheng_drums','claim.v0210.cave285_image','TEXT_IMAGE_CONTINUITY_LIMIT','OPEN','Official scholarship notes visual similarity, but similarity alone does not prove a continuous cult, workshop or textual dependency.','Add iconographic studies and inscriptional context before asserting transmission.');

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add pre-Qin, Qin-Han and later semantic stages with exact passages and scholarly dating',updated_at='2026-08-27T14:00:00Z' WHERE id IN ('queue.china.wuxing_sources','queue.china.wuxing_semantic_history');
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Add dated Daoist thunder-administration texts, temple records and region-specific living traditions; keep each layer distinct',updated_at='2026-08-27T14:00:00Z' WHERE id='queue.v060.chinese.leigong_diachronic';
INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0210.china.leigong_daoist','Leigong in dated Daoist thunder-administration texts','leigong daoist thunder administration dated texts','TEXT','civ.chinese','deity.chinese.leigong','claim.v0210.lunheng_drums','source.chinese.lunheng_leixu.ctext','Classical and visual layers are registered; Daoist administrative layer lacks a verified primary text.',98,'NEEDS_REVIEW',0,'Locate an authorized Daozang digital edition and register title, fascicle and passage before adding claims','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z'),
('queue.v0210.china.mogao_thunder_iconography','Mogao thunder-deity iconography by cave and period','mogao thunder deity iconography','ARCHAEOLOGICAL_SITE','civ.chinese','concept.chinese.leigong.visual_witnesses','claim.v0210.cave285_image','source.china.mogao_thunder.dunhuang','Official overview identifies two caves; detailed conservation and iconographic dossiers remain open.',94,'SOURCE_FOUND',0,'Add cave reports and image-location metadata without republishing protected images','2026-08-27T14:00:00Z','2026-08-27T14:00:00Z');

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0210_chinese_semantic_layers','2026-08-27T13:05:00Z','2026-08-27T14:00:00Z','Hong Fan and Han Shu wuxing semantics; Lunheng and Mogao thunder-deity witnesses','Use primary digital text passages and Dunhuang Academy public context; preserve date, genre, semantics and image interpretation','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Daoist thunder-administration primary sources remain queued rather than inferred.');
UPDATE project_metadata SET value='0.21.0-chinese-semantic-layers-20260827',updated_at='2026-08-27T14:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='29',updated_at='2026-08-27T14:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T14:00:00Z',updated_at='2026-08-27T14:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.21.0',29,'0.21.0-chinese-semantic-layers-20260827',NULL,'2026-08-27T14:00:00Z',NULL,'Chinese semantic-layer checkpoint: Hong Fan operational passage, Han Shu correlative-omen layer, Lunheng description and Mogao Caves 285/249 thunder-deity visual witnesses.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(29,'20260827_v0210_chinese_semantic_layers','2026-08-27T14:00:00Z');
COMMIT;
