BEGIN IMMEDIATE;

INSERT OR IGNORE INTO civilizations(id,canonical_name,name_zh,original_name,parent_id,region_id,tradition_type,period_start,period_end,description,research_status,evidence_status) VALUES
('civ.buddhist_himalayan','Himalayan Buddhist traditions','喜马拉雅佛教传统',NULL,'civ.buddhist','region.south_asia','REGIONAL_TRADITION',NULL,NULL,'Regional umbrella for separately dated Himalayan Buddhist witnesses.','PARTIAL','SOURCE_BACKED'),
('civ.buddhist_chinese','Chinese Buddhist traditions','中国佛教传统',NULL,'civ.buddhist','region.east_asia','REGIONAL_TRADITION',NULL,NULL,'Regional umbrella for separately dated Chinese Buddhist witnesses.','PARTIAL','SOURCE_BACKED'),
('civ.buddhist_indian','Indian Buddhist traditions','印度佛教传统',NULL,'civ.buddhist','region.south_asia','REGIONAL_TRADITION',NULL,NULL,'Regional umbrella for Indian Buddhist witnesses; object dossiers remain separate.','PARTIAL','SOURCE_BACKED');

INSERT OR IGNORE INTO sources(id,title,source_type,evidence_tier,institution,author_or_editor,language_id,publication_date,accessed_date,url,catalogue_number,rights_status,source_perspective,access_or_reuse_restrictions,community_permission_required,translation_status,verification_status,notes) VALUES
('source.met.vajra.1994_605_43','Vajra with Angry Heads and Makara Prongs','MUSEUM_OBJECT',3,'Metropolitan Museum of Art','Metropolitan Museum of Art','lang.en',NULL,'2026-08-27','https://www.metmuseum.org/art/collection/search/44344','1994.605.43','Open Access object record; image marked Public Domain','Official catalogue for a Tang-dynasty Chinese ritual instrument','Metadata and independent summaries; public-domain image not packaged',0,'English museum record','URL_SYNTAX_VALID','Gilt bronze, China, Tang dynasty; the catalogue describes tantric ritual use and diamond-like enlightenment symbolism.'),
('source.bm.vajra.1948_0716_11_b','vajra — British Museum 1948,0716.11.b','MUSEUM_OBJECT',3,'British Museum','British Museum','lang.en',NULL,'2026-08-27','https://www.britishmuseum.org/collection/object/A_1948-0716-11-b','1948,0716.11.b','British Museum terms apply','Official collection record for a Buddhist ritual vajra','Do not package collection images',0,'English museum record','URL_SYNTAX_VALID','Museum summary distinguishes Buddhist ritual-object survivals from earlier Indian weapon traditions.'),
('source.rubin.vajra.sc2022_3_2_1','Vajra — SC2022.3.2.1','MUSEUM_OBJECT',3,'Rubin Museum of Himalayan Art','Rubin Museum of Himalayan Art','lang.en',NULL,'2026-08-27','https://rubinmuseum.org/collection/sc2022-3-2-1/','SC2022.3.2.1','Museum page terms apply','Official catalogue for an eighteenth-century Tibetan ritual scepter','Do not package collection images',0,'English museum record','URL_SYNTAX_VALID','Metal ritual object from Tibet; catalogue identifies ritual use and method symbolism.');

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('text.vedic.rigveda.1_32','Rigveda 1.32 witness','《梨俱吠陀》1.32见证','ऋग्वेद १.३२','Ṛgveda 1.32','TEXT','civ.vedic','region.south_asia','Vedic textual tradition','登记因陀罗、弗栗多与 vajra 词的颂歌级见证；与后世金属仪式器分开。 / Hymn-level witness for Indra, Vṛtra and vajra, distinct from later metal ritual objects.','PARTIAL','SOURCE_BACKED',1,'{"witness":"SHAKALA_SAMHITA_MANDALA_1_SUKTA_32","same_object_as_later_ritual_vajras":false}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('institution.rubin_museum','Rubin Museum of Himalayan Art','鲁宾喜马拉雅艺术博物馆',NULL,NULL,'INSTITUTION','civ.buddhist_himalayan','region.north_america','Modern museum','保存和公开研究喜马拉雅艺术对象的现代机构。 / Modern institution holding Himalayan art objects.','PARTIAL','SOURCE_BACKED',1,'{"institution_type":"MUSEUM"}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('museum.met.vajra_1994_605_43','Vajra with Angry Heads and Makara Prongs 1994.605.43','鎏金青铜金刚杵 1994.605.43','唐 鎏金青銅金剛杵',NULL,'MUSEUM_OBJECT','civ.buddhist_chinese','region.east_asia','Tang dynasty (618–907)','大都会馆藏的唐代鎏金青铜仪式器；不是《梨俱吠陀》叙事中的那一件武器。 / Tang-dynasty gilt-bronze ritual object, not the mythic weapon-token in Rigveda 1.32.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_MUSEUM_OBJECT","ritual_object":true,"not_same_as":"weapon.vedic.vajra"}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('museum.bm.vajra_1948_0716_11_b','Buddhist ritual vajra 1948,0716.11.b','佛教仪式金刚杵 1948,0716.11.b',NULL,NULL,'MUSEUM_OBJECT','civ.buddhist_himalayan','region.south_asia','Museum-dated object; exact regional dossier requires catalogue audit','大英博物馆登记的佛教仪式器；精确年代与产地只按馆藏页继续扩张。 / British Museum Buddhist ritual object; date and provenance remain catalogue-scoped.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_MUSEUM_OBJECT","ritual_object":true,"not_same_as":"weapon.vedic.vajra"}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('museum.rubin.vajra_sc2022_3_2_1','Tibetan Vajra SC2022.3.2.1','西藏金刚杵 SC2022.3.2.1',NULL,NULL,'MUSEUM_OBJECT','civ.buddhist_himalayan','region.south_asia','Eighteenth century','鲁宾馆藏西藏金属仪式权杖；其“方法”象征属于馆藏解释层。 / Eighteenth-century Tibetan ritual scepter; symbolism remains museum interpretation.','PARTIAL','SOURCE_BACKED',1,'{"reality_status":"REAL_MUSEUM_OBJECT","ritual_object":true,"not_same_as":"weapon.vedic.vajra"}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('concept.south_asia.vajra_reception_layers','Vajra textual and material reception layers','vajra／金刚杵文本与物质接受层',NULL,NULL,'CONCEPT','civ.vedic','region.south_asia','Vedic through modern museum reception','比较吠陀武器词、佛教仪式器与馆藏解释的导航；成员之间不共享物理身份。 / Comparison network for textual weapon, ritual objects and museum interpretations; no shared physical identity.','PARTIAL','SOURCE_BACKED',1,'{"comparison_only":true,"shared_physical_identity":false,"jain_layer_status":"QUEUED"}','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z');

INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.22.0 vajra reception layers' FROM entities WHERE created_at='2026-08-27T15:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,primary_civilization_id,'TEXT_OR_MATERIAL_RECEPTION_CONTEXT','SUPPORTED','v0.22 scoped association' FROM entities WHERE created_at='2026-08-27T15:00:00Z';
INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0220.rv','text.vedic.rigveda.1_32','ऋग्वेद १.३२','ऋग्वेद १ ३२','lang.san','Devanagari','ORIGINAL_TITLE',1,'source.vedic.rigveda.1_32.vhp',NULL),
('name.v0220.rubin','institution.rubin_museum','Rubin Museum of Himalayan Art','rubin museum of himalayan art','lang.en','Latin','PREFERRED',1,'source.rubin.vajra.sc2022_3_2_1',NULL),
('name.v0220.met','museum.met.vajra_1994_605_43','唐 鎏金青銅金剛杵','唐 鎏金青銅 金剛杵','lang.zh','Han characters','CATALOGUE',1,'source.met.vajra.1994_605_43',NULL),
('name.v0220.bm','museum.bm.vajra_1948_0716_11_b','vajra 1948,0716.11.b','vajra 1948 0716 11 b','lang.en','Latin','CATALOGUE',1,'source.bm.vajra.1948_0716_11_b',NULL),
('name.v0220.rubinobj','museum.rubin.vajra_sc2022_3_2_1','Vajra SC2022.3.2.1','vajra sc2022 3 2 1','lang.en','Latin','CATALOGUE',1,'source.rubin.vajra.sc2022_3_2_1',NULL),
('name.v0220.layers','concept.south_asia.vajra_reception_layers','Vajra textual and material reception layers','vajra textual material reception layers','lang.en','Latin','DESCRIPTIVE',1,'source.met.vajra.1994_605_43','Modern research label.');

INSERT OR IGNORE INTO text_profiles(entity_id,text_type,original_language_id,composition_period,earliest_extant_witness,chapter_structure,repository,shelfmark,copyright_status,summary) VALUES
('text.vedic.rigveda.1_32','VEDIC_HYMN_WITNESS','lang.san','Vedic period; precise dating debated','Śākala Saṃhitā transmission','Mandala 1, Sukta 32','Vedic Heritage Portal','RV 1.32','Ancient text public domain; portal media terms apply','Hymn witness for Indra’s acts, Vṛtra and vajra terminology.');
INSERT OR IGNORE INTO museum_object_profiles(entity_id,holding_institution,catalogue_number,object_type,provenance,date_range,acquisition_notes) VALUES
('museum.met.vajra_1994_605_43','Metropolitan Museum of Art','1994.605.43','Five-pronged gilt-bronze vajra ritual instrument','China','Tang dynasty (618–907)','Charlotte C. and John C. Weber Collection, gift 1994.'),
('museum.bm.vajra_1948_0716_11_b','British Museum','1948,0716.11.b','Buddhist ritual vajra','Museum catalogue scope','Date pending fuller catalogue audit','Official British Museum object record.'),
('museum.rubin.vajra_sc2022_3_2_1','Rubin Museum of Himalayan Art','SC2022.3.2.1','Metal vajra ritual scepter','Tibet','18th century','Gift from the Collection of Jane Werner-Aye.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0220.rv_part','text.vedic.rigveda.1_32','PART_OF','text.vedic.rigveda',NULL,NULL,'RV 1.32 is a hymn-level witness within the Rigveda.','vajra.vedic_witness','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','TEXTUAL_WITNESS','Śākala Rigveda','Mandala 1',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.rv_indra','text.vedic.rigveda.1_32','MENTIONS','deity.vedic.indra',NULL,NULL,'RV 1.32 names Indra as the hymn’s deity and actor.','vajra.vedic_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Vedic text','RV 1.32',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.rv_vritra','text.vedic.rigveda.1_32','MENTIONS','creature.vedic.vritra',NULL,NULL,'RV 1.32 narrates Indra’s encounter with Vṛtra.','vajra.vedic_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Vedic text','RV 1.32',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.rv_vajra','text.vedic.rigveda.1_32','MENTIONS','weapon.vedic.vajra',NULL,NULL,'RV 1.32 contains vajra terminology in its account of Indra.','vajra.vedic_witness','SUPPORTED',0.99,'HIGH','VERIFIED','TEXT_SAYS','TEXTUAL_WITNESS','Vedic text','RV 1.32','Translation and material reconstruction remain separate questions.','2026-08-27T15:00:00Z'),
('claim.v0220.indra_uses','deity.vedic.indra','USES','weapon.vedic.vajra',NULL,NULL,'In RV 1.32, Indra is associated with wielding the vajra against Vṛtra.','vajra.vedic_witness','SUPPORTED',0.98,'HIGH','VERIFIED','TEXT_SAYS','MYTHIC_NARRATIVE','Vedic text','RV 1.32',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.network_weapon','concept.south_asia.vajra_reception_layers','HAS_MEMBER','weapon.vedic.vajra',NULL,NULL,'The comparison network includes the Vedic weapon concept.','vajra.reception_layers','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research navigation','modern',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.network_met','concept.south_asia.vajra_reception_layers','HAS_MEMBER','museum.met.vajra_1994_605_43',NULL,NULL,'The network includes the Tang material object.','vajra.reception_layers','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.network_bm','concept.south_asia.vajra_reception_layers','HAS_MEMBER','museum.bm.vajra_1948_0716_11_b',NULL,NULL,'The network includes the British Museum Buddhist ritual object.','vajra.reception_layers','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.network_rubin','concept.south_asia.vajra_reception_layers','HAS_MEMBER','museum.rubin.vajra_sc2022_3_2_1',NULL,NULL,'The network includes the Tibetan Rubin Museum ritual object.','vajra.reception_layers','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Research navigation','modern',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.met_held','museum.met.vajra_1994_605_43','HELD_BY_MUSEUM','institution.met',NULL,NULL,'The Metropolitan Museum of Art holds 1994.605.43.','vajra.material_objects','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Modern custody','current catalogue',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.bm_held','museum.bm.vajra_1948_0716_11_b','HELD_BY_MUSEUM','institution.british_museum',NULL,NULL,'The British Museum holds 1948,0716.11.b.','vajra.material_objects','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Modern custody','current catalogue',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.rubin_held','museum.rubin.vajra_sc2022_3_2_1','HELD_BY_MUSEUM','institution.rubin_museum',NULL,NULL,'The Rubin Museum catalogue identifies SC2022.3.2.1.','vajra.material_objects','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','LATER_RECEPTION','Modern custody','current catalogue',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.met_ritual','museum.met.vajra_1994_605_43','USED_AS',NULL,'tantric ritual instrument','text','The museum interprets the Tang object as a tantric ritual instrument.','vajra.material_objects','SUPPORTED',0.98,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Chinese Buddhist art','Tang dynasty','Museum interpretation, not Vedic textual fact.','2026-08-27T15:00:00Z'),
('claim.v0220.bm_ritual','museum.bm.vajra_1948_0716_11_b','USED_AS',NULL,'Buddhist ritual object','text','The British Museum classifies the object within Buddhist ritual use.','vajra.material_objects','SUPPORTED',0.96,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Buddhist material culture','catalogue scope',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.rubin_ritual','museum.rubin.vajra_sc2022_3_2_1','USED_AS',NULL,'tantric ritual scepter','text','The Rubin Museum classifies the object as a ritual scepter.','vajra.material_objects','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','LATER_RECEPTION','Tibetan Buddhist art','18th century',NULL,'2026-08-27T15:00:00Z'),
('claim.v0220.no_identity','concept.south_asia.vajra_reception_layers','PRESERVES_DISTINCTION',NULL,'textual weapon-token, three separately catalogued objects and later symbolic interpretations','text','Shared vocabulary and reception do not establish one physical object across centuries.','vajra.reception_layers','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Research method','current',NULL,'2026-08-27T15:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,catalogue_number,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0220.rv_%' OR c.id='claim.v0220.indra_uses' THEN 'source.vedic.rigveda.1_32.vhp' WHEN c.id LIKE 'claim.v0220.%met%' THEN 'source.met.vajra.1994_605_43' WHEN c.id LIKE 'claim.v0220.%bm%' THEN 'source.bm.vajra.1948_0716_11_b' WHEN c.id LIKE 'claim.v0220.%rubin%' THEN 'source.rubin.vajra.sc2022_3_2_1' ELSE 'source.met.vajra.1994_605_43' END,
 'Registered text passage or museum catalogue',NULL,CASE WHEN c.knowledge_layer='TEXTUAL_WITNESS' OR c.knowledge_layer='MYTHIC_NARRATIVE' THEN 'PRIMARY_TEXT' WHEN c.knowledge_layer='LATER_RECEPTION' THEN 'MUSEUM_OBJECT' ELSE 'MODERN_SCHOLARSHIP' END,'SUPPORTS',c.confidence,'v0.22 reception-layer evidence' FROM claims c WHERE c.id LIKE 'claim.v0220.%';

INSERT OR IGNORE INTO conflicts(id,subject_id,variant_group,claim_a_id,claim_b_id,conflict_type,status,summary,resolution_notes) VALUES
('conflict.v0220.vajra_object_identity','concept.south_asia.vajra_reception_layers','vajra.reception_layers','claim.v0220.rv_vajra','claim.v0220.no_identity','TEXT_OBJECT_IDENTITY_LIMIT','OPEN','The shared term vajra links textual and material reception but does not identify one physical object.','Preserve every dated museum object, textual witness and ritual interpretation as a separate record.');
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add Jain object records and dated Indian Buddhist examples from authorized catalogues; preserve tradition and material distinctions',updated_at='2026-08-27T15:00:00Z' WHERE id='queue.v060.vedic.vajra_reception';
INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0220.vajra.jain_objects','Jain vajra terminology and authorized object records','jain vajra objects','MUSEUM_OBJECT','civ.jain','concept.south_asia.vajra_reception_layers','claim.v0220.no_identity','source.bm.vajra.1948_0716_11_b','No sufficiently specific Jain primary or museum record was verified in this batch.',96,'NEEDS_REVIEW',0,'Locate Jain institutional or museum catalogues before adding any Jain reception claim','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z'),
('queue.v0220.vajra.indian_buddhist_objects','Early Indian Buddhist vajra material witnesses','early indian buddhist vajra objects','MUSEUM_OBJECT','civ.buddhist_indian','concept.south_asia.vajra_reception_layers','claim.v0220.network_bm','source.bm.vajra.1948_0716_11_b','Museum summary notes the survival gap for Buddhist India.',95,'SOURCE_FOUND',0,'Register securely dated Indian examples or explicit absence statements from museum scholarship','2026-08-27T15:00:00Z','2026-08-27T15:00:00Z');
INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0220_vajra_reception','2026-08-27T14:05:00Z','2026-08-27T15:00:00Z','Rigveda 1.32 and later Buddhist vajra ritual objects','Use official Vedic text and museum catalogues; distinguish textual weapon, material objects, custody and curatorial interpretation','CHECKPOINT_COMPLETE','Codex persistent research pipeline','Jain and early Indian Buddhist object layers remain queued.');
UPDATE project_metadata SET value='0.22.0-vajra-reception-layers-20260827',updated_at='2026-08-27T15:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='31',updated_at='2026-08-27T15:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T15:00:00Z',updated_at='2026-08-27T15:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.22.0',31,'0.22.0-vajra-reception-layers-20260827',NULL,'2026-08-27T15:00:00Z',NULL,'Vajra reception checkpoint: Rigveda 1.32 witness, three separately catalogued Buddhist ritual objects and a non-identity comparison network; Jain layer remains queued.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(31,'20260827_v0220_vajra_reception_layers','2026-08-27T15:00:00Z');
COMMIT;
