BEGIN IMMEDIATE;

CREATE TABLE IF NOT EXISTS tradition_access_policies (
    id TEXT PRIMARY KEY,
    entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    source_id TEXT REFERENCES sources(id),
    authority_name TEXT NOT NULL,
    community_context TEXT,
    access_level TEXT NOT NULL CHECK(access_level IN ('PUBLIC_CONTEXT','ATTRIBUTION_REQUIRED','PERMISSION_REQUIRED','DO_NOT_COLLECT')),
    permitted_scope TEXT NOT NULL,
    prohibited_scope TEXT NOT NULL,
    attribution_requirement TEXT,
    permission_contact_or_process TEXT,
    policy_basis TEXT NOT NULL,
    reviewed_at TEXT NOT NULL,
    notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_tradition_access_entity ON tradition_access_policies(entity_id);
CREATE INDEX IF NOT EXISTS idx_tradition_access_level ON tradition_access_policies(access_level);

INSERT OR IGNORE INTO entities(id,canonical_name,name_zh,original_name,transliteration,primary_type,primary_civilization_id,primary_region_id,historical_period,description,research_status,evidence_status,record_version,metadata_json,created_at,updated_at) VALUES
('concept.yoruba.living_tradition_access','Yoruba living-tradition access governance','约鲁巴活态传统访问治理',NULL,NULL,'CONCEPT','civ.yoruba','region.west_africa','Contemporary ethical research governance','连接 Ifá、Ṣàngó 公开资料与权限规则；权限记录不是神话事实，也不授予采集秘密内容的许可。 / Governance layer for public, attributed, permission-required and prohibited collection scopes.','PARTIAL','SOURCE_BACKED',1,'{"governance_layer":true,"permission_is_not_implied_by_public_url":true}','2026-08-27T16:00:00Z','2026-08-27T16:00:00Z'),
('concept.maori.iwi_variant_scope','Māori iwi/hapū variant and attribution scope','毛利 iwi／hapū 版本与署名范围',NULL,NULL,'CONCEPT','civ.maori','region.oceania','Living traditions and modern curated publication','记录各部族版本差异、作者署名与权限边界；不制造单一“毛利标准版”。 / Governance and comparison layer preserving iwi/hapū variation and attribution.','PARTIAL','SOURCE_BACKED',1,'{"single_standard_version":false,"community_attribution_required":true}','2026-08-27T16:00:00Z','2026-08-27T16:00:00Z');
INSERT OR IGNORE INTO entity_classifications(entity_id,type_code,is_primary,notes) SELECT id,primary_type,1,'v0.23.0 living-tradition permissions' FROM entities WHERE created_at='2026-08-27T16:00:00Z';
INSERT OR IGNORE INTO entity_civilizations(entity_id,civilization_id,association_role,certainty,notes) SELECT id,primary_civilization_id,'COMMUNITY_GOVERNANCE_CONTEXT','SUPPORTED','v0.23 scoped association' FROM entities WHERE created_at='2026-08-27T16:00:00Z';
INSERT OR IGNORE INTO names(id,entity_id,name_text,normalized_text,language_id,script_name,name_type,is_preferred,source_id,notes) VALUES
('name.v0230.yoruba_access','concept.yoruba.living_tradition_access','Yoruba living-tradition access governance','yoruba living tradition access governance','lang.en','Latin','DESCRIPTIVE',1,'source.yoruba.ifa.unesco','Modern project-governance label.'),
('name.v0230.maori_scope','concept.maori.iwi_variant_scope','Māori iwi/hapū variant and attribution scope','maori iwi hapu variant attribution scope','lang.mai','Latin','DESCRIPTIVE',1,'source.maori.creation.teara','Modern project-governance label.');

INSERT OR IGNORE INTO tradition_access_policies(id,entity_id,source_id,authority_name,community_context,access_level,permitted_scope,prohibited_scope,attribution_requirement,permission_contact_or_process,policy_basis,reviewed_at,notes) VALUES
('policy.ifa.public_context','text.yoruba.ifa_corpus','source.yoruba.ifa.unesco','UNESCO ICH public registry and named Yoruba custodial communities','Ifá as a living Yoruba divination and oral-knowledge tradition','PUBLIC_CONTEXT','UNESCO public summary, safeguarding context and registry metadata','Full verse corpus, initiatory instruction, lineage-restricted interpretations and non-public ritual detail','Cite UNESCO and identify the public registry scope','Use named community/lineage authority for anything beyond the public page','Source scope plus project non-extraction rule','2026-08-27','A public URL does not make the whole tradition public domain.'),
('policy.ifa.restricted','text.yoruba.ifa_corpus','source.yoruba.ifa.unesco','Relevant Ifá lineage/community custodians','Lineage-specific, initiatory or non-public knowledge','DO_NOT_COLLECT','None in this public research pipeline','Secret verses, initiatory sequences, divination-client data, restricted ritual instructions and lineage-confidential interpretations','Not applicable because collection is prohibited','A separately authorized community-led project would be required; this database must not repurpose such permission','Precautionary community-governance rule','2026-08-27','Explicit hard stop for collection and storage.'),
('policy.sango.public_festival','festival.yoruba.sango_oyo','source.yoruba.sango_festival.unesco','Oyo Ṣàngó Festival communities and UNESCO ICH public registry','Publicly documented festival and safeguarding context','ATTRIBUTION_REQUIRED','Official public festival description, inscription decision and public safeguarding information','Non-public rites, restricted spaces, participant personal data and claims of authority not stated by custodians','Cite UNESCO record and name Oyo community context','Refer non-public questions to authorized Oyo institutions/custodians','Source terms and living-tradition attribution rule','2026-08-27','Public festival visibility does not erase ritual boundaries.'),
('policy.sango.restricted','festival.yoruba.sango_oyo','source.yoruba.sango_festival.unesco','Authorized Oyo custodians','Non-public ritual and interior community knowledge','PERMISSION_REQUIRED','Only material specifically released by an authorized custodian for the stated use','Secret or restricted rites, interior locations, unconsented participant data and generalized Yoruba-wide claims','Record named authority, scope and date of permission per claim','Obtain explicit purpose-specific permission before collection','Community authority and least-collection rule','2026-08-27','No permission is inferred from museum or UNESCO publication.'),
('policy.ose_sango.museum','artifact.yoruba.ose_sango','source.yoruba.ose_sango.met.1983_603_5','Metropolitan Museum of Art for object metadata; Yoruba custodians for living meaning','Museum object metadata and living religious context are separate authority layers','ATTRIBUTION_REQUIRED','Catalogue number, material, dimensions, custody and museum-published interpretation','Image reuse outside terms, secret ritual use or treating a museum object as exhaustive community authority','Cite catalogue and distinguish curator interpretation from community authority','Seek custodial authority for non-public living-practice claims','Museum catalogue scope plus living-tradition distinction','2026-08-27',NULL),
('policy.maori.teara_public','text.maori.creation_traditions','source.maori.creation.teara','Te Ahukaramū Charles Royal / Te Ara','Public, named, curated synthesis of Māori creation traditions','ATTRIBUTION_REQUIRED','Public text under stated CC BY-NC terms, with author and source attribution','Generalizing the synthesis as every iwi/hapū version; reusing non-text media without checking its terms','Attribute Te Ahukaramū Charles Royal and Te Ara; preserve page licence limits','Commercial reuse or non-text media requires the stated source process','Te Ara citation and licence notice','2026-08-27','Public synthesis explicitly says tribes have different versions.'),
('policy.maori.iwi_variants','text.maori.creation_traditions','source.maori.creation.teara','Relevant iwi/hapū authority for a named variant','Community-specific creation narratives and whakapapa','PERMISSION_REQUIRED','A public community-published account, or material supplied under explicit scoped permission','Unattributed pan-Māori synthesis, restricted whakapapa, sacred detail or reuse beyond consent','Name iwi/hapū, speaker/author, publication and permission scope','Obtain permission from the relevant authority for non-public or community-specific material','Community-specific attribution and variation rule','2026-08-27','Not all iwi share an Io tradition; variation is a first-class data property.'),
('policy.maori.restricted_whakapapa','text.maori.creation_traditions',NULL,'Relevant iwi/hapū and knowledge holders','Restricted whakapapa or sacred community knowledge','DO_NOT_COLLECT','None unless a future community-led system explicitly changes the storage model','Restricted genealogies, sacred knowledge and material whose publication status or authority is unclear','Not applicable because collection is prohibited by default','Do not solicit or store; refer to community authority','Precautionary Indigenous data-governance rule','2026-08-27','Default-deny for ambiguity.');

INSERT OR IGNORE INTO claims(id,subject_id,predicate,object_entity_id,object_literal,object_datatype,statement,variant_group,claim_status,confidence,confidence_level,review_status,assertion_scope,knowledge_layer,tradition_scope,temporal_scope,research_notes,created_at) VALUES
('claim.v0230.ifa_public_registry','text.yoruba.ifa_corpus','PUBLICLY_CONTEXTUALIZED_BY',NULL,'UNESCO Intangible Cultural Heritage public registry','text','The project may retain the public UNESCO context for Ifá while applying stricter limits to non-public knowledge.','living_access.ifa','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Ifá public safeguarding context','current registry','This does not authorize corpus extraction.','2026-08-27T16:00:00Z'),
('claim.v0230.ifa_policy','text.yoruba.ifa_corpus','GOVERNED_BY','concept.yoruba.living_tradition_access',NULL,NULL,'The Ifá dossier is governed by explicit living-tradition access policies.','living_access.ifa','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.ifa_no_secret','concept.yoruba.living_tradition_access','PROHIBITS_COLLECTION_OF',NULL,'secret verses, initiatory instructions, divination-client data and lineage-restricted interpretations','text','The public research pipeline must not collect or store restricted Ifá knowledge.','living_access.ifa','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current','Ethical access rule, not a description of the content.','2026-08-27T16:00:00Z'),
('claim.v0230.sango_registry','festival.yoruba.sango_oyo','PUBLICLY_CONTEXTUALIZED_BY',NULL,'UNESCO Intangible Cultural Heritage public registry and inscription decision','text','The public festival and safeguarding context may be recorded with attribution.','living_access.sango','SUPPORTED',0.99,'HIGH','VERIFIED','HISTORICAL_REALITY','RITUAL_PRACTICE','Oyo Ṣàngó Festival','current registry',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.sango_policy','festival.yoruba.sango_oyo','GOVERNED_BY','concept.yoruba.living_tradition_access',NULL,NULL,'The festival dossier uses public, attributed and permission-required access levels.','living_access.sango','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.sango_limit','concept.yoruba.living_tradition_access','REQUIRES_PERMISSION_FOR',NULL,'non-public rites, restricted spaces and participant-specific data','text','Non-public Ṣàngó material requires purpose-specific authority rather than inference from a public listing.','living_access.sango','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.maori_many','text.maori.creation_traditions','HAS_VARIANTS',NULL,'many traditions with tribe-specific versions and common themes','text','Te Ara states that Māori have many creation traditions and that tribes tell different versions.','living_access.maori','SUPPORTED',0.99,'HIGH','VERIFIED','IN_TRADITION','TEXTUAL_WITNESS','Te Ara public synthesis','published 2009','Attribute the named author; do not generalize as one standard text.','2026-08-27T16:00:00Z'),
('claim.v0230.maori_io','text.maori.creation_traditions','HAS_VARIANTS',NULL,'not all tribes have an Io tradition','text','The public synthesis explicitly notes that not all tribes have an Io tradition.','living_access.maori','SUPPORTED',0.99,'HIGH','VERIFIED','IN_TRADITION','TEXTUAL_WITNESS','Te Ara public synthesis','published 2009',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.maori_scope','concept.maori.iwi_variant_scope','DERIVED_FROM','text.maori.creation_traditions',NULL,NULL,'The governance node responds to the source’s explicit statement of tribal variation.','living_access.maori','SUPPORTED',0.99,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.maori_no_standard','concept.maori.iwi_variant_scope','PRESERVES_DISTINCTION',NULL,'iwi/hapū versions, named authorship, public licence and permission scope','text','The project does not construct a single canonical Māori creation version.','living_access.maori','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z'),
('claim.v0230.maori_permission','concept.maori.iwi_variant_scope','REQUIRES_PERMISSION_FOR',NULL,'non-public community-specific narratives, restricted whakapapa and sacred detail','text','Community-specific non-public material is default-deny unless an appropriate authority grants scoped permission.','living_access.maori','SUPPORTED',1.0,'HIGH','VERIFIED','SCHOLARLY_INTERPRETATION','SCHOLARLY_INTERPRETATION','Project governance','current',NULL,'2026-08-27T16:00:00Z');

INSERT OR IGNORE INTO evidence(id,claim_id,source_id,source_location,evidence_type,direction,strength,research_notes)
SELECT 'evidence.'||substr(c.id,7),c.id,
 CASE WHEN c.id LIKE 'claim.v0230.ifa_%' THEN 'source.yoruba.ifa.unesco' WHEN c.id LIKE 'claim.v0230.sango_%' THEN 'source.yoruba.sango_festival.unesco' ELSE 'source.maori.creation.teara' END,
 'Public authority or named curated synthesis; access policy adds a precautionary project rule','OFFICIAL_SITE','SUPPORTS',c.confidence,'No restricted traditional content stored' FROM claims c WHERE c.id LIKE 'claim.v0230.%';

UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Maintain hard DO_NOT_COLLECT rule; only add public safeguarding metadata or community-led permission updates',updated_at='2026-08-27T16:00:00Z' WHERE id='queue.ifa.permission_model';
UPDATE collection_queue SET status='BASELINE_COMPLETE',attempts=attempts+1,next_action='Add named Oyo authority contacts only from public institutional records; non-public rites remain permission-gated',updated_at='2026-08-27T16:00:00Z' WHERE id='queue.v060.yoruba.sango_permissions';
UPDATE collection_queue SET status='PARTIAL',attempts=attempts+1,next_action='Register each public iwi/hapū variant with named authority, author, licence and permission scope; never infer a single standard version',updated_at='2026-08-27T16:00:00Z' WHERE id='queue.polynesia.iwi_variants';
INSERT OR IGNORE INTO collection_queue(id,target_label,normalized_label,proposed_entity_type,civilization_id,discovered_from_entity_id,discovered_from_claim_id,discovered_from_source_id,discovery_context,priority,status,attempts,next_action,created_at,updated_at) VALUES
('queue.v0230.permissions.review','Periodic review of living-tradition access policies','living tradition permission policy review','CONCEPT','civ.yoruba','concept.yoruba.living_tradition_access','claim.v0230.ifa_no_secret','source.yoruba.ifa.unesco','Authority pages, licences and community preferences can change.',100,'SOURCE_FOUND',0,'Review public authority, licence, prohibited scope and contact process before every future living-tradition batch','2026-08-27T16:00:00Z','2026-08-27T16:00:00Z'),
('queue.v0230.maori.named_iwi_sources','Named iwi/hapū public creation-tradition sources','maori named iwi hapu sources','ORAL_TRADITION','civ.maori','concept.maori.iwi_variant_scope','claim.v0230.maori_many','source.maori.creation.teara','Te Ara establishes variation but is a synthesis, not every community’s own authority record.',98,'SOURCE_FOUND',0,'Prioritize iwi/hapū official publications and record attribution, licence and access policy per claim','2026-08-27T16:00:00Z','2026-08-27T16:00:00Z');

INSERT OR IGNORE INTO research_sessions(id,started_at,ended_at,scope,strategy,status,agent_or_process,notes) VALUES('research.20260827.v0230_living_permissions','2026-08-27T15:05:00Z','2026-08-27T16:00:00Z','Ifá, Ṣàngó and Māori living-tradition access governance','Store public authority context and explicit access policies; default deny for secret, initiatory, restricted or ambiguously authorized material','CHECKPOINT_COMPLETE','Codex persistent research pipeline','No secret Ifá verses, restricted rites or whakapapa collected.');
UPDATE project_metadata SET value='0.23.0-living-tradition-permissions-20260827',updated_at='2026-08-27T16:00:00Z' WHERE key='data_version';
UPDATE project_metadata SET value='32',updated_at='2026-08-27T16:00:00Z' WHERE key='schema_version';
UPDATE project_metadata SET value='2026-08-27T16:00:00Z',updated_at='2026-08-27T16:00:00Z' WHERE key='generated_at';
INSERT OR IGNORE INTO dataset_releases(id,schema_version,data_version,git_commit,built_at,database_sha256,release_notes) VALUES('release.0.23.0',32,'0.23.0-living-tradition-permissions-20260827',NULL,'2026-08-27T16:00:00Z',NULL,'Living-tradition governance checkpoint: persistent four-level access policies for Ifá, Oyo Ṣàngó public/restricted contexts and Māori iwi/hapū variant attribution; restricted knowledge is not collected.');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(32,'20260827_v0230_living_tradition_permissions','2026-08-27T16:00:00Z');
COMMIT;
